### ISSUE TITLE
Flaky Test - hostmetricsreceiver/internal/scraper/loadscraper/TestScrape

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#10030]
```
=== CONT  TestScrape
    load_scraper_test.go:150: 
        	Error Trace:	load_scraper_test.go:150
        	            				load_scraper_test.go:133
        	Error:      	"0.6975" is not less than "0.67"
        	Test:       	TestScrape
--- FAIL: TestScrape (0.00s)
```

Observed here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6456854842?check_suite_focus=true#step:7:3948

**Comment by zeno-splunk** [comment]
Hello @djaglowski 

I'm currently dealing with the issue and I was wondering if you could assist me.

I have successfully run the code on my pull request (PR) and local environment. 
However, I'm unable to trace the issue because the logs have expired after one year and I can't rerun them. 
Is it possible for you to provide me with some test data that I can use for debugging purposes?

Additionally, I would greatly appreciate your assistance in removing the skip test on line 36 of the file hostmetricsreceiver/internal/scraper/loadscraper/load_scraper_test.go and run the test again.

```
func TestScrape(t *testing.T) {
	skip(t, "Flaky test. See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10030") // remove this
	type testCase struct {
```

Thank you for your support.

**Comment by ZenoCC-Peng** [comment]
Hello, I am currently review this test.

Upon running 20 times the GitHub Action on my personal branch, there were no test failures for the receiver. Here is the file [Hostmetricsreceiver-FlakyTest-#10030.xlsx](https://github.com/open-telemetry/opentelemetry-collector-contrib/files/11911022/Hostmetricsreceiver-FlakyTest-.10030.xlsx).

Someone modified the code, see the  #10301 

If everything seems fine, I will proceed with pulling request.

**Comment by mx-psi** [comment]
I reverted #23874, since it seems like the test is still either flaky or consistently failing on Windows.

**Comment by ZenoCC-Peng** [comment]
Hi,
I have identified an issue related to testing in the Windows environment.
Due to time constraints, I am handing over the issue of this matter to others.

The problem seems to stem from the possibility that Windows may encounter difficulties in fetching data.
You can refer to the following link for more details: https://github.com/shirou/gopsutil/blob/master/load/load_windows.go#L67

I have been working on a solution which involves using a for loop. You can find my proposed solution in the following link: https://github.com/ZenoCC-Peng/opentelemetry-collector-contrib/pull/15/files

Initially, when I tested the build-and-test-windows.yml workflow with my solution, it was successful.
However, when I executed the entire workflow, the build-and-test-windows.yml occasionally failed.
I suspect that the issue might be related to the order in which the workflow tasks are executed.

**Comment by michalpristas** [comment]
looking at this
