### ISSUE TITLE
[exporter/dynatrace] Are resources attributes being ignored ?

### ISSUE THREAD

**Issue by alefcarlos** [open-telemetry/opentelemetry-collector-contrib#10586]
### Discussed in https://github.com/open-telemetry/opentelemetry-collector-contrib/discussions/10581

<div type='discussions-op-text'>

<sup>Originally posted by **alefcarlos** June  2, 2022</sup>
I'm testing dynatrace metrics exporter and I enriched with one agent information.

This article explains how
https://www.dynatrace.com/support/help/extend-dynatrace/extend-metrics/reference/enrich-metrics

So, I added those dimensions to resource attributes, but dynatrace is not ingesting those informations.

I added the logging exporter to debug:

```

2022-06-03T02:17:44.525Z        INFO    loggingexporter/logging_exporter.go:57  MetricsExporter {"#metrics": 1}
2022-06-03T02:17:44.525Z        DEBUG   loggingexporter/logging_exporter.go:67  ResourceMetrics #0
Resource SchemaURL:
Resource labels:
     -> service.name: STRING(WebApi1)
     -> service.version: STRING(0.1.0.0)
     -> service.instance.id: STRING(poc-otl-webapi1-547c654f99-m852p)
     -> dt.entity.process_group_instance: STRING(PROCESS_GROUP_INSTANCE-5A0F7F0066278195)
     -> dt.entity.host: STRING(HOST-D187A6CF47B6C81E)
ScopeMetrics #0
ScopeMetrics SchemaURL:
InstrumentationScope Super.WebApi 1.0.0
Metric #0
Descriptor:
     -> Name: TransactionAuthorized2
     -> Description:
     -> Unit:
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_CUMULATIVE
NumberDataPoints #0
Data point attributes:
     -> my_label: STRING(value1)
StartTimestamp: 2022-06-03 02:10:58.1750046 +0000 UTC
Timestamp: 2022-06-03 02:17:25.9024442 +0000 UTC
Value: 7
```

We can see that `resource labels` contains `dt.*` attibutes, but on Dynatrace Metrics Explorer did not:

![image](https://user-images.githubusercontent.com/5452336/171774025-978410bc-dd3a-4c71-808d-8429b9631a06.png)

Is it a bug or am I doing that wrong ?

To read dynatrace one agent file and append to resource build I have followed this article:

https://www.dynatrace.com/support/help/extend-dynatrace/opentelemetry/opentelemetry-traces/opentelemetry-ingest/opent-dotnet#send

</div>

**Comment by arminru** [comment]
Hi @alefcarlos! Thank you for you question.

Both data point attributes and resource attributes are available as metric dimensions in Dynatrace.
Dimensions from resource attributes are, however, not created automatically. 

To have dimensions created from the resource attributes, you can do either of the following:

1. Use the [resourcetotelemetry](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/resourcetotelemetry) exporter helper by adding the following config flag:

```
  dynatrace:
    endpoint: ...
    api_token: ...  
    resource_to_telemetry_conversion:
        enabled: true
```

Note that this will add ALL available resource attributes as data point attributes and consequently dimensions.
Depending on how many resource attributes you plan to send, you might need to do some filtering.
Currently, Dynatrace accepts a maximum of 50 dimensions per metric.

2. You could set the `dt.*` attributes directly as data point attributes (instead of the resource) in your application.
You would need to do this for all of your metric instruments, so this would require quite some manual work.

3. You could use the [Dynatrace SDK exporter for .NET](https://github.com/dynatrace-oss/opentelemetry-metric-dotnet) to directly export metrics from your application to Dynatrace without the need for a collector.
The exporter will directly take the `dt.*` attributes from the OneAgent, if available, and add it as dimensions on your metrics (without populating or reading the resource).

We are also working on a native OTLP ingest endpoint for metrics with which you would not need to use any Dynatrace-specific exporter at all. It is currently expected to become available later this year.
If you'd like to discuss your use cases and how the proposed solutions work for you, I can also connect you to one of our product managers in this area. I'm sure they'd love to learn more.

Let me know if that helps 🙂

**Comment by alefcarlos** [comment]
@arminru, Hi!

I'm using de second option now, but i will test that configuration on collector:

```
    resource_to_telemetry_conversion:
        enabled: true
```

It would be cool to update documentation regarding that configuration.

Thank you so much for the response ;)

**Comment by alefcarlos** [comment]
Hi, @arminru. I'm closing this issue, cause the collector now sends the resource attributes using that configuration. I just wanted to send the `dt.*` attributes to Dynatrace ;)
