### ISSUE TITLE
New component json log exporter

### ISSUE THREAD

**Issue by yotamloe** [open-telemetry/opentelemetry-collector-contrib#10836]
## The purpose and use-cases of the new component
This exporter lets you send log records as JSON bytes to a generic HTTP(S) endpoint.
Will be similar to [fluentbit](https://docs.fluentbit.io/manual/pipeline/outputs/http) and [fluentd](https://docs.fluentd.org/output/http) HTTP outputs.
An example use case can be forwarding logs to log management backends via logstash ([example1](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-http.html), [example2](https://logit.io/sources/configure/json))

Our team at logz.io already implemented such an exporter in our vendor-specific component `logzioexporter` ([ref from my fork](https://github.com/yotamloe/opentelemetry-collector-contrib/blob/logzioexporter-logs-support/exporter/logzioexporter/exporter.go#L131-L157)) to support logging with open telemetry collector. We thought others in the community could find it useful so we decided to contribute the log exporter as a non-specific vendor component if the community will approve it.

## Example configuration for the component
```YAML
exporters:
  jsonlog:
    endpoint: https://api.example.com/logs
    gzip_compression: true
```
Plus [exporterhelper](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/README.md) options
## Telemetry data types supported
Logs

**Comment by djaglowski** [comment]
What defines the format used [here](https://github.com/yotamloe/opentelemetry-collector-contrib/blob/a0cfc1eb82edeac6396ce8f06b90dbc8c8f84a3f/exporter/logzioexporter/jsonlog.go#L57)?

We have an experimental spec for serializing signals to json, [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/experimental/serialization/json.md#telemetry-data-requirements). Could this component use that format instead?

**Comment by bogdandrutu** [comment]
Should this be part of a "file exporter" that allows to export any signal in proto/json or any "marshaler" that we support? @djaglowski do we have such thing?

**Comment by djaglowski** [comment]
Not to my knowledge. There would be a lot of overlap between exporting signals as json to a file and exporting signals as json to an endpoint. Seems like they'd share code but probably still should be separate exporters.

**Comment by tigrannajaryan** [comment]
Is this some specific JSON format that is different from OTLP/JSON? If it is OTLP/JSON then I think the best place for it is `otlphttpexporter`. We can an option to this exporter to specify whether to use binary Protobuf or JSON as the format.

**Comment by yotamloe** [comment]
Hi @tigrannajaryan 

The format we use for logz.io single log entry is essentially a `map[string]interface{}` that includes the log record fields (`severityNumber`,`traceId`,`sapnId`, timestamp, etc.), log record attributes, and resource attributes associated with the log record. In addition, we also try to "flat" the log body if the value type is `ValueTypeMap` ([code](https://github.com/yotamloe/opentelemetry-collector-contrib/blob/logzioexporter-logs-support/exporter/logzioexporter/jsonlog.go#L83-L91)), and add more log fields.

Our general approach is to separate `ExportLogsServiceRequest` into individual log entries with all the metadata that we can collect.

Take this JSON representation of`ExportLogsServiceRequest` for example:
```json
{
  "resourceLogs": [
    {
      "resource": {
        "attributes": [
          {
            "key": "resource-attr",
            "value": {
              "stringValue": "resource-attr-val-1"
            }
          }
        ]
      },
      "instrumentationLibraryLogs": [
        {
          "instrumentationLibrary": {},
          "logs": [
            {
              "timeUnixNano": "1581452773000000789",
              "severityNumber": "SEVERITY_NUMBER_INFO",
              "severityText": "Info",
              "name": "logA",
              "body": {
                "stringValue": "This is a log message"
              },
              "attributes": [
                {
                  "key": "app",
                  "value": {
                    "stringValue": "server"
                  }
                },
                {
                  "key": "instance_num",
                  "value": {
                    "intValue": "1"
                  }
                }
              ],
              "droppedAttributesCount": 1,
              "traceId": "08040201000000000000000000000000",
              "spanId": "0102040800000000"
            }
          ]
        }
      ]
    }
  ]
}
```
Will be converted to this format:
```json
{
  "@timestamp": "1581452773000000789",
  "traceId": "08040201000000000000000000000000",
  "spanId": "0102040800000000",
  "level": "Info",
  "resource-attr": "resource-attr-val-1",
  "app": "server",
  "instance_num": "1",
  "message": "This is a log message"
}
```
If the `ExportLogsServiceRequest` contains more than one log, the JSON logs will be appended to the exported byte array, separated by a new line. ([code](https://github.com/yotamloe/opentelemetry-collector-contrib/blob/logzioexporter-logs-support/exporter/logzioexporter/exporter.go#L146))
I hope that makes sense.
Please feel free, if you guys have any comments or suggestions.

**Comment by tigrannajaryan** [comment]
> Will be converted to this format...

This conversion loses data (e.g. instrumentationLibrary/Scope data is missing) and has ambiguities (what happens if I have a LogRecord attribute named "resource-attr" or named "spanId"?). I do not see the justification why this format needs to be chosen as a canonical format endorsed by Otel Collector.

IMO, if we want to have a exporter that is given a generic name "jsonexporter" then it needs to be:
1. Lossless and capable of non-ambiguously representing all pdata.
2. If it is not OTLP/JSON then have a clear justification why it deviates from it.
3. Follows [Otel recommendations](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/overview.md#trace-context-in-legacy-formats) for trace context in text formats (see e.g. "traceId" vs "trace_id").
4. Follows Otel terminology (why "level" instead of "severity"?).

For now I don't see see 1-4 fulfilled. 

My preference to move forward with this initiative would be to:
1. Add OTLP/JSON support to `otlphttpexporter`.
2. If we want to give the user another JSON exporter with more control to choose the shape of the emitted JSON data then implement a new `httpexporter` or `jsonhttpexporter`, where the user has knobs to customize the shape of the created JSON data. If a specific JSON structure is somehow significant (how?) then make it the default for the new exporter. If this JSON structure proves to be nice and useful, make an OTEP to propose it as some form of standard for Otel.

**Comment by yotamloe** [comment]
Sure that makes sense.
I was presenting the (beta) format we use for vendor-specific preferences. I agree that this initiative should follow 1-4. Thanks for the feedback!

**Comment by halcyondude** [comment]
+1, in particular it's critical that using the json exporter retains full data fidelity and is [lossless](https://en.wikipedia.org/wiki/Lossless_compression)
