### ISSUE TITLE
[processor/transform]: add replace_regex_match config setting to replace attributes/metrics based on regex pattern

### ISSUE THREAD

**Issue by davidmirza408** [open-telemetry/opentelemetry-collector-contrib#11118]
**Is your feature request related to a problem? Please describe.**
This issue relates to transformprocessor.  replace_match relies on wild cards to find a pattern to replace a string.  In some scenarios where the location of the portion of the string to replace is not clear, a regex expression may be more appropriate.  One such example would be a hostmetricsreceiver reporting command line parameters.  Sensitive data like a password or apikey may be passed in any order.  
  
**Describe the solution you'd like**
I would like to introduce a config setting called replace_regex_match which would operate much like replace_match but using regex patterns.  

Note: approval of this feature may mean that we can deprecate replace_match.  I am interested in opinions on this.

**Describe alternatives you've considered**
None

**Additional context**
None

I already have an implementation that I can submit for PR.

cc @TylerHelmuth

**Comment by TylerHelmuth** [comment]
@anuraaga was just saying that as soon as we add glob matching someone will ask for regex haha 😄 

Yes a `replace_regex_match` would be a good feature.  Maybe instead of a new function we can update `replace_match` and `replace_all_matches` to take a third parameter that switching the function between Glob and Regexp.  The pattern would be used to create the appropriate object in the function and then the replacement would still be used verbatim when there is a match.  Would that work?

**Comment by davidmirza408** [comment]
@TylerHelmuth, do you think I should remove replace_all_matches and replace_match or deprecate them
