### ISSUE TITLE
Can't use traceID in transform processor because it returns struct

### ISSUE THREAD

**Issue by davidgargti20** [open-telemetry/opentelemetry-collector-contrib#11555]
trace_id: Currently accessed as a TraceID struct so does not work in conditions.
The transform processor's Getters normally returns a field as the type it is represented in pdata. This can cause problems when the field is used in set expression. I cannot use traceId as it is returned as struct.

**Comment by TylerHelmuth** [comment]
@davidgargti20 I believe this issue (and all other similar pdata issues sans enums) have been handled in this issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10350.  Collector Contrib 0.54.0 should have the fixes you need.

**Comment by davidgargti20** [comment]
@TylerHelmuth but I don't think it has been handled for get it still returning struct for set traceid it has been handled

**Comment by TylerHelmuth** [comment]
@davidgargti20 trace_id, span_id, and parent_span_id are all returned as a pcommon.TraceID or pcommon.SpanID struct and should be interacted with via the TraceID/SpanID Factory functions.

The syntax looks like:

`set(span_id, SpanID(0x0807060504030201)) where span_id == SpanID(0x0000000000000000)`
`set(trace_id, TraceID(0x0102030405060708090a0b0c0d0e0f10)) where trace_id == TraceID(0x00000000000000000000000000000000)`

As part of the issue I linked we landed at byte literals and factory functions instead of converting the IDs to strings bc it was more performant.

**Comment by davidgargti20** [comment]
@TylerHelmuth but this way it actually underperform its use
I basically want to do 
set(attributes["traceId"],trace_id) 
but it doesn't work as it return struct
if we return it as string or bytes we can do this as well as comaprison

**Comment by TylerHelmuth** [comment]
Yes I would agree that use case will not work, and I think thats probably a good thing.  I would _strongly_ recommend never setting an attribute value to be a trace id or span id as the cardinality will be off the charts.

That said, supporting trace and span IDs as strings at some point in the future was discussed in the PR where we added the TraceID and SpanID factories.  We could add that capability via another Factory function.  A generic Factory function like `String` that converts any field passed to it to a string could be useful.  

That would allow you to do something like `set(attributes["traceId"], String(trace_id)) `, but again, that is a very dangerous scenario.

**Comment by TylerHelmuth** [comment]
High cardinality attributes are not necessarily bad, but can come with unwanted consequences.  In general, high cardinality is expensive, both from a performance perspective when you want to use the data but also from a cost perspective.  

The higher the cardinality on an attribute the more aggregating that needs to happen when using the data and/or the more data that needs to be returned when querying the data.  

The higher the cardinality of an attribute may also cost you more, either because your vendor charges you or bc it takes more space for your to store the data yourself.

This rule is not universal though.  For example, no one will complain about adding k8s.pod.uid as a resource attribute.  But thats because there isn't an alternative.  For trace id and span id they are already defined as their own fields so it recommended not to add them a second time anywhere else.

But I see what you are trying to do.  It is unfortunate that the [groupbytrace processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/groupbytraceprocessor) doesn't support logs.  Maybe open an issue requesting that if there isn't already an issue for it? 

In the meantime, for the use case you are trying to accomplish, I think a `String()` factory is a good approach.  This will keep most span and trace ID operations as performant as possible while allowing string usage where necessary.  I would say you drop the attribute after you are done grouping though.  Configuring 2 transform processors, 1 to use to add the trace id before grouping and one to remove the attribute after grouping, might be a good idea.  The transform processor doesn't have a succinct way to drop attributes yet (keep_keys is probably the closet), we might need a `drop_keys` function as well.

Another approach would be to add a function to the transform processor that can do the grouping you want instead of using the groupbyattributes processor.  [Grouping is called out as a wanted capability of the Telemetry Query Language](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/processing.md#grouping), but we haven't implemented it yet.

**Comment by davidgargti20** [comment]
So can a String() factory be included in the transform processor?
It will definitely be helpful in some scenarios.

**Comment by davidgargti20** [comment]
Sure

**Comment by CatalinAdlerDF** [comment]
@TylerHelmuth is there an official way to implement tail-based sampling for all the telemetry data part of a trace: logs, traces and metrics?
Basically "collect everything about a trace, and sample it if some condition is true".

I am referring to individual log entries that have the trace_id and span_id set correctly.

**Comment by TylerHelmuth** [comment]
> is there an official way to implement tail-based sampling for all the telemetry data part of a trace

I don't think so.

**Comment by mvillafuertem** [comment]
Hi @TylerHelmuth, my traceIDs are UUIDs, how should I set the trace_id field? Thanks
```yaml
              - set(trace_id.string, cache["traceId"]) where trace_id.string == nil or trace_id.string == ""
              - set(trace_id.string, cache["traceID"]) where trace_id.string == nil or trace_id.string == ""

```
