### ISSUE TITLE
[processor/transform] Add support for toggling scalar value types

### ISSUE THREAD

**Issue by Mrod1598** [open-telemetry/opentelemetry-collector-contrib#11810]
**Is your feature request related to a problem? Please describe.**
When collecting from prometheus, a `value_type` is assigned and sometimes incorrectly. Using this processor, it should be possible to toggle from double to int or the other way around in this processor.

**Describe the solution you'd like**
implementation of either the ability to use the set function to change it, or a new function to toggle it for a metric separate from the set function.

**Comment by TylerHelmuth** [comment]
@Mrod1598 the metrics context allows accessing (Get and Set) of a scalar value using `value_double` and `value_int`.  You can update a NumberDataPoint's value using set.  I added this test locally in `metrics/processor_test.go` and it passed

```Go
{
	query: []string{`set(value_int, 2) where value_double == 1.0`},
	want: func(td pmetric.Metrics) {
		td.ResourceMetrics().At(0).ScopeMetrics().At(0).Metrics().At(0).Sum().DataPoints().At(0).SetIntVal(2)
	},
},
```

**Comment by Mrod1598** [comment]
Got it thanks! is that documented somewhere that I missed?

**Comment by TylerHelmuth** [comment]
> Got it thanks! is that documented somewhere that I missed?

I think this is an instance where the README's statement of "everything can be accessed using the OTLP protobuf names" isn't completely honest.  To handle how pdata represents the protobuf's requirements of value for NumberDataPoint the TQL had to make up a accessor and `value_double` and `value_int` were chosen.  There are some other scenarios like that that should be improved in the README.  In fact the whole README is getting kinda messy.  I plan to address it with https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/11751.

> wait actually isn't that changing the value of the actual data point and not toggling the type? my scenario is where the value is stored as a double but should be stored as an int.

pdata (what the Transform Processor is beholden to) doesn't have a concept of "change the value type without changing the value.  pdata allows you to check the value type, but not set it.  It allows you to set an int value (which updates the value type) and set a double value (which updates the value type)

For your scenario I tried:

```yaml
set(value_int, value_double)
```

Which doesn't work because the float64 returned by `value_double` could not be asserted as an `int64` during `value_int`'s type assertion where it looks for an int64.  So I actually don't think the TQL can handle this scenario right now bc it doesn't know to cast.

**Comment by TylerHelmuth** [comment]
I think we need a new Factory function that lets you cast to a Int.  then we could do 

```yaml
set(value_int, Int(value_double))
```

**Comment by deepto98** [comment]
Can I pick this up?

**Comment by TylerHelmuth** [comment]
@deepto98 It's yours

**Comment by TylerHelmuth** [comment]
@mcdoker18 do you plan to update the transform processor with the new function?

**Comment by mcdoker18** [comment]
@TylerHelmuth sorry for the delay, I was on vacation :)

**Comment by bogdandrutu** [comment]
@TylerHelmuth qqs on this:
1. Why not using the lower letters for this? `int()`
2. Can the setter for the `int_value` be changed and do the cast in this case instead of asking user to do this?

**Comment by TylerHelmuth** [comment]
@bogdandrutu current naming guidelines are that Factory Functions be named with uppercase to differentiate from regular functions. 

We could probably update setters to be smarter, checking the passed in value and seeing if it can be casted. That would be a more generic solution if it works.
