### ISSUE TITLE
Use OpenTelemetry Collector Builder for local and CI builds

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#11867]
We currently rely on a custom [main.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/otelcontribcol/main.go) file to make Collector builds on CI and locally (if someone e.g. runs `make otelcontribcol`). 

For consistency with the core repository we could keep a manifest and use the [OpenTelemetry Collector Builder](https://github.com/open-telemetry/opentelemetry-collector/tree/main/cmd/builder). This would be beneficial in several ways:

- The core and contrib repositories are consistent in how they build.
- We dogfood the builder more often and are able to catch mistakes earlier, before doing an actual release.
- Our test builds are closer to the final build, avoiding possible deviations between our main.go file and the builder's one.

To do this, one would need to:
1. create a manifest.yaml based on the one in the [releases repository](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-contrib/manifest.yaml). Don't forget to add replaces for all modules
2. create a second manifest.yaml based on the [testbed components](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/8778b8731e926af9aaa6d804fd7ffd17ebcec3dc/cmd/otelcontribcol/main_testbed.go). (Same note about replaces)
3. Add the builder (`go.opentelemetry.io/collector/cmd/builder`) to the [`internal/tools` module](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/internal/tools) and to the [install-tools](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/8778b8731e926af9aaa6d804fd7ffd17ebcec3dc/Makefile#L221) task.
4. Modify the [`make otelcontribcol` task](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/8778b8731e926af9aaa6d804fd7ffd17ebcec3dc/Makefile#L284) and the [`make otelcontribcol-testbed` task](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/8778b8731e926af9aaa6d804fd7ffd17ebcec3dc/Makefile#L296) to use the builder for building the component
5. Remove the `cmd/otelcontribcol` folder. This will need to be done in a follow-up PR after deprecating it for one release. The Dockerfile file will need to be kept somewhere

**Comment by deepto98** [comment]
Can I pick this up?

**Comment by mx-psi** [comment]
@deepto98 do you plan to continue working on this or should I unassign you?

**Comment by mattsains** [comment]
if @deepto98 isn't working on this anymore, I'd like to take it on instead

**Comment by mattsains** [comment]
I've managed to update the build to use a manifest file I've written, but the manifest contains a lot of repetitive configuration which I think would be worth generating as part of the build. It's just a list of all the projects within the contrib repo, so I was thinking of using the Makefile variables like `RECEIVER_MODS`, `PROCESSOR_MODS`, etc., to fill in a yaml template which would be used by the builder.

I asked on Slack whether there is preferred tooling for doing this (yq?) but I have not heard back yet.

**Comment by mx-psi** [comment]
Automatically generating the list sounds good to me, it's what we already do in other places, see e.g. [this script](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/workflows/scripts/add-component-options.sh)

**Comment by mattsains** [comment]
I've been working on a script to generate the manifest file within opentelemetry-collector-contrib. However, I am having doubts about whether I can use the makefile variables I mentioned earlier.

For one thing, those variables are simply all the directories under the `receiver/`, `processor/` etc directories. This is quite different from the information in [the manifest file in opentelemetry-collector-releases](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-contrib/manifest.yaml) because it includes unreleased modules.

I'm trying to decide between the following options and would appreciate some input:

1. Reach out to github to download the manifest file from opentelemetry-collector-releases and modify it to include the replace entries. I think this is the best because the stated goal of this issue is to bring the build's collection generation to be as close as possible to the actual release build.
2. Get the information from [internal/components/components.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/components/components.go). This is where the information is currently (indirectly) obtained from, but I would need to massage this go file into configuration which I think is a bad idea
3. Use the information found in [versions.yaml](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/versions.yaml). I think this would be the best if we desire to have unreleased modules in the CI build process - which I don't think we do.

Where is the right place for me to get a list of all the modules we want the CI build to include? I don't want to simply copy-paste the release repo's copy, because this will fall out of date pretty quickly and introduce yet another place where manual updates have to be done any time there is a version bump or a new module added.

**Comment by jpkrohling** [comment]
Taking a step back, I believe this shouldn't be automated. Just like we manually add components to `internal/components/components.go` today, we should add them to the manifest when they are ready to be used. Ideally, we could parse the component's status and include them automatically once they get past the "in-development" stage.

As part of this change, the `components.go` facility should be removed.

> Reach out to github to download the manifest file from opentelemetry-collector-releases and modify it to include the replace entries

I'm not a huge fan of this idea, -releases depends on -contrib, we shouldn't make -contrib depend on -releases as well.

**Comment by jpkrohling** [comment]
Once you open the PR, please assign me as a reviewer, I would love to take a look at it.

**Comment by mattsains** [comment]
I took the release file, and modified it to include replaces like this:

```
cat manifest.yaml > manifestwithreplace.yaml

# Automatically add replaces for any package that exists in contrib
echo >> manifestwithreplace.yaml
sed -nE 's%.*github.com/open-telemetry/opentelemetry-collector-contrib/(extension|receiver|exporter)/([^/]+) (v[0-9.]+)%  - github.com/open-telemetry/opentelemetry-collector-contrib/\1/\2 \3 => ../\1/\2%p' manifest.yaml >> manifestwithreplace.yaml
```

In other words, any time it finds a module reference to something in contrib, it appends a replace directive to the end of the file.

However, running builder on it returns this error:

```
# github.com/grafana/loki/pkg/util/log
../../../go/pkg/mod/github.com/grafana/loki@v1.6.2-0.20221121081917-d3111bcaa774/pkg/util/log/log.go:24:22: undefined: log.LineBufferedLogger
../../../go/pkg/mod/github.com/grafana/loki@v1.6.2-0.20221121081917-d3111bcaa774/pkg/util/log/log.go:100:24: undefined: log.NewLineBufferedLogger
../../../go/pkg/mod/github.com/grafana/loki@v1.6.2-0.20221121081917-d3111bcaa774/pkg/util/log/log.go:101:8: undefined: log.WithFlushPeriod
../../../go/pkg/mod/github.com/grafana/loki@v1.6.2-0.20221121081917-d3111bcaa774/pkg/util/log/log.go:102:8: undefined: log.WithPrellocatedBuffer
../../../go/pkg/mod/github.com/grafana/loki@v1.6.2-0.20221121081917-d3111bcaa774/pkg/util/log/log.go:103:8: undefined: log.WithFlushCallback
```

I've managed to track it down to this replace: `github.com/open-telemetry/opentelemetry-collector-contrib/exporter/lokiexporter v0.66.0 => ../exporter/lokiexporter`

I'm not really sure why this is happening because I'm not a golang expert. I've attached the generated [manifest.yaml](https://github.com/open-telemetry/opentelemetry-collector-contrib/files/10135888/manifest.yaml.txt) I've got in case you are interested in trying it out for yourself - deleting line 222 makes it build for me. I am using golang 1.19.3 and builder version 0.65.0
[manifest.yaml.txt](https://github.com/open-telemetry/opentelemetry-collector-contrib/files/10135888/manifest.yaml.txt)

Some help or pointers in how to figure this out would be appreicated.

**Comment by mx-psi** [comment]
@jpkrohling I think this is probably related to promtail replaces? In any case, since it says `loki` in there I will let you have a look first since you probably have more context than me :smile:

**Comment by mattsains** [comment]
I noticed that components.go includes `github.com/open-telemetry/opentelemetry-collector-contrib/receiver/promtailreceiver` but the release manifest does not. If I remove it from my manifest, the builder succeeds again.

In general, I noticed some discrepancies between components.go and the release manifest, and I'm not sure which ones to include:

Items present in release manifest but not components.go:

* github.com/open-telemetry/opentelemetry-collector-contrib/extension/jaegerremotesampling
* github.com/open-telemetry/opentelemetry-collector-contrib/processor/redactionprocessor

Items in components.go but not release manifest:

* github.com/open-telemetry/opentelemetry-collector-contrib/extension/fluentbitextension
* github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/ecstaskobserver
* github.com/open-telemetry/opentelemetry-collector-contrib/exporter/parquetexporter
* github.com/open-telemetry/opentelemetry-collector-contrib/receiver/azureeventhubreceiver
* github.com/open-telemetry/opentelemetry-collector-contrib/receiver/chronyreceiver
* github.com/open-telemetry/opentelemetry-collector-contrib/receiver/oracledbreceiver
* github.com/open-telemetry/opentelemetry-collector-contrib/receiver/otlpjsonfilereceiver
* github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusexecreceiver
* github.com/open-telemetry/opentelemetry-collector-contrib/receiver/promtailreceiver
* github.com/open-telemetry/opentelemetry-collector-contrib/receiver/pulsarreceiver
* github.com/open-telemetry/opentelemetry-collector-contrib/receiver/purefareceiver
* github.com/open-telemetry/opentelemetry-collector-contrib/receiver/saphanareceiver
* github.com/open-telemetry/opentelemetry-collector-contrib/receiver/windowseventlogreceiver

**Comment by mattsains** [comment]
btw, including either promtailreceiver or lokiexporter results in the error I shared above

**Comment by mattsains** [comment]
I tried to update the github.com/prometheus/prometheus replace from 0.38.0 to 0.40.1, but this failed with this error:

```
# github.com/weaveworks/common/server
../../../go/pkg/mod/github.com/weaveworks/common@v0.0.0-20220916164235-da3fde973eec/server/server.go:263:51: undefined: web.TLSStruct
../../../go/pkg/mod/github.com/weaveworks/common@v0.0.0-20220916164235-da3fde973eec/server/server.go:278:51: undefined: web.TLSStruct
# github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver/internal
../receiver/prometheusreceiver/internal/appendable.go:78:9: cannot use newTransaction(ctx, o.metricAdjuster, o.sink, o.externalLabels, o.settings, o.obsrecv, o.registry) (value of type *transaction) as type storage.Appender in return statement:
        *transaction does not implement storage.Appender (missing AppendHistogram method)
```

**Comment by jpkrohling** [comment]
@mar4uk, are you able to take a look at this?

**Comment by mattsains** [comment]
Unassigning myself from this issue because it looks like @bogdandrutu has taken this over
