### ISSUE TITLE
Longer traces does not get sampled using tailsamplingprocessor

### ISSUE THREAD

**Issue by davidgargti20** [open-telemetry/opentelemetry-collector-contrib#11888]
While using tailsamplingprocessor longer traces get sampled this may be due to decision_wait . Does traces have something that indicate that trace has ended we can use that instead of decision wait and persist traces unless trace is ended.

**Comment by pmm-sumo** [comment]
Trace is constituted out of collection of spans which have parent-child relationship. There is currently no mechanism to tell that span has no children other than simply not observing those. One of the purposes of `decision_wait` is to collect enough "evidence" before making a decision. Also, currently there is no mechanism in tailsamplingprocessor to make decision earlier on some condition (however it would be possible to develop one)

**Comment by jpkrohling** [comment]
You said it all, @pmm-sumo. At most, we need to document this, as I just answered the same elsewhere, but there's nothing we can do in this case other than log a metric (which I think we are already doing).

**Comment by CatalinAdlerDF** [comment]
Do spans also miss having a `end` marker?

If so, how could this be achieved?
In practice we do know and control the boundaries of traces that we care about; can be inbound requests on the main load balancers, or who knows; to each its own.
Do you guys see a way to simulate the end marker, maybe observe something from a span event, or a log entry, to trigger the rules for the sampler?

**Comment by jpkrohling** [comment]
There's no such thing as an "end" marker: service A might call parallel calls to service B and service C. So, neither spans from service B nor service C can contain this marker. There have been a few experiments and research around mapping traces (and their spans) as workflows defined in an external location. In that case, you could have a custom processor that compares the trace structure with the expected workflow. I'm not aware of a usable processor for this though.

**Comment by CatalinAdlerDF** [comment]
Must say it is weird.
If we consider a web app; the span boundaries are clear cut: the http request itself defines them.
In your example, i'd expect to be able to express that span_A start and end deterministically, and it has 2 child spans, span_B, span_C, that start and end deterministically respectively.

I think the nuance is `deterministic` and the benefit of a explicit marker is the flows it can enable downstream.

**Comment by pmm-sumo** [comment]
@CatalinAdlerDF there are few more things

> In your example, i'd expect to be able to express that span_A start and end deterministically, and it has 2 child spans, span_B, span_C, that start and end deterministically respectively.

Even if you could use some sort of marker you have no guarantees on when all the spans will arrive to the collector (due to buffering and such). In effect, there would need to be a very strong assumption that a very specific number of spans is always anticipated to consider trace finished. I believe it is really a fairly narrow case that gives a little benefit for a lot of extra work

Additionally, there are additional use-cases which make the problem more complex. E.g. asynchronous systems

**Comment by CatalinAdlerDF** [comment]
I understand your perspective @jpkrohling but it still feels like the simple use case should be allowed, wo restoring to building custom processors: I have a web server, nothing more, i wanna take action when a trace ends.

To paint the complete picture, the business use case i and my whole org would like to have is: "log a trace if it has a failure"; this is mostly to control cost, bc most of the logs & traces are not useful unless there's smth to use them for, which for this example is diagnostics. A `trace` in this example is an operation that might span few services, though often enough it does not.

What I will be doing now is use a big time buffer to be sure that all the logs & traces are captured (hopefully), then apply the tail-sampling rules. But in my tests this has led to tens of GB of memory consumption since the collector is storing everything in memory; didn't find a way to use disk for its storage.

**Comment by jpkrohling** [comment]
> i wanna take action when a trace ends

How would you declare when a trace ends?

**Comment by jpkrohling** [comment]
In case 2, what if there was a networking problem that caused you to miss the span A? For 3, this is not the case for all traces: there are async traces, where specific spans finish after the root span has been completed.

**Comment by jpkrohling** [comment]
I like the idea of having two timeouts: one optimistic, which will evaluate traces unless they look incomplete, and another one which will evaluate the rules no matter what.

**Comment by k-meister** [comment]
@jpkrohling, Hi!
Any chance this is considered for a roadmap?
