### ISSUE TITLE
Define which type of changes require the addition of a changelog entry

### ISSUE THREAD

**Issue by joaopgrassi** [open-telemetry/opentelemetry-collector-contrib#12087]
**Is your feature request related to a problem? Please describe.**

When sending a contribution, it's not clear which type of change requires the addition of a changelog entry. In `CONTRIBUTING` there is no mention of when/when not one is required, just that one is needed.

**Describe the solution you'd like**
Maybe in `CONTRIBUTING` we can give some guidance on when a changelog entry is necessary. For example, [for small, editorial changes](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12075) it's not. This would make things easier for new contributors :).

**Comment by djaglowski** [comment]
I think the very high-level rule of thumb should be that a changelog entry is required when a change is "user-facing".

That said, we arguably have at least four groups who we might consider "users" of this repository:
1. Those who are consuming the telemetry emitted (directly or transitively) from the collector.
2. Those who are deploying or otherwise managing the collector executable.
3. Those who are depending on APIs exported from collector packages.
4. Those contributing directly to the collector codebase.

I think the changelog is primarily directed at the first three groups, but that it's reasonable to occasionally include important changes relevant only to those of us in the forth group as well.

---

With the above in mind, here are some examples of what I think should or shouldn't require a changelog entry:

Requires an entry:
- Changes to the configuration of the collector.
- Changes to the telemetry emitted _by_ the collector. (ie. where the collector originates the telemetry)
- Changes to the way the collector processes telemetry. (ie. does not matter where it was originated)
- Meaningful changes to the performance of the collector.
- Changes to the prerequisites or assumptions for running a collector.
- Changes to an API exported by a collector package.

Judgement call:
- Changes to developer tooling in the repo.
- Major changes to tests or test frameworks.
- Major changes to documentation.

Does not warrant an entry:
- Typical documentation updates.
- Refactorings with no meaningful change in functionality.
- Most changes to tests.
- Chores. eg:
  - Enable X linter on all components.
  - Fix CI process.

**Comment by jpkrohling** [comment]
Sounds quite right to me. Should this be added to the contribution guidelines?

**Comment by djaglowski** [comment]
Sure, I'll make a PR.
