### ISSUE TITLE
Unable to consume modules via external distributions

### ISSUE THREAD

**Issue by mxiamxia** [open-telemetry/opentelemetry-collector-contrib#1217]
**Is your feature request related to a problem? Please describe.**
I cannot only import `awsxrayexporter` module alone in my custom Otel-Collector go.mod without importing the full OTel-Collector-Contrib module. Otherwise, it shows errors  `github.com/open-telemetry/opentelemetry-collector-contrib/internal/awsxray@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
`

**Describe the solution you'd like**

Update the following in `awsxrayexporter/go.mod`
```
require (
github.com/open-telemetry/opentelemetry-collector-contrib/internal/awsxray v0.0.0-00010101000000-000000000000
...)
replace github.com/open-telemetry/opentelemetry-collector-contrib/internal/awsxray => ./../../internal/awsxray
```
==>
```
require (
	github.com/open-telemetry/opentelemetry-collector-contrib/internal/awsxray v0.11.0
...
)
```
**Describe alternatives you've considered**

**Additional context**

**Comment by anuraaga** [comment]
Left some details in my comment here

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1219#issuecomment-705303444

It would be nice if we can solve this issue in our go.mod files to make it easier to depend on the components in redistributions.

**Comment by jpkrohling** [comment]
I think this might actually be a build problem: the resourcedetectionprocessor also has a similar setup, and fails for the same reason. The release process should be bumping all dependencies to the contrib modules to the version being released.

For instance, here: 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/85ad20caefb81ba28f0db35b229e55d44e203c4e/processor/resourcedetectionprocessor/go.mod#L9

It should be using v0.12.0 instead.

**Comment by jpkrohling** [comment]
The `k8sprocessor` has the same problem.

**Comment by andrewhsu** [comment]
from the triage mtg, was able to prioritize, but ran out of time today to apply a `spec` label, so feel free to apply the appropriate when suitable (if this applies to a specific spec label)

**Comment by jpkrohling** [comment]
This issue isn't tied to a specific spec (metrics/logs/traces), it's part of the project's setup. From the triage meeting, I understand that we do have a goal of making each component individually consumable. Right now, there are a few modules (like the mentioned here) that depend on other modules in the same repository. When tagging this repository, those dependencies aren't changed, causing consumers of those modules to fail with the message from this issue here.

We should either:

1. instruct component builders to not depend on other modules
1. change the release script to mass-update inter-dependencies to the version that is being released

To be clear: there is a workaround for this problem, but we need a proper solution in the mid term (after GA).

**Comment by sirianni** [comment]
> there is a workaround for this problem

Is the workaround using a `replace` directive in the consuming project's `go.mod`? For example:
```
replace github.com/open-telemetry/opentelemetry-collector-contrib/internal/common v0.0.0-00010101000000-000000000000 => github.com/open-telemetry/opentelemetry-collector-contrib/internal/common v0.20.0
```

**Comment by felix** [comment]
> Is the workaround using a `replace` directive in the consuming project's `go.mod`?

Correct, I require the following:
```
replace (
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/splunkhecexporter v0.0.0-00010101000000-000000000000 => github.com/open-telemetry/opentelemetry-collector-contrib/receiver/splunkhecreceiver v0.24.0
        github.com/open-telemetry/opentelemetry-collector-contrib/internal/splunk v0.0.0-00010101000000-000000000000 => github.com/open-telemetry/opentelemetry-collector-contrib/receiver/splunkhecreceiver v0.24.0
)
```

**Comment by ttomsu** [comment]
Just hit this trying to use the `filelogreceiver` with v0.28.0.

**Comment by colin-sitehost** [comment]
it is deeply troubling that these packages are broken and have stayed broken for most of their lifetimes. if these packages are not intended to be imported, they should be hidden behind an `/internal/`, otherwise they should go-get and go-build.

I am interested in resolving this, and happy to help. I see two paths forward:
- change your workflow to stagger changes
  - this is what [google does](https://github.com/googleapis/google-cloud-go)
  - you would need to:
    - `/internal/` module changes are merged
    - `/internal/` modules are tagged
    - exported modules merge `/internal/`tagged changes
    - exported modules are tagged
- have a shadow repo/branch that gets fixed up during release
  - this is what [kubernetes does](https://github.com/kubernetes/kubernetes)
  - everything looks like it does today
  - shadow repo is not consumed by customer
  - release does the "stagger changes":
    - tag and push `path/to/internal/pkg/vX.Y.Z` [recte leaf modules in the dependency tree]
    - replace `v0.0.0` with `vX.Y.Z` on anything that depends on `path/to/internal/pkg`
    - optionally remove `replace`
    - tag `path/to/pkg/vX.Y.Z`
    - recurse until root module is tagged with `vX.Y.Z`

if we are listing all your options, including the bad or unacceptable ones, you could also:
- commit to only supporting `./cmd/otelcontribcol` and move everything else behind `/internal/`
- migrate to a single module
- publish modules without `go.sum` that point yet to be released tags

**Comment by jpkrohling** [comment]
We are working on potentially reorganizing the repositories we have today as part of https://github.com/open-telemetry/opentelemetry-collector/issues/3474, and I think we should address it there.

**Comment by colin-sitehost** [comment]
awesome; out of curiosity what timeline is that work slated for, and what of the listed options seem to fit this project best?

**Comment by jpkrohling** [comment]
That discussion is happening right now and should be completed by GA, which is happening very soon. I'm not quite sure which of the solutions would work best, to be honest.

**Comment by colin-sitehost** [comment]
sounds good, I will use the replace trick from [above](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1217#issuecomment-780617732), until this gets resolved shortly; let me know if there is anything else I can do to assist.

> though, you can simplify the `replace` from above it to:
> ```go.mod
> replace github.com/open-telemetry/opentelemetry-collector-contrib/internal/aws/awsutil => github.com/open-telemetry/opentelemetry-collector-contrib/internal/aws/awsutil v0.29.0
> ```

**Comment by mx-psi** [comment]
I think this has been fixed for a long time so I am closing this. If you disagree please comment so that we reopen it
