### ISSUE TITLE
[exporter/kafka] Send individual LogRecords

### ISSUE THREAD

**Issue by nanorobocop** [open-telemetry/opentelemetry-collector-contrib#12623]
**Is your feature request related to a problem? Please describe.**
Current implementation of of Kafka exporter sends complete ResourceLogs, which consists of ScopeLogs, which consists of LogRecords.
So instead of sending individual LogRecords, it sents structure of 3 nested levels.
It requires storage behind Kafka to store such complex structure.

**Describe the solution you'd like**
This proposal is to send individual LogRecords.
One LogRecord per sarama.ProducerMessage.

**Describe alternatives you've considered**

**Additional context**

**Comment by nanorobocop** [comment]
As far as I can see, other exporters also extract individual LogRecords and send it: [clickhouseexporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/clickhouseexporter/exporter.go#L66-L110), [elasticsearchexporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/elasticsearchexporter/exporter.go#L99-L121), [lokiexporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/lokiexporter/exporter.go#L174-L245).
So this seems more common.

**Comment by bogdandrutu** [comment]
An individual "log record" is incorrect to be sent, since lots of informations about that record are in the Resource and Scope.

**Comment by tigrannajaryan** [comment]
One way sending individual log records would be acceptable is if somehow the Resource and Scope information was merged into the LogRecord. Essentially have a flat record which contains all the information. That however would be a totally different encoding, different from the `otlp_proto` and `otlp_json` supported encodings.

>other exporters also extract individual LogRecords and send it
The elastic exporter for example does exactly what I described above: it flattens the Resource attributes: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c364eb954f853de33ef5bd2fd777f42cd410daec/exporter/elasticsearchexporter/model.go#L41

This is a choice vendor specific exporters are free to make. Kafka exporter can't make such a choice for OTLP encodings since that would mean loosing data.

One possible option would be to add support for other `encoding`s to kafka exporter. However, the encoding needs to be well defined and we need to have strong arguments in favour of adding such encoding to Kafka exporter.

Another alternate option is to use batch processor with send_batch_max_size = 1 to ensure every emitted Kafka record contains only one LogRecord.

**Comment by nanorobocop** [comment]
> An individual "log record" is incorrect to be sent, since lots of informations about that record are in the Resource and Scope.

Resource and Scope attributes could be merged into LogRecord attributes (in attribute processor, for example).
Individual LogRecords are usually what is expected by backend storage.

**Comment by nanorobocop** [comment]
> One way sending individual log records would be acceptable is if somehow the Resource and Scope information was merged into the LogRecord. Essentially have a flat record which contains all the information. That however would be a totally different encoding, different from the otlp_proto and otlp_json supported encodings.

Right, that is what I'm proposing - to have different encodings: `logRecordJSON` [encoding](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12657/files#diff-dd624142e6681519789b3a3e47af1638c82ba09e6aadd3949ad743535cae4c4dR83) and `logRecordAttributesJSON` [encoding](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12658/files#diff-dd624142e6681519789b3a3e47af1638c82ba09e6aadd3949ad743535cae4c4dR85)

**Comment by nanorobocop** [comment]
> Another alternate option is to use batch processor with send_batch_max_size = 1 to ensure every emitted Kafka record contains only one LogRecord.

That could be an option, but I think problem is nested structure with arrays []ResourceLog:[]ScopeLog:[]LogRecords, which is unnecessary in this case.
Backed would need to go 3 levels deep to get LogRecord's Timestamp and Body.

As noticed above, many exporters implement sending individual LogRecords and have [such 3 for loops pattern](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c364eb954f853de33ef5bd2fd777f42cd410daec/exporter/elasticsearchexporter/exporter.go#L102-L113).
This seems common and deserves it's own flattened encoding maybe?
