### ISSUE TITLE
[exporter/splunkhecexporter] "host.name" attribute in metric attributes not taken into account when computing HECEvent host

### ISSUE THREAD

**Issue by overmeulen** [open-telemetry/opentelemetry-collector-contrib#12747]
**Describe the bug**
I have a metric with a "host.name" attribute in the resource attributes.
I have another metric with a "host.name" attribute in the metric attributes, not the resource ones.
In Splunk I end up with my hostname being in the tag "host" for the first metric.
While for the second one it is in "host.name"

**What did you expect to see?**
I expect to always get my hostname in the tag "host" which seems to be the standard in Splunk

**What version did you use?**
v0.56.0

**Additional context**
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.54.0/exporter/splunkhecexporter/metricdata_to_splunk.go#L73

For logs this is already handled:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.54.0/exporter/splunkhecexporter/logdata_to_splunk.go#L77

**Comment by atoulme** [comment]
@overmeulen thank you for the report. I have opened this PR to address the bug: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12762

**Comment by dmitryax** [comment]
`host.name` is [a resource attribute](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/host.md#host) not a metric attribute. It's expected that they are not translated.

@overmeulen how come that you've got `host.name` as a part of a metric? What receivers do you use? If there are scraping receivers setting `host.name` as a metric attribute they should be fixed instead.

**Comment by overmeulen** [comment]
@dmitryax we have an in-house python process that generates metrics for a bunch of services. That's why we have the host.name as a metric attribute and not a resource one. I know each service is supposed to emit its own metrics but this is a huge legacy application and instrumenting all the services would be way too costly at the moment.
Note that you already override resource attributes by metric attributes (even the host.name) for the logs.

**Comment by dmitryax** [comment]
@dmitryax we have an in-house python process that generates metrics for a bunch of services. That's why we have the host.name as a metric attribute and not a resource one. I know each service is supposed to emit its own metrics but this is a huge legacy application and instrumenting all the services would be way too costly at the moment.

Can you utilize [groupbyattr](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/groupbyattrsprocessor) processor to move the metric attribute to resource. It'll make your data OTel spec compliant. Potentially you can run into this problem with any other otel component not only splunkhec exporter 

> Note that you already override resource attributes by metric attributes (even the host.name) for the logs.

I believe we will need to remove that.

**Comment by atoulme** [comment]
I have filed #13997 to follow up on this last comment, @dmitryax 

I believe this issue should be closed as "Won't Fix" at this time. @overmeulen please let me know if we can help any further.

**Comment by overmeulen** [comment]
Thanks @atoulme I went with groupbyattr processor as proposed by @dmitryax
