### ISSUE TITLE
Dependencies on github.com/outcaste-io/ristretto v0.2.0 are failing

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#12934]
Apparently, we have a dependency on a specific tag for the module "github.com/outcaste-io/ristretto", but that version does not exist. This has been failing for a few days for me, but it didn't fail on CI. When releasing contrib, it did fail again.

**Comment by jpkrohling** [comment]
Related to: https://github.com/DataDog/datadog-agent/pull/12992

**Comment by TylerHelmuth** [comment]
@jpkrohling is this a release blocker?

**Comment by jpkrohling** [comment]
Not really, I'm preparing the release with a change to the go.mod containing a "replace" directive.

**Comment by mx-psi** [comment]
DataDog/datadog-agent/pull/12992 got merged, but I can't upgrade the modules used here yet because of other issues.

There is a workaround for most users, which is to run:

```
go env -w GOPROXY="https://proxy.golang.org,direct"
```

to enforce usage of the official Go proxy. This is not available in certain regions (e.g. China) or when having certain network restrictions, so I recognize that this remains an issue even with the workaround and I am working so that we can remove this dependency.
