### ISSUE TITLE
Add custom time format configuration option

### ISSUE THREAD

**Issue by nanorobocop** [open-telemetry/opentelemetry-collector-contrib#12974]
**Is your feature request related to a problem? Please describe.**
Opentelemetry stores time in [timestamps with nanoseconds](https://github.com/open-telemetry/opentelemetry-collector/blob/main/pdata/internal/data/protogen/logs/v1/logs.pb.go#L351).
But different storages or later processing may expect time in some different format.
This is request to add custom time format to telemetry data.
Custom time field could be just another attribute.

**Describe the solution you'd like**
There're different places where adding attribute in desired time format could be added:
* [attribute processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor) (but should be extended to accept Timestamp field)
* [transform processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor) (but it works with TQL functions only, so not sure)
* together with [stanza time_parser](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/time_parser.md)

Custom time format is most useful for logs, since variety of log formats, so stanza time_parser looks more suitable for me.
But I'd like to listen if this could be interesting to somebody else in some different place.

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by nanorobocop** [comment]
Added implementation of this idea - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12977

**Comment by djaglowski** [comment]
> This is request to add custom time format to telemetry data.

If I'm understanding correctly, you want a mechanism that will format a timestamp according to a custom format and write the resulting string value to a specified field.

I think this functionality would need to be implemented in the transformprocessor, and that it would need to be generic enough to apply to any pdata.Timestamp field. (Logs, metrics, and traces all have more than one timestamp field in their data models.)

I don't think it would be appropriate to implement this within `pkg/stanza`, since this is focused on log ingestion. That is not to say that the timestamp format logic could not be reused.

My suggestion is that we need a detailed proposal for a transform processor function.

**Comment by TylerHelmuth** [comment]
I think a factory function could be created in the telemetry query language that could take a Path that returns a timestamp and converts it to a string based on a supplied format.

**Comment by nanorobocop** [comment]
Thanks for suggestions!
Let me take a closer look at TQL.
