### ISSUE TITLE
Why is elasticexporter missing from version 0.58?

### ISSUE THREAD

**Issue by wajika** [open-telemetry/opentelemetry-collector-contrib#13323]
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/release/v0.58.x/exporter/elasticexporter
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/release/v0.56.x/exporter/elasticexporter

**Comment by kago-dk** [comment]
@wajika  Based on what I have read, the exporter has been deprecated due to Elastic APM Server supporting native OTLP ingestion as part of https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13173.

The old readme
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/002c6436fa37b288c3fc8c7ade569dc14b5821f6/exporter/elasticexporter/README.md

**Comment by wajika** [comment]
> @wajika Based on what I have read, the exporter has been deprecated due to Elastic APM Server supporting native OTLP ingestion as part of #13173.
> 
> The old readme https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/002c6436fa37b288c3fc8c7ade569dc14b5821f6/exporter/elasticexporter/README.md

Thank you for your answer, I understand.
