### ISSUE TITLE
I'd like to be able to export metrics to Azure Monitor or Azure Application Insights

### ISSUE THREAD

**Issue by stevehipwell** [open-telemetry/opentelemetry-collector-contrib#13552]
**Is your feature request related to a problem? Please describe.**
I need to be able to export metrics to Azure Monitor or Azure Application Insights so I don't need to install the OMS agent in my AKS cluster.

**Describe the solution you'd like**
I'd like the azuremonitorexporter to support metrics.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by minopolous** [comment]
I tried to send traces to an application insights instance using the latest collector version 0.58.0 and the azuremonitorexporter, but when I turn on debug logs I can see that the data transfer fails with http 404. (Set the instrumentation key and the endpoint url as per the connection string of the app insights instance). It appears as if this exporter and the app insights service "are not made for eachother", since the path in the endpoint doesn't exist? Azure monitoring seems to include app insights and log analytics (at least). Which of them is supposed as "the other side"?

**Comment by minopolous** [comment]
Thanks @evan-bradley for the labels. As it concerns me, a clarification to understand if I tried something which is not meant to work, would be sufficient.

**Comment by pcwiese** [comment]
Currently unsupported (doesn't mean it won't be, just no ETA yet)

**Comment by pkt1583** [comment]
+1 I am also looking for this feature

**Comment by slavomirs** [comment]
there is an open PR ( #14916 ), anyone willing/able to review?

**Comment by stevehipwell** [comment]
This issue shouldn't be stale; #14916 is open.

**Comment by YohanSciubukgian** [comment]
Is it fully supported now as #14916 is merged ?
