### ISSUE TITLE
[processor/transform] Add `drop` action support

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#13578]
`drop` action is pretty important functionality to replace filter processors. It's already being mentioned in the docs but not implemented yet.

Subtasks per data type:

- [ ] #13579
- [ ] #13580
- [ ] #13581

**Comment by TylerHelmuth** [comment]
@dmitryax for metrics, should we drop the data point, the entire metric?

**Comment by dmitryax** [comment]
I believe it would be based on what we have in the `where` clause, right? So if we filter by attribute, it's data points. But if we filter by metric name or metric type, it's entire metric. Also I believe we should drop the whole metric if all datapoint were dropped as the result of applying the action. Same rule ideally should be propagated further: e.g. if all metrics are dropped, ScopeMetrics object should be dropped etc.

**Comment by TylerHelmuth** [comment]
I like the concept, but we don't currently have a way to relate the query's condition with the telemetry's context.  Currently the ParsedQueries are used like `If condiiontion() then Function()`, with no intelligence relating the 2.  We could add a parameter to the function that indicates which level to start the drop at.  I think doing a "rolling up drop" is also possible.  

Some of these requirements might result in context-specific functions (which is totally fine).  I'll start doing some proofs of concepts today and see how things turn out.

**Comment by dmitryax** [comment]
> I like the concept, but we don't currently have a way to relate the query's condition with the telemetry's context.

If we cannot do that, we potentially can ask user to be more specific using `drop` action, e.g. `drop(metric)`, `drop(metric.data_point)`

**Comment by TylerHelmuth** [comment]
Yes I think we'll have to either pass in a parameter or have functions like `drop_metric`, `drop_span`, `drop_datapoint`

**Comment by TylerHelmuth** [comment]
@dmitryax experimenting with this today I think it'll be best to have a `drop` function for the "Item" level of each context (which for us is datapoint, span, and log) and the a separate `drop_metric` function to specifically drop metrics.  With different functions we can make assumptions that the thing being dropped is in the current context.  I also think they will have to be specific to the transform processor since they also make assumptions about the context being use.

**Comment by dmitryax** [comment]
Makes sense. Should we call it explicitly for all the items not jus `drop` for dp span and log record?

**Comment by TylerHelmuth** [comment]
> Makes sense. Should we call it explicitly for all the items not just `drop` for datapoint, span and log record?

Yes I think we should

**Comment by TylerHelmuth** [comment]
@dmitryax testing showed that removing items from the list while iterating through the list does have side-effects.  For example, if we drop the first datapoint in a DataPointSlice, the items all "shift", but the index doesn't, resulting in the item that was directly next to the dropped item being missed.

I don't have a clever solution for this yet.  We might have to leak responsibility into the transform processor itself unless you've got any ideas.

**Comment by dmitryax** [comment]
> but the index doesn't

What do you need index for? can you point me to the code part please?

**Comment by TylerHelmuth** [comment]
@dmitryax here is the code I'm referring to for metrics (although traces and logs work similarly)

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/88efd62d1e486484c6aac93c539be8e0068f6bca/processor/transformprocessor/internal/metrics/processor.go#L96-L99

If any of the functions called for a data point drop the data point, the remaining functions called would be meaningless, but also `dps.At(i)` will "skip" an element.  If dps has 3 data points, `[dp0, dp1, dp2]`, if we drop the datapoint at position 0 the Slice is changed to look like `[dp1, dp2]` (as it should).  But the loop iterating over all the data points doesn't have insight into the fact that the list just changed, so when it tries to move on to the next item at position 1, we'll have effectively skipped `dp1`.

This is all happening because the processor is written to perform each function consecutively on each data point without any thought to what the function does.

**Comment by TylerHelmuth** [comment]
This solution could be solved by using RemoveIf loops like you did in the metricstransformprocessor and then checking the return value of the function and responding accordingly.  That leaks responsibility of dropping the data to the processor itself instead of the TQL function but would ensure that when a function is dropped the remaining functions are not called and the remaining datapoints/spans/logs are not affected.

**Comment by dmitryax** [comment]
> That leaks responsibility of dropping the data to the processor itself instead of the TQL function but would ensure that when a function is dropped the remaining functions are not called and the remaining datapoints/spans/logs are not affected.

Removing of an item should be responsibility of a container, not element itself. Looks like indexes are only used to get actual element, so I don't think you need to use them at all. All loops probably can be just replaced with `RemoveIf`

**Comment by TylerHelmuth** [comment]
I was able to get drop working using RemoveIf and a lot of custom logic in the transform processor.  Not sure how I feel about the implementation yet, gonna sleep on it.

**Comment by dmitryax** [comment]
Btw have we made a decision that `transform` processor will be a replacement for filter processors or it's supposed to _translate_ only but not remove?

**Comment by TylerHelmuth** [comment]
Based on the proof of concept today I can see a world where the filter processor sticks around and takes advantage of TQL Conditions. Kinda like mentioned here: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13545

**Comment by TylerHelmuth** [comment]
Although I do like the concept of being able to drop data within the transform processor. Could be situations where data is manipulated and then dropped in the middle based on some condition and then manipulation continues.

**Comment by TylerHelmuth** [comment]
@dmitryax draft PR for drop function/remove if implementation: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13632

**Comment by dmitryax** [comment]
As discussed during the SIG meeting, we postpone adding this functionality until we introduce multi context functionality and decide if `drop` actions should be part of transform or filter processor

**Comment by TylerHelmuth** [comment]
I am actively working on this issue again.
