### ISSUE TITLE
Feedback to improve tql package

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector-contrib#13690]
- [x] ExprFunc, maybe Gettter.Get, Setter.Set should all return errors I believe. I am certain for ExprFunc and Setter (for invalid type) that we should do it, not 100% for Get, but it is not bad to do.
- [x] Pass `ctx context.Contex` to all these funcs? Maybe part of the TransformContext?
- [x] Look into transform the `TransformContext` interface into a struct to avoid unnecessary allocations. I think right now we have an allocation for each Span/LogRecord/DataPoint.
- [x] `tql.Literal` can be private based on the current usages. Look into all the types and avoid exposing public any unnecessary type.
- [ ] Better explain the types, none of the public types have public comments.
- [x] I don't understand why do we need an Enum type and EnumParser. Can we have the GetSetter for enum deal with conversion to/from strings if needed and avoid exposing this concept?
- [x] Hide internal implementation of the `Query`. Just make it a struct with `func (q *Query) Evaluate(ctx TransformContext) error`. This will allow us to move all types form parser.go as private (if possible) or in a internal package.

**Comment by TylerHelmuth** [comment]
>  I don't understand why do we need an Enum type and EnumParser. Can we have the GetSetter for enum deal with conversion to/from strings if needed and avoid exposing this concept?

See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10349 for some Enums decisions.  The current implementation allows the grammar to convert EnumSymbols to int64 during startup instead of during the hot path.  Not saying the current implementation is the only way to achieve that, but I think it important that we handle Enums during parsing instead of during runtime.

**Comment by TylerHelmuth** [comment]
>  Hide internal implementation of the Query. Just make it a struct with func (q *Query) Evaluate(ctx TransformContext) error. This will allow us to move all types form parser.go as private (if possible) or in a internal package.

I plan to do something like this for https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13545. Waiting on https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13544 before moving forward with that refactor.

**Comment by TylerHelmuth** [comment]
>  Pass ctx context.Contex to all these funcs? Maybe part of the TransformContext?

We don't have a use case for this today but I'm curious if you've got one in mind.

**Comment by bogdandrutu** [comment]
> We don't have a use case for this today but I'm curious if you've got one in mind.

Things can be retrieved from the context (maybe?)?

**Comment by TylerHelmuth** [comment]
> Look into transform the TransformContext interface into a struct to avoid unnecessary allocations.

We could do this if we stopped having a TransformContext per signal and had one struct with all the functions (`GetItem`, `GetResource`, `GetInstrumentationScope`, `GetMetric`, `GetMetrics`) to access all the data in the context.  But we would be severely reducing the usability of the package anywhere outside the collector.  So much so that if we got rid of the TransformContext interface we might want to move the package from pkg into internal.
