### ISSUE TITLE
Improvements to contrib issue backlog

### ISSUE THREAD

**Issue by ericmustin** [open-telemetry/opentelemetry-collector-contrib#13936]
At the [September 7 Collector SIG mtg](https://docs.google.com/document/d/1r2JC5MB7GupCE7N32EwGEXs9V_YIsPgoFiLP4VWVMkE/edit#), @evan-bradley requested input on how to improve the growing contrib issue backlog (753 open issues at the moment).

There was some discussion about how to improve handling issues that are vendor-specific and possibly more appropriate for a vendor support ticketing system. Suggestions included linking to support-workflows of those vendors directly, and a team/organization level email or github handle that a triager could include in an immediate response, rather than just mentioning the github handles of the component's codeowners. In general finding a way to nudge those subset of issues to the more appropriate (_and more responsive, more secure, etc_) support workflows, means being able to then close some of those issues, and improve the backlog.

just opening this issue so that @evan-bradley has a place to collect feedback and improvement ideas.

cc @open-telemetry/collector-contrib-maintainer @open-telemetry/collector-contrib-approvers @open-telemetry/collector-contrib-triagers

**Comment by evan-bradley** [comment]
I think this would make a lot of sense. Even starting with a link to a support resource (email address, link, forum, etc.) in the README.md file for vendor-specific components could go a long way to providing users with a reliable path to resolving their issue. An automation or note in the issue templates (or both) that makes the user aware of this point of contact when opening an issue would likely be helpful to make sure the link is visible.

I think the general approach described in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12731 would also significantly help with managing the issue backlog.

**Comment by jpkrohling** [comment]
I'm sorry I'm missing something obvious, but what problem are we handling here? Is it only about the number of issues we have? If people think this repository is the best for their issue, isn't that an indication that other users would think the same?

I would rather have a bunch of open items here that can be bumped from time to time by users facing the same problem than send people to other systems and give up because they can't find out how to open an issue there.

To me, having proper labels and perhaps a "label owner" would provide a better user experience.

**Comment by evan-bradley** [comment]
The overall goal of this issue is to collect ideas on improving the organization and turnaround time of issues in the backlog. Ideally this would also reduce the number of open issues as a side effect.

The intent behind the suggestion made by @ericmustin is to reduce the resolution time on issues with vendor-specific components. In cases where the code owners are not responsive or are not experts on the vendor's backend, having a stable and dedicated resource provided by the vendor to handle problems a user may encounter when using the component may allow the user to get help more quickly. I think this would be used in tandem with ensuring that issues are properly tagged so the code owners are notified.

**Comment by jpkrohling** [comment]
Can we start small, perhaps with just labels with vendor names on them? Like `vendor:lightstep` or `vendor:grafana`? I've seen one such issue today where this could have been applied already. If the vendor decides that it's better to create a ticket on their side, they can propose that as part of the issue and close it.

**Comment by djaglowski** [comment]
+1 to starting small. I'm all for increasing clarity and organization of the backlog, but we should first clearly articulate the problem(s) we need to solve. Then we should look for solutions within the repo's current management framework (primarily GitHub).

On the issue of vendor-specific components - do we believe that these are not being sufficiently maintained by vendors _because of a problem we can and should solve_? If so, can we start by articulating what it is? 

In my opinion, we should not oblige ourselves to drive vendor-specific issues to conclusion. What we _should_ do, is consider whether there are sufficient means for vendors to maintain their components responsively. I would argue that the systems we have in place are largely effective in this regard. Specifically, we require vendors to provide one or more code owners to maintain their components. These owners are already pinged when issues relating to the component arise. Whether this is enough to effectively maintain the component is largely up to the vendor. Vendors can also include support information in their readme's, if they choose. Is there really a gap here that we need to fill?

**Comment by TylerHelmuth** [comment]
We can also try to lean on our Unmaintained and Deprecated statuses? If issues are getting worked, we're supposed to be updating components accordingly. 

If the vendor isn't responding to pings and we mark their component unmaintained, that feels like the "next step" of escalation.

**Comment by ericmustin** [comment]
@djaglowski Not a hill i'm interested in dying on but i do genuinely feel there are gaps for effectively handling open issues that are vendor specific, and over time these gaps have led to many open issues that probably ought to be closed, which would help reduce the 756 issue backlog. There are two areas where I see this.

- One, user issues _being triaged_ in an open issue that would be better served as support tickets, and encouraging them to stay as open issues is problematic. Example: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14009#issuecomment-1242111327 . We're asking the user to send over potential PII in a public issue, which is a huge red flag imo.
- Two, vendor specific questions _not being triaged_ in open issues that would get more appropriate eyes on it if it were in a support ticketing system. Example: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13377 . Is this a bug? User error? A feature request? Is there a workaround? Who knows, because it's been unacknowledged in the month since it's been opened.

That being said, i'm not a maintainer of anything in this project so I defer to y'all on what is best. If folks feel that the current issue assignment and tagging features are sufficient for handling these, then that's fine with me, and folks can just lean into those features a bit more, as @TylerHelmuth suggests. Perhaps all that's needed in that case is a time commitment by someone to go through the backlog of issues and try to close those which are no longer relevant, and ping the vendor component maintainers on those that do still seem relevant.

**Comment by djaglowski** [comment]
@ericmustin I fully agree with the general notion of improving our backlog. I mostly just want us to be specific about what we are trying to fix, so I appreciate that you've articulated some details.

Again, I'm of the mind that we need to provide vendors with _sufficient means to maintain their components responsively_, so I'm looking at these examples from that point of view. To me, I don't see a gap that warrants a systemic process change for vendor-specific components.

> user issues being triaged in an open issue that would be better served as support tickets

Using our current process, a maintainer/approver/triager adds a component-specific label to the issue. The code owners are pinged automatically and decide how to handle the ticket. If it's easy / safe enough, they may choose to handle it in public. Otherwise, they can ask the user to open a support ticket and point them in the right direction. I think this is not an ideal workflow but it is sufficient because the code owner is notified and can handle the issue however they choose.

> vendor specific questions not being triaged in open issues that would get more appropriate eyes on it if it were in a support ticketing system

Similarly, a component-specific label is added to the issue and the code owners are pinged and handle it accordingly. If the label is not being added, that's on the maintainers. However, if the code owner is unresponsive, I don't think that is _necessarily_ a gap in our process. It'd be a problem if the code owners were not notified, or some other systemic issue prevented them from addressing the issue.

In the case of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13377, this is not a vendor specific issue so an external ticketing system would not have helped here. Vendor specific or not though, I (the code owner) was pinged and had the opportunity to respond but obviously failed to do so. That's on me. I was giving it some thought and forgot to circle back. If anything, additional pings would have been helpful. (See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12731)

**Comment by TylerHelmuth** [comment]
I will also add that the triaging (and then working) issues for components related to a vendor product when the vendor isn't the owner of the component is one of the major reasons these components struggle to get sponsors.  Vendor specific components without a vendor sponsor struggle because users don't realize the vendor isn't supporting the component like the name might imply.  In these situations vendor support queue probably also wouldn't help because the vendor isn't supporting the component.

**Comment by evan-bradley** [comment]
Thanks everyone for your input. Based on the discussion for far, I would like to first tackle #12731, and see the results of that effort to guide where we go next. I'll leave this issue open for about another week to see if there are any more ideas.
