### ISSUE TITLE
Create a lightweight web app to create a collector config

### ISSUE THREAD

**Issue by pmcollins** [open-telemetry/opentelemetry-collector-contrib#13991]
**Is your feature request related to a problem? Please describe.**
Users may find creating a YAML config for the collector to be challenging and error prone. Once they create a config, it can also be challenging to visualize data flowing through the collector and troubleshoot problems.

**Describe the solution you'd like**
A lightweight web app that provides guide rails for creating a config, being to the extent possible, point and click. It should also let users see data flowing through the collector so they can make changes to the config and diagnose problems.

**Additional context**
I have created a proof of concept that solves the above problem and would like feedback about it -- including whether it should be included in the contrib repo at all, or whether it should live in its own repo.

**Comment by jpkrohling** [comment]
This might be related to: https://github.com/open-telemetry/opentelemetry-collector/pull/5943

I would prefer to have a CLI tool first, to be honest.

**Comment by damemi** [comment]
+1 for a CLI tool, but it could probably share a lot of code with the web app. Visualizations for pipelines could be really useful.

Something really fancy like a package manager for building collectors/configs would be a cool extension of this

**Comment by frzifus** [comment]
Would be greate to have something like that. CLI or WebApp sounds both great. 

cc @esnible

**Comment by codeboten** [comment]
from sept 28 SIG call, cc @jpkrohling

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan suggested we needed at least 2 owners for the repository. 

Yes, to ensure long-term maintenance and simply to make sure someone can approve the PRs. You can't review, approve and merge your own PRs :-)

**Comment by cartermp** [comment]
Love this effort. Another thought here is that this (or something like this) could live on the website as well, and/or be linked to from the collector docs [that get significant traffic](https://play.honeycomb.io/opentelemetry-web/datasets/opentelemetry.io/result/sHiiZF79G6s?useStackedGraphs). Although we can link to things in the interim, it's far less friction for end-users to have any web-based tool hosted on the site in the long-term. But in the interest of incremental progress, I wholly endorse:

* Getting a tool that creates the config easily out into the world as quickly as possible
* Reworking relevant parts of the docs so that this tool is linked to as a recommended option
* Figuring out the right technical path for the website to be able to host such a tool, especially after it's been vetted by several end-users

**Comment by svrnm** [comment]
I wanted to say what @cartermp said, but he used better words, so 💯 

> I would prefer to have a CLI tool first, to be honest.

Can we still make sure that this is also going to happen? @neelayu invested lots of effort into that, and the CLI is still the way to go for many people :-)

**Comment by jpkrohling** [comment]
> from sept 28 SIG call, cc @jpkrohling

I circulated this internally and will ping @pmcollins in case someone is interested in helping with the frontend parts.

**Comment by pmcollins** [comment]
It was decided that we don't want this functionality in contrib at this time and that a separate repo should be created for it. For now, this repo will live in the Splunk org, but we can move it to Otel upon request.

**Comment by frzifus** [comment]
@pmcollins could you link the repo here? :)
