### ISSUE TITLE
Remove confusing term "pipeline" from stanzareceiver config

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#1438]
The configuration currently uses the term "pipeline" to describe operations that happen with the log record in the receiver. This may be confusing for the user since "pipeline" already means something else in the Collector.

I suggest we re-work slightly the config to look like this:
```yaml
stanza:
  inputs:
    - array of input operators, e.g. file_input which will become the start of the stanza pipeline
  operators:
    - array of actions, e.g. parser operator regex_parser which will continue the pipeline. 
```

This eliminates the word "pipeline" and the added benefit is that it makes impossible to do a mistake and put an input operator in the middle of the pipeline or start the pipeline with non-input operator.

For example:
```yaml
stanza:
  inputs:
    - type: file_input
      include: [ '*.log' ]
      start_at: beginning
  actions:
    - type: regex_parser
      regex: '^(?P<time>\d{4}-\d{2}-\d{2}) (?P<sev>[A-Z0-9]*)'
      timestamp:
        parse_from: time
        layout: '%Y-%m-%d'
      severity:
        parse_from: sev
```

@djaglowski what do you think?

**Comment by keitwb** [comment]
We could go even farther with this and have `inputs` + `parsers` to encourage people to not using any of the "general purpose" operators in stanza since those heavily overlap with the Collector processors.

It does seem good to avoid overloading the term _pipeline_ but another alternative could be to just call it `stanza_pipeline` even though it is repetitive with the `stanza` key above it would be very explicit.

Either way `actions` could be something better since that is not a stanza term (from  what I can tell) and it's pretty generic.

**Comment by djaglowski** [comment]
It does seems reasonable that the overloaded term "pipeline" should be renamed. Perhaps "operators", "graph", or "log_pipeline" would be acceptable.

In regards to the suggested bucketization of stanza operators though, I think there are some implications here that need to be considered more carefully. 

At a high level, OpenTelemetry's concept of a pipeline is more constrained that stanza's. Unlike OT's `N receivers => 1 processor => ... => 1 processor => M exporters` pipeline, stanza supports any directed acyclic graph of operators. I think we need to be careful that any constraints put in place around stanza's graph are not preventing otherwise easy solutions. To be clear, I agree it may make sense to constrain stanza's DAG if we're sure the configurations we're eliminating are better solved at the OT pipeline level.

It's true that in many use cases a DAG is not necessary, the most simple being `1 input => emit` or `1 input => 1 parser => emit`. However, there are many instances where a DAG is helpful. If you look at some of the stanza plugins, you can see this in action. 

A relatively straightforward one is [couchbase](https://github.com/observIQ/stanza-plugins/blob/master/plugins/couchbase.yaml) which is essentially a `7 inputs => 7 parsers => emit` solution. Yes, you could split these into 7 receiver instances, but perhaps it is beneficial to manage them together? At a minimum, I'd like to assert the the following is an elegant abstraction that should remain a possible solution:
```
stanza:
  plugin_dir: local
  pipeline:
    - type: couchbase
```
If I can go one step further, it seems it would make sense to allow the underlying DAG to be pulled up, dropped into the same receiver, and customized as necessary from there, all without necessarily requiring separation into multiple components.

Another common situation where a DAG makes sense is in cases where multiple types of logs are found within a single input. Here you typically need something like `1 input => 1 router => N parsers => emit`. This can be seen in our [mysql](https://github.com/observIQ/stanza-plugins/blob/master/plugins/mysql.yaml#L67) plugin. I think the suggested bucketization strategy would make this more complicated than explicit output from node to node.

Yet another case where a DAG is useful is when consuming application logs in kubernetes. Using couchbase as the example again, multiple log sources end up routing to `stdout` and then they must be routed appropriately from there to the correct parsers - not something I believe would be easy to split across multiple receivers, or to handle downstream in the processors, at least not in the short term.

All this is to say that there is a lot of power in what stanza can do today, and I believe that the proposed separation of operators into buckets may be inadvertently precluding functionality that we will end up wanting later. 

By not perfectly mirroring the OT pipeline model, we're certainly adding some complexity at the stanza level, but this can largely be ignored except for when it is needed. Put another way, users will typically just have a receiver managing `1 input => 1 parser => emit`, but they can enhance if necessary. On the other hand, I believe the additional capabilities are uniquely suitable for many log processing use cases, so I would suggest that any restructuring of stanza's pipeline definition should be done very carefully. (naming aside of course)

> it makes impossible to do a mistake and put an input operator in the middle of the pipeline

Whether or not this should be seen as a mistake comes down to whether or not the notions mentioned above are seen as legitimate use cases, but I think some of the examples I've provided show that there are reasons this is necessary , such as if we decide that it's ok to support multiple log inputs within a single stanza receiver (which I would very much like to do, at least in the short term).

> or start the pipeline with non-input operator

This is certainly a lot less necessary to support (although stanza can still connect it into the graph if a later operator references it). That said, this is probably one of the areas where establishing some additional rules around the structure of the resulting DAG would make sense. For example, we could enforce that any non-input operator must have an upstream operator.

> encourage people to not using any of the "general purpose" operators in stanza

Can we discuss operator inclusion/exclusion on a case by case basis? It is easily controllable whether or not each operator is made available within the receiver, so I don't think we need to make any broad decisions around this. Just for example, I think `router` is a rather general purpose operator, but has some very legitimate pre-parsing use cases.

**Comment by tigrannajaryan** [comment]
> A relatively straightforward one is [couchbase](https://github.com/observIQ/stanza-plugins/blob/master/plugins/couchbase.yaml) which is essentially a `7 inputs => 7 parsers => emit` solution. Yes, you could split these into 7 receiver instances, but perhaps it is beneficial to manage them together? At a minimum, I'd like to assert the the following is an elegant abstraction that should remain a possible solution:

@djaglowski looking at the couchbase I do not fully understand how the stanza pipeline is supposed to work. Are items listed in the pipeline connected by default sequentially, but if there is an `output` setting specified then this default connection is not made and whatever is specified in the `output` setting of the step overrides it? Does `{{.output}}` signify the very end of the pipeline? Is there a document that describes how this works? I can't find one in stanza repo.

**Comment by djaglowski** [comment]
@tigrannajaryan You've got the right idea. If an operator does not have an explicit `output` field, then it will output to the next operator. 

`{{ .output }}` is only valid in plugins. This is saying that a parameter named `output` can be expected, and that value will be inserted in place. The value of `output` is set according to the same rules. The only difference really is that this value is then passed into the plugin as a parameter.

I'm writing up some clearer documentation on this today, and will link it here once it's merged.

**Comment by tigrannajaryan** [comment]
@djaglowski I understand. I agree, the flexibility of forming a DAG may be very useful, so let's keep it for now. I suggest that for now we just do the simple renaming of "pipeline" to "operations" (or similar).

**Comment by djaglowski** [comment]
Here's some improved documentation on the stanza pipeline: https://github.com/observIQ/stanza/blob/master/docs/pipeline.md

And a bit more clarity on how plugins work: https://github.com/observIQ/stanza/blob/master/docs/plugins.md#using-plugins
