### ISSUE TITLE
receiver/kafkareceiver - Allow user to read from latest or smallest offset

### ISSUE THREAD

**Issue by MacNale** [open-telemetry/opentelemetry-collector-contrib#14976]
### Is your feature request related to a problem? Please describe.

I cant specify kafka offset to configure receiver/kafkareceiver to start reading from.

### Describe the solution you'd like

support config as follows - 

offset: smallest | latest

**Comment by ueisele** [comment]
Hello,

I also need this feature to submit metrics already published to Kafka to an additional sink. 
In principle, it would of course also be possible to create a consumer group in advance and set the offset. However, a way to configure this would make this much easier.
Since this only required a few lines of code, I implemented this and created the PR #21408.
