### ISSUE TITLE
[exporter/elastic]  Support exporting infrastructure metrics

### ISSUE THREAD

**Issue by MacNale** [open-telemetry/opentelemetry-collector-contrib#15345]
### Is your feature request related to a problem? Please describe.

It looks like ElasticSearch Exporter can export traces and logs but no metrics

<img width="371" alt="image" src="https://user-images.githubusercontent.com/14235758/196821330-60e1d0dd-798d-4f7a-ba26-4de339121292.png">

### Describe the solution you'd like

Ability to export the metrics to ElasticSearch using expoerter

### Describe alternatives you've considered

Logstash to stream metrics but it is a pain.

**Comment by jkowall** [comment]
Use a database which is good with time series. If you've tried to do this with elastic you'll know the pain.

**Comment by JaredTan95** [comment]
> 

Thx your reply, and I learned from elastic official's blog here https://www.elastic.co/blog/elasticsearch-as-a-time-series-data-store,  I don't know if it's a solution worth trying 🤔

**Comment by jkowall** [comment]
It's simply not cost-effective, performant, and reasonable to use as a metric store. We've built it and created and roll-ups and other requirements, and it still was extremely costly. That's why everyone uses Prometheus and Prometheus compatible services. You simply cannot do proper metric analytics on an Elasticsearch or OpenSearch database. The next OpenSearch will connect to and handle Prometheus interoperability to solve this problem. 

The blog you posted is 7 years old, lots has changed since then. StageMonitor which the blog quotes is a dead solution. Any product which is doing heavy metric analytics is not running on Elasticsearch or OpenSearch. It's a known fact, but you can do as you wish. :)

**Comment by JaredTan95** [comment]
> It's simply not cost-effective, performant, and reasonable to use as a metric store. We've built it and created and roll-ups and other requirements, and it still was extremely costly. That's why everyone uses Prometheus and Prometheus compatible services. You simply cannot do proper metric analytics on an Elasticsearch or OpenSearch database. The next OpenSearch will connect to and handle Prometheus interoperability to solve this problem.
> 
> The blog you posted is 7 years old, lots has changed since then. StageMonitor which the blog quotes is a dead solution. Any product which is doing heavy metric analytics is not running on Elasticsearch or OpenSearch. It's a known fact, but you can do as you wish. :)

Agree with @jkowall , elasticsearch is not the proper way to store otlp/metrics

**Comment by vincentfree** [comment]
Together with a colleague I've actually build this feature but due to what is explained in this PR by @jkowall and others we are actually in the migration to Grafana Mimir for OTLP metrics. As stated we ran into issues which are very hard to overcome and were not worth while to fix. Compared to other prometheus compatible solutions Elastic or on our case opensearch just doesn't fit the profile.

**Comment by jkowall** [comment]
@vincentfree we did the same, building rollups and other capabilities on top of Elasticsearch, and it didn't work, and we had to reverse course. It was a major mistake for us. Well, the good news is, not that it's relevant to this discussion, is that OpenSearch 2.4 (due out next week) supports Prometheus integration and PromQL. This will eventually give us a viable open-source alternative to using Grafana to analyze metrics, and it opens up a lot of use cases for PPL.

**Comment by MacNale** [comment]
https://demo.elastic.co/app/metrics/explorer?metricsExplorer=(chartOptions:(stack:!f,type:line,yAxisMode:fromZero),options:(aggregation:avg,metrics:!((aggregation:avg,color:color0,field:system.cpu.total.norm.pct),(aggregation:avg,color:color1,field:kubernetes.pod.cpu.usage.node.pct),(aggregation:avg,color:color2,field:docker.cpu.total.pct)),source:default),timerange:(from:now-1h,interval:%3E%3D10s,to:now))

I opened the request by seeing the above demo. Looks like I need to study more on why elastic is not a right choice for metric store.

**Comment by jkowall** [comment]
> https://demo.elastic.co/app/metrics/explorer?metricsExplorer=(chartOptions:(stack:!f,type:line,yAxisMode:fromZero),options:(aggregation:avg,metrics:!((aggregation:avg,color:color0,field:system.cpu.total.norm.pct),(aggregation:avg,color:color1,field:kubernetes.pod.cpu.usage.node.pct),(aggregation:avg,color:color2,field:docker.cpu.total.pct)),source:default),timerange:(from:now-1h,interval:%3E%3D10s,to:now))
> 
> I opened the request by seeing the above demo. Looks like I need to study more on why elastic is not a right choice for metric store.

If it's possible it doesn't mean it's a good idea. If you have a few metrics or a smaller infrastructure, then it would be fine. The queries and language (Lucene) is poor at dealing with time-series data. You will be limited by this fact alone. The bigger problem is that scaling ElasticSearch is costly, very costly. There is no notion of a roll up or handling data over time. 

My company tried to build a metric platform on ElasticSearch (we even built rollups and buckets), and it was roughly 150x more expensive than running M3DB which is what we use today. M3DB is still more expensive than running Cortex/Thanos (or Prometheus) but you get some other advantages. 

The biggest plus is PromQL. It is a very robust language for dealing with time series. You can analyze the data faster and in more advanced ways. Super simple example. Tell me on Lucene how you'd query data for 95th percentile of a 5 minute bucket request rate? Or even how you'd store buckets in ElasticSearch.

Easy in prometheus histogram_quantile(0.95, rate(http_request_duration_bucket[5m]) 

The Elastic products which you are referring to make many assumptions on your data and limit what kind of metrics and analysis you can do. This is necessary due to the database.
