### ISSUE TITLE
[admin] mark-issues-as-stale.sh not grabbing enough issues

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#15684]
### Describe the issue you're reporting

The new workflow to mark issues as stale worked, but I don’t think it processed enough issues since the gh command didn’t set a limit. 

I think this call https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/92ad54f707a967386b764b6fdaea5a2ba4377319/.github/workflows/scripts/mark-issues-as-stale.sh#L40 needs to include a [—limit flag](https://cli.github.com/manual/gh_issue_list). At the moment I suspect it is using the default of 30.

**Comment by evan-bradley** [comment]
My intent was to leave it at the default of 30 issues and run it once a week to gradually mark issues as stale to make sure nobody was hit with a ton of notifications at once, since there are roughly 500 issues eligible to be marked as stale. Issues still won't be closed for 4 months after being marked stale, so I'm also fine being more aggressive. We could turn up the issue limit, run frequency, or both if we'd like to process them faster.

One thing to consider is that many older issues aren't tagged with component labels, so code owners won't be notified. @dmitryax and I discussed extending the workflow to add labels through comments to include component labels, and mentioning this to issue openers in the stale message. This would put the burden on issue openers to get the stale issue processed if it is still valid, otherwise it could be closed. This flow could also potentially assist code owners manage labels on newer issues.

What do you think?

**Comment by TylerHelmuth** [comment]
I'd certainly put a vote towards faster processing, as many issues are super old.  But I'd like to hear all opinions.

I like the idea of extending the "add labels via comments" workflow to include component labels.  I think that would be useful for several situations.
