### ISSUE TITLE
mongodbreceiver integration test failing w/ latest mongodb driver update

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#16182]
### Component(s)

receiver/mongodb

### Describe the issue you're reporting

See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3422093006/jobs/5700027979

```
    integration_test.go:158: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/mongodbreceiver/integration_test.go:158
        	Error:      	Received unexpected error:
        	            	number of resources does not match expected: 4, actual: 0
        	Test:       	TestMongodbIntegration/Running_mongodb_3.0
```

**Comment by schmikei** [comment]
The mongo go driver dropped support for 2.6 in 1.11.0 

https://github.com/mongodb/mongo-go-driver/tree/v1.11.0

We should probably drop support as well going forward as it is a fairly dated release at this point. Was mostly supported during the development to support default installations of some popular OSes.

**Comment by djaglowski** [comment]
Looks like [mongo dropped support for versions < 3.6](https://github.com/mongodb/mongo-go-driver/releases). I think we'll need to do the same in order to upgrade the driver.

Looks like [anything prior to 4.2 is EOL already](https://www.mongodb.com/support-policy/lifecycles). 4.0 went EOL earlier this year, so it seems reasonable to retain support for that, but I'm thinking we should drop 3.x entirely.
