### ISSUE TITLE
[processor/transform] Add the capability to scale a metric value

### ISSUE THREAD

**Issue by gabrielgiussi** [open-telemetry/opentelemetry-collector-contrib#16214]
### Component(s)

processor/transform

### Is your feature request related to a problem? Please describe.

Currently the metricstransformer already supports [scaling a value](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor#scale-value) and a [recent PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/15691) even extended this for histograms.

Since processor/transformer will eventually replace metricstransformer could we add this feature? 

If you agree with feature request I could work on this.

### Describe the solution you'd like

Scale a value down/up, even histograms, e.g. to transform a histogram in milliseconds to seconds
```
scale(0.001) where metric.name == "envoy_vhost_vcluster_upstream_rq_time"
```

**Comment by TylerHelmuth** [comment]
A solution for this may have some overlap with https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16067

**Comment by TylerHelmuth** [comment]
@gabrielgiussi yes the transform processor should be able to handle this.  I think we can make a generic function that takes a float or int and scales it based on a factor.  Instead of `scale` setting the value itself, though, I think it would work better as a Factory Function (a function that modifies data and then returns it) would be best so that the result can be used anywhere.

Function signature could look like `Scale(getter, factor)`.  The we could do things like

- `set(value_double, Scale(value_double, 10))`
- `set(attributes["my-number"], Scale(value_double, 100))`
- `set(start_time_unix_nano, Scale(start_time_unix_nano, .0001)` <- I'm really interested in this implication.

**Comment by TylerHelmuth** [comment]
@gabrielgiussi OTTL supports arithmetic operations which should handle this use-case:

`set(value_double, value_double*0.001) where metric.name == "envoy_vhost_vcluster_upstream_rq_time"`

I do think there is a limitation with scaling histograms.

**Comment by bacherfl** [comment]
If this ticket is available, I would like to work on this @evan-bradley FYI

**Comment by bacherfl** [comment]
@TylerHelmuth @evan-bradley just a quick question for clarification - Since arithmetic operations can be used for achieving this, as suggested [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16214#issuecomment-1756621324), is the goal now to either:

- have the arithmetic operations also support handling Histograms, or to
- implement the `Scale` factory function that can handle both scalar values and histograms?

**Comment by TylerHelmuth** [comment]
@bacherfl thanks for looking at this.

I am open to opinions on whether we just need histogram support or a new function.  

I believe a new function would provide the most consistent workflow for end users, and it could also optionally allow updating the metric unit.

**Comment by evan-bradley** [comment]
I would also agree we should implement a function.

I would be in favor or either a `scale_metric` Editor that only operates on all data points within a metric, or a `Scale` Converter that works on both whole metrics and on individual data points. The Converter would probably be a little more verbose in general usage (`set(data_points, Scale(data_points, 10))`), but would allow for things like scaling a misadjusted data point if that's ever an issue.

A `Scale` converter could be good for adjusting individual integer/float values, but I think relying on arithmetic for that is okay.

**Comment by TylerHelmuth** [comment]
Operating on all the datapoints of a metric is the most similar to the metricstransformprocessor

**Comment by bacherfl** [comment]
Thanks for your replies @TylerHelmuth @evan-bradley - I implemented this as a new converter function now - feel free to check out the linked PR :)
