### ISSUE TITLE
[processor/servicegraph] Failed to find dimensions for key xxx

### ISSUE THREAD

**Issue by Frapschen** [open-telemetry/opentelemetry-collector-contrib#16262]
### Component(s)

processor/servicegraph

## Description
I get an error in my app when it sent span to a otel collector which configed a servicegraph processor

the error cause by:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9166107431795fb5a7433ffea78c9ab3ddde208c/processor/servicegraphprocessor/processor.go#L365-L384

a relate bug discuss at https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/15687#discussion_r1008880704

### Collector version

latest

## Environment
OS: cenos 7
running on container

### Log output

```shell
2022/11/11 08:01:18 rpc error: code = Unknown desc = failed to build metrics: failed to find dimensions for key istio-ingressgatewayghippo-keycloakx
2022/11/11 08:01:23 rpc error: code = Unknown desc = failed to build metrics: failed to find dimensions for key dsp-controlplane-appserverdsp-controlplane-backend
2022/11/11 08:01:28 rpc error: code = Unknown desc = failed to build metrics: failed to find dimensions for key mcamel-elasticsearch-apiserverkpanda-proxy-ingress
```

### Additional context

relate bug report

**Comment by JaredTan95** [comment]
looks like the same issue https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16024 ?

**Comment by Frapschen** [comment]
Can we fellow this https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16601 to fix this issues? @jpkrohling @mapno

**Comment by Frapschen** [comment]
I use a [UT](https://github.com/Frapschen/opentelemetry-collector-contrib/blob/servicegraph_Failed_to_find_dimensions/processor/servicegraphprocessor/processor_test.go#L334) to replay the error. Can you have time to check it?@mapno

**Comment by mapno** [comment]
Hey! Thank you for the test. It helped me figure out what's happening. The problem resides on how the processor stores series in-memory, and how it (doesn't) purge them.

There are two sets of maps: one to store [series values](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.69.0/processor/servicegraphprocessor/processor.go#L69-L75), and another to [map keys to the dimensions of the series](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.69.0/processor/servicegraphprocessor/processor.go#L77-L78). The issue comes from the function [`p.cleanCache`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e3d2bd5041ffa8ab7eb1404420d9cdb46f0e051e/processor/servicegraphprocessor/processor.go#L492-L508) that removes stale series from these maps.

There are a few solutions that could be implemented: 1) purge the first set of maps of stale series, 2) skip stale series during metrics collection, 3) stop removing stale series. I'd go for option 1.

**Comment by mapno** [comment]
Opened a PR for option 1: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17512.
