### ISSUE TITLE
[pkg/stanza/fileconsumer/fingerprint] the way to iidentify a file

### ISSUE THREAD

**Issue by maokitty** [open-telemetry/opentelemetry-collector-contrib#16266]
### Component(s)

pkg/stanza

### Is your feature request related to a problem? Please describe.

There is a possibility of different file have the same first N bytes,while the default value of N is 1kb(It's hard to findout the reason  when problem is  happend)

### Describe the solution you'd like

Add the filePath to fingerprint
Maybe the create time of file can be added too

**Comment by djaglowski** [comment]
[Here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/fileconsumer/design.md#deduplication-of-files) is the design document section pertaining to fingerprints.

You are correct that multiple files with the same first `N` bytes will not be differentiated. There are cases where `N` needs to be larger than the default, in which case you can use the `fingerprint_size` setting. 

File path and create time are intentionally ignored because of the need to handle file rotation. When files are rotated, the file path and/or name changes, and the created time may change as well. Still, we do not want to treat the rotated file as if it was a new file that we have never seen, so we must have an independent way of identifying it.
