### ISSUE TITLE
[pkg/stanza/operator/parser/json] json parse error

### ISSUE THREAD

**Issue by maokitty** [open-telemetry/opentelemetry-collector-contrib#16261]
### Component(s)

pkg/stanza

## Description
if the content contains '\n' ,the parser will report an error
## Steps to Reproduce
```
func main() {
	str :="{\"body\":\"a \n b\"}"
	p :=Parser{json:jsoniter.ConfigFastest}
	parse, e := p.parse(str)
	if e!=nil {
		fmt.Println(e)
	}else{
		fmt.Println(parse)
	}
}
type Parser struct {
	json jsoniter.API
}
func (j *Parser) parse(value interface{}) (interface{}, error) {
	var parsedValue map[string]interface{}
	switch m := value.(type) {
	case string:
		err := j.json.UnmarshalFromString(m, &parsedValue)
		if err != nil {
			return nil, err
		}
	default:
		return nil, fmt.Errorf("type %T cannot be parsed as JSON", value)
	}
	return parsedValue, nil
}
```
## Expected Result
map[body:a 
 b]

## Actual Result
ReadString: invalid control character found: 10, error found in #9 byte of ...|{"body":"a 
 b"}|..., bigger context ...|{"body":"a 
 b"}|...

### Collector version

0.61.0

## Environment
go version go1.18.4 darwin/amd64

**Comment by djaglowski** [comment]
I believe this is the correct behavior. According to the json specification, newline characters must be escaped.

You can read more about this [here](https://stackoverflow.com/a/42073). The first comment on the accepted answer states it quite well:

`... the JSON spec at [ietf.org/rfc/rfc4627.txt](http://www.ietf.org/rfc/rfc4627.txt) contains this sentence in section 2.5: "All Unicode characters may be placed within the quotation marks except for the characters that must be escaped: quotation mark, reverse solidus, and the control characters (U+0000 through U+001F)." Since a newline is a control character, it must be escaped.
`
