### ISSUE TITLE
[processor/k8sattributes] setting container.id on traces

### ISSUE THREAD

**Issue by ty-elastic** [open-telemetry/opentelemetry-collector-contrib#16431]
### Component(s)

processor/k8sattributes

### Describe the issue you're reporting

Hi, I'm using the k8sattributes processor to enrich `container.id` on OTEL traces using `k8s.pod.ip` or `k8s.pod.uid` to match the pod and `k8s.container.name` and `k8s.container.restart_count` to match the container within the pod.

I can appreciate that `k8s.container.restart_count` allows me to definitively match the container instance (if k8s restarts the container within the pod without restarting the pod). In practice, though, I wonder if this added complexity is necessary.

For example, I can't find or think of an easy way to pass in the actual `k8s.container.restart_count` as an env variable from a k8s deployment yaml (i.e., k8s can't tell me this via downward API, and I can't think of a way to easily keep track of it myself in a persistent env variable). Perhaps I'm missing something obvious here?

So barring that, if I hardcode `k8s.container.restart_count=0` as an env variable in the deployment yaml, that works unless of course k8s restarts the container.

In practice, would it be reasonable to have a mode wherein the k8sattributes processor just assumes you want to match to the current running instance of the container? You obviously can't have 2 running at the same time, and I would think the only "glare" condition here is for traces emitted by the old container right before it died but which haven't yet been processed by the collector; if the new container immediately launches while those traces are in flight, they would be stamped by the k8sattributes processor with the wrong `container.id`. That said, this seems like a rare event, and even if it did occur, it is probably ok for most use caes?

I'm suggesting that we have a mode in k8sattributes which will just assume you are talking about the latest instance of a given container in a pod if you don't explicitly set `k8s.container.restart_count`.

PR forthcoming.

thoughts?

**Comment by dmitryax** [comment]
Hi @ty-elastic.

> For example, I can't find or think of an easy way to pass in the actual k8s.container.restart_count as an env variable from a k8s deployment yaml (i.e., k8s can't tell me this via downward API, and I can't think of a way to easily keep track of it myself in a persistent env variable). Perhaps I'm missing something obvious here?

Usually, `k8s.container.restart_count` is passed for logs metadata enrichment by extracting it from the log file path. The lowest expected granularity for traces is a pod, not a container, because you cannot say which container sent a trace by looking at an IP address in the client request context.

Couple questions:
- How do you set `k8s.container.name`? Is it manually hardcoded in tracing instrumentation?
- What's the use case? Why do you need `container.id` on tracing?

**Comment by ricramalho** [comment]
Hi. My team is really needing this feature to be merged. We are making a OpenTelemetry integration with Datadog to collect logs, metrics and traces, and we would appreciate to have the container id attribute to get the best out of all the dashboards.
We have OpenTelemetry collector running as a sidecar on the pods we want to log to Datadog - we configured the shared volume mounts to get the logs, receiver and k8sprocessor to get more details regarding the pod/containers. If we add the container name and restart count as resource attributes, it works until we restart the container:

resource:
        attributes:
        - key: k8s.container.restart_count #mandatory
          value: 0
          action: insert
        - key: k8s.container.name #mandatory
          value: dummy-nginx
          action: insert
 
Once we restart the container, it stops sending the container id. If we manage to get the latest container ID (with the higher restart count), that would solve our problem.
Right now we are testing this with the restart count set to 0, however, as you know, it's not feasible to have it this way using in higher environments. Thank you.

@dmitryax  in our use case, the k8s.container.name is passed as resource variable on the receiver alongside the volume where the logs are stored. 
Regarding the need for the container id, we need it because without it, our integration with Datadog isn't fully done - we cannot see on the Datadog UI the container name, pod name and docker image used. Also, without it, some dashboards are not available.

**Comment by ty-elastic** [comment]
Hi @dmitryax , some APM solutions (agents and backends) do tag traces with `container.id`. See the Java OTEL instrumentation library (io.opentelemetry.instrumentation.resources.ContainerResource), for example. One reason this exists is to provide ID and tagging for apps running in containers outside of k8s (e.g., vanilla Docker).

Some APM backends use `container.id` to marry together data about a service which may be collected from various sources, outside of OTEL. For example, since many OTEL instrumentation libs do not yet support log capture, I may use a traditional agent to pick up and send in container logs. `container.id` would be one way of associating traces with logs, and possibly infra metrics, collected through some other agent.

I would set `k8s.container.name` from a runtime `OTEL_RESOURCE_ATTRIBUTES` env variable (which most/all OTEL instrumentation libs support).

**Comment by dmitryax** [comment]
@ty-elastic , @ricramalho  Ok, sounds good. Thanks for the detailed answers

**Comment by dmitryax** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16432
