### ISSUE TITLE
Work with the Loki team to reduce the number of replaces directives

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#16453]
One of the concerns when working on #14632 was that it would inherit the replaces directives from the Loki project into the promtail receiver, affecting both contrib and, later down the stream, on builder manifests. We (@mar4uk and myself) should work with the Loki team at Grafana Labs to try to reduce the number of replaces directives as much as possible.

**Comment by mar4uk** [comment]
This issue can be closed. All replace directives introduced by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14632 were removed
@jpkrohling could you please close this issue as fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17029, https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17577
