### ISSUE TITLE
Implement opamp extension configuration reading and validation

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#16619]

**Comment by srikanthccv** [comment]
@tigrannajaryan, since the https://github.com/open-telemetry/opentelemetry-collector/issues/6599 is completed, I think we can't use the `service.instance.id` as a replacement for `instance_uid`. So the config for opamp extension would look something like.

```
type Config struct {
    Endpoint string `mapstructure:"endpoint"`
    confighttp.HTTPClientSettings `mapstructure:",squash"`
}
```

**Comment by srikanthccv** [comment]
I wonder if there was a reason behind passing settings at the time of `Start` instead of creating a new client with `ClientSettings`. Functionally I don't see much of a difference; having it already set up with given settings before the Start call makes it easier to customize `sender`/`dailer`. Either way, I can pick some of these issues and start working, but I guess there should be an extension skeleton first.

**Comment by evan-bradley** [comment]
I think the basic requirements of this issue have been met, providing custom transport clients to the OpAMP client library will need to be tackled separately in opamp-go.
