### ISSUE TITLE
Inconsistent config in loadbalancer exporter

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector-contrib#1697]
**Describe the bug**
Config miss alignment in loadbalancer

**Steps to reproduce**
See the new way of defining dns added in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1650

**What did you expect to see?**
A single consistent way to specify addresses using "endpoint"

**What did you see instead?**
To specify endpoint for dns resolver user has to specify hostname + port

**What version did you use?**
master

**Comment by jpkrohling** [comment]
It isn't consistent because the values mean different things. 

The DNS resolver accepts a hostname to send a DNS A/AAAA query in order to resolve the list of backends. For each one of those results, an endpoint will be built based on the IP + the port specified in the config.

The static resolver, on the other hand, accept a list of endpoints (not hostnames), which is a complete specification of host (name/IP) + port.
