### ISSUE TITLE
[Datadog Exporter] host_metadata::enabled configured to false, but still setting the k8s.node.name & host attributes

### ISSUE THREAD

**Issue by omamoo** [open-telemetry/opentelemetry-collector-contrib#17028]
### Component(s)

exporter/datadog

## Description
While running open telemetry collector as deployment, I'm configuring `host_metadata::enabled` to `false` and I'm expecting that the exporter won't override the `k8s.node.name` attribute, but it's appending the node name that the controller is running on to the existing `k8s.node.name` attribute.

## Steps to Reproduce
1. Create Otel collector pods as deployment (and not as daemonset).
2. Transmit some test metric with the tag `k8s.node.name=bla-bla`.
3. Take a look at Datadog server side, and you'll see the the value of `k8s.node.name` is set to `bla-bla,<host-name-of-colletor-node>`

## Expected Result
I'm expecting to see only the value `bla-bla`

## Actual Result
`bla-bla,<hostname-of-node-that-running-otel-collector>`

![image](https://user-images.githubusercontent.com/91830944/207614883-dc7dc5a2-33b1-43ce-af94-2f4ac31eeb6d.png)

### Collector version

0.67.0

## Environment
OS: alpine-3.16
Compiler(if manually compiled): Got the source code from DockerHub

### OpenTelemetry Collector configuration

```json
{
	"exporters": {
		"datadog": {
			"api": {
				"fail_on_invalid_key": true,
				"key": "****************",
				"site": "datadoghq.com"
			},
			"host_metadata": {
				"enabled": false
			}
		}
	},
	"processors": {
		"batch": {
			"send_batch_max_size": 256,
			"send_batch_size": 100,
			"timeout": "10s"
		},
		"memory_limiter": {
			"check_interval": "5s",
			"limit_mib": 4096,
			"spike_limit_mib": 2048
		},
		"resource": {
			"attributes": [{
				"key": "deployment.environment",
				"value": "Dev",
				"action": "upsert"
			}]
		}
	},
	"receivers": {
		"otlp": {
			"protocols": {
				"grpc": {
					"max_recv_msg_size_mib": 32
				}
			}
		}
	},
	"service": {
		"pipelines": {
			"metrics": {
				"receivers": [
					"otlp"
				],
				"processors": [
					"resource",
					"memory_limiter",
					"batch"
				],
				"exporters": [
					"datadog"
				]
			},
			"traces": {
				"receivers": [
					"otlp"
				],
				"processors": [
					"resource",
					"memory_limiter",
					"batch"
				],
				"exporters": [
					"datadog"
				]
			}
		},
		"telemetry": {
			"logs": {
				"encoding": "json"
			}
		}
	}
}
```

### Log output

```shell
No logs relevant to this issue.
```

**Comment by mx-psi** [comment]
Hi @omamoo, thanks for reporting the issue.

> I'm configuring `host_metadata::enabled` to false and I'm expecting that the exporter won't override the `k8s.node.name` attribute, but it's appending the node name that the controller is running on to the existing `k8s.node.name` attribute.

The `host_metadata::enabled` flag controls whether the 'host metadata payload' is sent or not. This controls 
1. what information is shown on the infrastructure monitoring tab (i.e. whether/how does your host show up on the host list)
2. whether host tags (`host_metadata::tags`) get applied or not.

It does not control any overriding behavior on tags, and disabling it will at most remove the host tags. Off the top of my head, I can't think of any place in the exporter where we would modify the value of `k8s.node.name` within the Datadog exporter, so to further troubleshoot the issue I would like to ask for some sample metrics in the OTLP format, so that I can try and reproduce the issue.

Could you use the [`file` exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/fileexporter#file-exporter) to gather some OTLP data into a file and send us the output (after removing any sensitive details?). 

If you prefer doing this outside of Github, feel free to open a [support case with Datadog](https://www.datadoghq.com/support/) (in which case please mention this Github issue and feel free to mention my name).

Thanks!
