### ISSUE TITLE
[processor/transform] add metadata to processor to indicate data was modified

### ISSUE THREAD

**Issue by ajsaclayan** [open-telemetry/opentelemetry-collector-contrib#17205]
### Component(s)

processor/transform

### Is your feature request related to a problem? Please describe.

Hi community,

My team is using the transform processor to guard against backend limits. The data is dropped if the data hits these constraints, which we don't want (incomplete data is better than no data).
Limits include:
1. Max attribute value length should be no more than X
2. Total number of attributes should not exceed Y

Now that data exists, it would be nice to have some sort of attribute that shows that the telemetry was modified (truncated, attributes were stripped).

### Describe the solution you'd like

Adding an attribute would be straightforward, but the behavior is unintuitive for use cases where some data exceeds the total number of attributes. Would be curious to hear the communities feedback.

### Describe alternatives you've considered

Another approach would be to log when data is transformed.

**Comment by TylerHelmuth** [comment]
@ajsaclayan i would recommend truncating/limiting to 1 less than your limit so you can add a metadata attribute. 

Logging would be very noisy.

**Comment by ajsaclayan** [comment]
@TylerHelmuth agree logging would be noisy and not very useful. 

For truncating 1 less than the limit, are you suggesting using attribute processor? I'm not sure how to add an attribute to data that's only been modified by the transform processor.

That reminds me of another issue which could be a separate topic, but our backend has a limit on the total number of attributes (resource level + data point level). We could set arbitrary limits at each level that total max number of attributes, but would be interested to see if it was possible to limit against the sum of resource and data point with the current transform.

**Comment by TylerHelmuth** [comment]
@ajsaclayan sorry, I explained poorly.  For truncating the length of a single attribute you can do it up to your limit.  When limiting the number of attributes you can do 1 less than your limit so that you have guaranteed room for a metadata attribute.  The `limit` function also allows specifying specific attributes that should never be dropped, so another approach is to use your limit and specify not to drop your metadata attribute.

The transform processor itself doesn't currently keep track of whether or not a piece of telemetry is modified, but it should be possible to detect whether or not a transformation has occurred or will occur with a Where clause.  For example, you can set the metadata attribute if the number of attributes is greater than your limit and then on the next statement do the limiting.  It's not a perfect solution, but it will get you started.

Ultimately the ability to detect if data was sent through any processor and modified is a bigger picture problem and I think should be solved with instrumenting the collector with more in-depth tracing.

> if it was possible to limit against the sum of resource and data point with the current transform

The contexts don't expose the number of attributes they have and we don't have a function to do the counting so at the moment it can't be done.  The framework could support adding this feature.
