### ISSUE TITLE
elastic exporter not recognized

### ISSUE THREAD

**Issue by chitrartha** [open-telemetry/opentelemetry-collector-contrib#1787]
**Describe the bug**
Attempting to configure elastic as an exporter but keeps getting an error complaining that it is an unknown exporters type

**Steps to reproduce**
Add elastic as an exporter and start otel collector using the repo from otel-collector_0.16.0_amd64.deb

**What did you expect to see?**
The collector running with elastic exporter with no issues

**What did you see instead?**
The collector fatally exiting with application run finished with error: cannot load configuration: unknown exporters type "elastic" for elastic

**What version did you use?**
Version: 0.16.0

**What config did you use?**
Config:
```
exporters:
  elastic:
    apm_server_url: "http://0.0.0.0:9200"
    insecure: true
```

**Environment**
OS: Ubuntu 16.04.6 LTS

**Additional context**
2020-12-08T15:46:25.423Z        info    service/service.go:290  Loading configuration...
Error: cannot load configuration: unknown exporters type "elastic" for elastic
2020/12/08 15:46:25 application run finished with error: cannot load configuration: unknown exporters type "elastic" for elastic

**Comment by cyrille-leclerc** [comment]
@chitrartha could you be using the "trimmed" OpenTelemetry Collector package rather than the "contrib" package? The "contrib" package include the vendor exporters such as the Elastic" exporter.

* the package you use: otel-collector_0.16.0_amd64.deb
* the contrib package: [otel-contrib-collector_0.16.0_amd64.deb](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/download/v0.16.0/otel-contrib-collector_0.16.0_amd64.deb)

Could you try installing the [otel-contrib-collector_0.16.0_amd64.deb](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/download/v0.16.0/otel-contrib-collector_0.16.0_amd64.deb) rather than the otel-collector_0.16.0_amd64.deb?

**Comment by chitrartha** [comment]
@cyrille-leclerc Thank you so much. It works now!!
