### ISSUE TITLE
Add logging support to the Elasticsearch exporter

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-collector-contrib#1800]
This issue is moved here from https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1630 as a tracking bug. 

@cyrille-leclerc Let me know if anyone is already working on this. This future is on our TODO list and we can help if no one is actively working on it.

**Comment by cyrille-leclerc** [comment]
Thanks Janaa. I'll clarify by midweek how we are moving forward on on adding logs support to the Elastic exporter.

**Comment by MarkSeufert** [comment]
Currently working on a logs[ Elasticsearch exporter](https://github.com/open-telemetry/opentelemetry-cpp/pull/444) for the C++ repo, it'd be useful to see how the collector defines the mapping between OTEL log fields to Elasticsearch so that we can stay consistent.

**Comment by cyrille-leclerc** [comment]
Thanks for your patience @rakyll and @MarkSeufert.

Elastic plans to work on the OpenTelemetry Collector exporter toward Elasticsearch right now and it should not be a very long task.

We were doing a PoC when we opened https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1630 and we are just starting a new release iteration, it's the right time for us to  implement.

**@rakyll we would like to verify with you one point please**: the PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1801 you initiated connects to [Elastic APM Server](https://www.elastic.co/guide/en/apm/server/current/index.html) rather than connecting to Elasticsearch (see the line of code [here](https://github.com/rakyll/opentelemetry-collector-contrib/blob/8579ee9121358d5ab0aa1873fb7fe1948bc7fa4b/exporter/elasticexporter/exporter.go#L134)).
Our proposal in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1630 is to add an exporter toward Elasticsearch directly, not going through Elastic APM Server.
Our rationale is:
* we want to simplify onboarding of Elasticsearch users who may have not installed Elastic APM Server, who are using plain Elasticsearch,
* Elastic APM Server doesn't have a logs HTTP intake and we don't plan to introduce one because we plan to instead add native support for the OpenTelemetry Protocol on APM Server (alongside the existing Elastic APM HTTP Protocol and the Jaeger protocol).

@rakyll we guess that you also have in mind the addition of a direct exporter toward Elasticsearch, is this correct?

If we are aligned on this vision, we can start implementing with no delay.

Moreover, @MarkSeufert highlighted an important point: a clear and documented mapping between OpenTelemetry Semantic Conventions and the Elasticsearch data model: Elastic Common Schema. 

The specification work started a while ago on https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/logs/data-model.md#elastic-common-schema . 

Our proof of concept is designed to have clarity on this mapping, we propose to use the Pull Requests of this Elasticsearch exporter to validate with the OpenTelemetry the mapping decisions. Would this work for you?

**Comment by rakyll** [comment]
@cyrille-leclerc would you be interested in contributing an exporter. We can help you to validate the scheme mapping. Sorry for opening #1801. I was just looking into Elastic for the first time and wanted to draft a change to note I was looking into it but didn't have time. I'd be happy if you can take over.

**Comment by urso** [comment]
As has been pointed out by @cyrille-leclerc, the current elastic exporter does not ingest data right into Elasticsearch, but forwards metrics and traces to the [Elastic APM Server](https://www.elastic.co/guide/en/apm/server/current/index.html). The APM server applies some additional processing before indexing traces and metrics as documents in Elasticsearch.

In addition to forwarding APM-Server, we plan to add a second "mode" to the elastic exporter. For now we will support indexing only logs directly, but it would be nice to add metrics as a follow up later. We will introduce new settings like `elasticsearch_url`, `api_key` and similar that configure the Elasticsearch endpoint. Elasticsearch and APM Server endpoints are configured, the APM takes precedence if it is available for said event types.

We expect events to be published to follow the OpenTelemetry Semantics. The [OTel Semantics to ECS mapping](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/logs/data-model.md#elastic-common-schema) hasn't been maintained for some time. In the process we will look for required updates and add support for users to configure the mapping.

I hope to have an initial PR ready soon.

**Comment by rakyll** [comment]
cc @alolita

**Comment by ilaif** [comment]
Hey guys, what's the status of the exporter? Couldn't determine if it's "released" yet. Didn't find any documentation.
Thanks!

**Comment by vincentfree** [comment]
I have tried to add the component locally, logs and traces seem to work but the thing that I need which is metrics is still not there. Any update on the timelines and if I can contribute?

**Comment by amccool** [comment]
`ILoggerProvider` implementation using rx.net and batching https://github.com/amccool/AM.Extensions.Logging.ElasticSearch

**Comment by codeboten** [comment]
The logs exporter is currently shipped as part of the contrib distribution: https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-contrib/manifest.yaml

Closing the original issue. If there are additional enhancement requests, please open separate items for them.
