### ISSUE TITLE
OTTL ConvertCase for dot.delimited.case

### ISSUE THREAD

**Issue by seankhliao** [open-telemetry/opentelemetry-collector-contrib#18084]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

I'd like to convert metric/attribute names into a standardized form of `dot.delimited.names`

### Describe the solution you'd like

[ConvertCase](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#convertcase) learns a new `toCase` value of `dot`

### Describe alternatives you've considered

`replace_all_*` functions only work on maps, not a string as required for changing the metric name.

**Comment by TylerHelmuth** [comment]
@seankhliao Would replace_pattern work for you?

**Comment by seankhliao** [comment]
I skipped over it thinking it was a single match variant

I think it only works if combined with converting to snake case first, ConvertCase will handle acronyms which is difficult to replicate in regex

eg `namespaced_PRCount` -> `namespaced.pr.count`

**Comment by seankhliao** [comment]
I sent in #18275 for the case I raised here (`dot`).

Though I'm wondering if `ConvertCase` would be better served by being more general:
if the `toCase` argument is a single character, use that as the delimiter, otherwise fall back to the well known ones (`upper` and `lower`).
This would help with systems that use other delimiters, eg GCP conventions appear to be `/` separated

**Comment by TylerHelmuth** [comment]
@seankhliao you raise an interesting point.  I certainly don't want to keep adding new cases for each character that someone wants to delimit with.  I think it would be good to expose `ToDelimited`'s capability somehow.

A couple ideas:
1. At the moment OTTL purposefully does not do optional parameters.  We could add a third parameter that is not used for established named cases such as `upper`, `lower`, `camel`, and `snake` (although I think `snake` could be covered via `ToDelimiter("_")`).  But that is kinda messy for named cases.
2. As you mentioned, we could use the `toCase` parameter as a delimiter if it is a single character, otherwise fall back to known patterns.  If none are matched, error.  The parameter feels overloaded with this idea, but it helps deal with a third param and a breaking change.
3. We could expose `ToDelimited` via a separate function.  But it'd be sooo similar to convert case :/.
4. We could also just suck it up and add new cases for different delimiting character.

I think before we merge in your PR we should come to a conclusion on this.  @evan-bradley @bogdandrutu what do you think?  I lean towards @seankhliao's idea or option 1.

**Comment by evan-bradley** [comment]
I'm split with options 1 and 2. If we add an extra parameter, one will always be unused, and to me that's a little odd. On the other hand, overloading it with either cases or character delimiters feels like we're mixing up two concepts (even if they're fairly closely related). I think one thing that would help me feel better about option 2 is if we added a few more common separators (`-` and `|` come to mind) as named cases. This would make it so that the fallback of using a character hopefully becomes a rare exception.

One thing I like about option 3 is that it is explicit. It makes the difference between the two ideas (naming case vs. delimiter) very clear, even if there is some overlap in functionality.

**Comment by TylerHelmuth** [comment]
With https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20879 I think optional parameters will be the  solution to this issue.

**Comment by TylerHelmuth** [comment]
Optional Parameter support is released which means we can come back to this issue. I feel the solution is to add a new optional parameter

**Comment by evan-bradley** [comment]
It would be nice to find a common term between "delimiter" and "case" and have a function that has `case` and `delimiter` optional parameters the user can pass to specify how to format the output string. Barring that, making the case in `ConvertCase` optional and adding a `delimiter` optional parameter should suffice.
