### ISSUE TITLE
Scale OpenTelemetry collector for metrics?

### ISSUE THREAD

**Issue by fracasula** [open-telemetry/opentelemetry-collector-contrib#18204]
### Component(s)

exporter/loadbalancing

### Describe the issue you're reporting

Apologies for asking a question here, the Slack channel seems to be private.

I was having a look at the official docs on the [loadbalancer exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/loadbalancingexporter/README.md) and I realized that only `traces` and `logs` are supported.

I'm trying to understand why is that:
1. because the project is not mature enough so it doesn't have a `metrics` pipeline (not yet done)
2. because it doesn't make sense to horizontally scale for metrics
3. something else

Which one is it? Can somebody shed some light on this?

We're planning to use OTel for both metrics and traces. I wonder if it makes sense to have Prometheus scrape the metrics from the LoadBalancer (Gateway) and then have the other collectors (the ones behind the LoadBalancer) just get the traces.

Alternatively we could use sidecars but sidecars are a 1-to-1 with the pod and they get restarted with it. We were looking for something more resilient and that is independent from the services that will send the metrics/traces.

**Comment by jpkrohling** [comment]
A mix of them all. 

2. metrics that are pushed into the collector are mostly stateless so that you can horizontally scale the collector with regular load balancers. The same can be said about logs, though, but a few people in the community made the case for needing a consistent decision about which backend would receive the log entry and sent a PR adding support for logs
3. besides nobody requesting and proposing a PR for it, another reason is that Prometheus-style pulls are not suitable for this kind of scaling. I detailed this a bit on this doc page (sorry for linking a vendor-specific website, but the content is vendor-neutral and will hopefully land on otel's website soon): https://grafana.com/docs/opentelemetry/collector/how-to-scale/

I'm closing this, but feel free to reopen if there's anything still unclear.
