### ISSUE TITLE
Version support on kubernetes by the  k8sattributesprocessor

### ISSUE THREAD

**Issue by Driksi** [open-telemetry/opentelemetry-collector-contrib#18759]
### Describe the issue you're reporting

Hello, I am currently using the kubernetes version 1.21 and I would like to know if this version is supported by the processor.
Thank you.

**Comment by astencel-sumo** [comment]
This is a valid question, as there is nothing in the docs that would describe the k8s version support by the k8sattributes processor or other k8s-related components.

Having said that, I believe the k8sattributes processor's functionality is generic enough to warrant its compatibility with all supported (and also all not supported) versions of Kubernetes. It most certainly works well with Kubernetes 1.21.

The k8sattributess processor's dependencies on the k8s API are [v1.Pod](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#pod-v1-core) and [v1.Namespace](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#namespace-v1-core), which have probably existed since, I'd guess, Kubernetes v1.0.

**Comment by dmitryax** [comment]
We aim to ensure the support of the latest four versions at least. We are adding end-to-end tests for that https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18767. But that support can be extended for particular collector components

**Comment by astencel-sumo** [comment]
Do we want to add something to the docs about the declared (and actual?) support? What do you think @dmitryax?

**Comment by dmitryax** [comment]
@astencel-sumo Yes, we need to update the docs. I'd do that after the e2e tests are in place. Currently we can do that for the k8s attributes processor
