### ISSUE TITLE
Datadog exporter exporting to local datadog agent 

### ISSUE THREAD

**Issue by munali** [open-telemetry/opentelemetry-collector-contrib#18763]
### Component(s)

Datadog exporter

### Describe the issue you're reporting

I notice that if I run a OTLP collector and try to use the datadog exporter, it expects to export to Datadog backend and does not support exporting to a datadog agent running locally. This is seen by an error like so:

```exporter "datadog" has invalid configuration: api.key is not set```

Not all Datadog agents have been upgraded to have OTLP ingest, so being able to export to the datadog agent would be helpful in the short term.

**Comment by mx-psi** [comment]
Hi @munali, thanks for your issue and apologies for the delay in replying. The recommended way of doing this is by upgrading the Datadog Agent to a version that supports OTLP ingest and using the OTLP exporter to send data to it. 

We don't have plans to support sending to the Datadog Agent via the Datadog exporter at the moment; using OTLP will result in a more consistent experience since the mapping happens through the same code as the Datadog exporter.
