### ISSUE TITLE
New example without mock frontend and backend

### ISSUE THREAD

**Issue by jankaifer** [open-telemetry/opentelemetry-collector-contrib#19404]
### Component(s)

examples/demo

### Describe the issue you're reporting

We are adding support for open telemetry to https://github.com/vercel/next.js and we want to give our users an easy way to run locally OTel collector for debugging purposes.

Essentially something like `examples/demo` but without a mock server and mock client.

We will create a new GitHub repo for that (at least for now), but it would probably be better if we could add it here as a new example that is `ready-to-go`.

Sorry If you already have this example somewhere (in different repo) and I just haven't found it.

**Comment by JanKaifer** [comment]
I created this ["fork"](https://github.com/vercel/opentelemetry-collector-dev-setup) in the meantime. Let me know if you think it's a good idea to move it here.

**Comment by atoulme** [comment]
You can take a look at https://github.com/open-telemetry/opentelemetry-demo in general to see how we approach demos.

My employer Splunk has examples that use the collector and a simple Splunk enterprise deployment as a Docker Compose you can try to inspire from: https://github.com/signalfx/splunk-otel-collector/tree/main/examples

**Comment by JanKaifer** [comment]
We try to keep our demos in our main https://github.com/vercel.next.js repo.
And we would like to keep the core next.js project for otel example too.

But in order to be able to efficiently debug OTel locally it's handy to run some dockerized services (collector + backend).

Right now we are telling people to use https://github.com/vercel/opentelemetry-collector-dev-setup which is essentialy `examples/demo` but without the mock server/client and that works well.

We just thought that it's handy enough even for others that it would better fit in this repo or under the `open-telemetry` scope on GitHub.
