### ISSUE TITLE
[chore] Remove components from root module

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#19462]
### Is your feature request related to a problem? Please describe.

The root module has all the components right now, but there is no reason for that now that we can use the builder to make our collector distro and other tools.

### Describe the solution you'd like

Remove all components from root go module. If possible, remove the root go module completely.

**Comment by TylerHelmuth** [comment]
Is the root go.mod causing problems or is the primary goal for removing because it is not being used? It sounds like maybe cross-link uses it to help us with replace statements, is that accurate?

**Comment by atoulme** [comment]
It doesn't have a valid use on its own and most of the code related can instead live under cmd/otelcontribcol. This is probably less toil overall to manage long term.

While crosslink helps, the current approach taken by ocb is to have replace links in the yaml, so I'm not sure we need that.

**Comment by Aneurysm9** [comment]
crosslink is used for more than just distribution building.  It ensures that every module in the repo replaces its uses of every other module in the repo so that local changes function as expected and we don't have to constantly update pseudoversions.  

I don't think removing crosslink here is either necessary or desirable.  It should only need the root module (which still appears to exist in the associated PR) to [root the tree of modules](https://github.com/open-telemetry/opentelemetry-go-build-tools/blob/main/crosslink/internal/common.go#L38) on which it will operate.  It does a [walk through the filesystem](https://github.com/open-telemetry/opentelemetry-go-build-tools/blob/main/crosslink/internal/graph.go#L61) from that point to [build a dependency graph](https://github.com/open-telemetry/opentelemetry-go-build-tools/blob/main/crosslink/internal/graph.go#L28-L31) for all the [modules it found](https://github.com/open-telemetry/opentelemetry-go-build-tools/blob/main/crosslink/internal/graph.go#L66).  It then [performs replacements](https://github.com/open-telemetry/opentelemetry-go-build-tools/blob/main/crosslink/internal/crosslink.go#L63) on [every module](https://github.com/open-telemetry/opentelemetry-go-build-tools/blob/main/crosslink/internal/crosslink.go#L41) it has a dependency list for.

If it has a defect that causes it to not function as expected in this situation then we should fix that.  Let's not give up the benefits it provides.

**Comment by mx-psi** [comment]
I assume #21790 and https://github.com/open-telemetry/opentelemetry-go-build-tools/pull/308 would help to do this
