### ISSUE TITLE
[Datadog] All metrics exported with "otel." prefix

### ISSUE THREAD

**Issue by lchayoun** [open-telemetry/opentelemetry-collector-contrib#2016]
**Describe the bug**
We are using the collector to proxy metrics from carbon to DataDog
All of the metrics are prefixed with "otel."

**Steps to reproduce**
Run the collector with any receiver and DataDog exporter

**What did you expect to see?**
The metrics as they were send to the collector

**What did you see instead?**
"otel." prefixed metrics

**What version did you use?**
Version: v0.17.0

**Comment by mx-psi** [comment]
Hi @lchayoun, thanks for reporting this and apologies for the late response. While this was intended (see #1483) we have discussed this internally and we will change this behavior in an upcoming release.

Once this issue is addressed, the `otel.` prefix will only be added to metrics produced by the hostmetrics receiver, since these metrics can easily clash with the Datadog Agent system check which is enabled by default.

**Comment by lchayoun** [comment]
Sounds great, thank you for the update!
