### ISSUE TITLE
[pkg/stanza] Support back-pressure from downstream consumers

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#20511]
Currently, we drop logs on any error from the downstream consumer. This behavior is not desired in case of temporary errors. Users might want to slow down reading the log files instead of dropping the data.

We should provide a way to have such behavior that a configuration option can control.

**Comment by tigrannajaryan** [comment]
@dmitryax one related thing I would like to decide is if that configuration option needs to be per receiver or we want it to be per pipeline, for example as a memory_limiter processor config option?

If it is memory_limiter option then memory_limiter can easily make the decision to drop the data and return "success" to the caller. If the option is to retry then memory_limiter should return non-permanent error to the caller, preferably a distinct non-permanent error that indicates the retrying should not be immediate, but after a while (since in memory limited situations we want receivers to slow down).

**Comment by dmitryax** [comment]
> @dmitryax one related thing I would like to decide is if that configuration option needs to be per receiver or we want it to be per pipeline, for example as a memory_limiter processor config option?

I think the memory limiter should not automatically drop itself and instead provide more specific error messages such as RetryableError, as you suggested. My reasoning is that the decision to drop or retry can significantly vary among different receivers. Even the same receiver type can have different modes of operation, such as the filelog receiver which may choose to drop certain application logs but never miss any audit logs. Given that multiple receivers are typically used in a single pipeline, setting this configuration on the memory limiter would require splitting the pipeline.
