### ISSUE TITLE
[receiver/dockerstats] Add pids_stats metrics

### ISSUE THREAD

**Issue by sigilioso** [open-telemetry/opentelemetry-collector-contrib#21041]
### Component(s)

receiver/dockerstats

### Is your feature request related to a problem? Please describe.

I would like to improve the dockerstats receiver with the addition of `pids_stats` metrics.

### Describe the solution you'd like

Docker container's stats endpoint returns [pids_stats](https://github.com/moby/moby/blob/master/docs/api/version-history.md?plain=1#L607) if the Linux's Kernel is >= 4.3 and [pids group](https://www.kernel.org/doc/Documentation/cgroup-v1/pids.txt) is supported. 

It can include up to two metrics:
- `pids_current`: current number of processes.
- `pids_max`: maximum number of processes.

I would like the receiver to support reporting those metrics when available.

### Additional context

This is part of a New Relic initiative to adopt the dockerstats receiver as a source of instrumentation.

I would be happy to work on it once the proposal gets refined/approved.

**Comment by jamesmoessis** [comment]
Thanks for the proposal @sigilioso, would be happy to add this feature, and happy to review any PRs for it.

A couple of things to consider: 
* We will need to bump the supported docker API version, since the pids_stats are only available in >=v1.23 (this receiver is currently on 1.22). This will technically be a breaking change, but since the 1.22 API spec is 8 years old now and this receiver is still in alpha, that's fine by me.
* There should be tests covering both cases of when these stats exist and when they don't, since they only exist in kernel version 4.3 and above. 

That's all I can think of for now. Let me know if you have any more questions!

**Comment by crobert-1** [comment]
@sigilioso It looks like your PR #21111 was meant to address this, please close this issue if it's been resolved.
