### ISSUE TITLE
[receiver/dockerstats] Add extra metrics

### ISSUE THREAD

**Issue by carlossscastro** [open-telemetry/opentelemetry-collector-contrib#21087]
### Component(s)

receiver/dockerstats

### Is your feature request related to a problem? Please describe.

I would like to improve the dockerstats receiver with the addition of a few more metrics.

### Describe the solution you'd like

Similar to the receivers `container.cpu.percent` metric, we would like to also report percentage metrics for kernel, user, and per core

It would include the following 3 metrics:

* `container.cpu.utilization.usermode`: Percent of CPU in user mode used by the container.
* `container.cpu.utilization.kernelmode`: Percent of CPU in kernel mode used by the container.
* `container.cpu.utilization.percpu`: Per-core percent of CPU used by the container also with a `core` metric attribute

Together with these 3 metrics we would propose the addition of 3 new metrics from the docker inspect API:

* container.cpu.limit: The CPU limit set for the container.
* container.cpu.shares: The CPU shares set for the container.
* container.restart.count: The number of restarts for the container.

I would like the receiver to support reporting those metrics when available.

### Additional context

This is part of a New Relic initiative to adopt the dockerstats receiver as a source of instrumentation.

I would be happy to work on it once the proposal gets refined/approved.

**Comment by atoulme** [comment]
I think you can start working on this as long as those metrics are disabled by default to start with. Did I count 6 metrics though?
Can you start with an easy one, like `container.restart.count`?

**Comment by jamesmoessis** [comment]
@carlossscastro I have a couple of questions about this.

> Percent of CPU in (user | kernel) mode used by the container.

Will this be percentage be with respect to the overall container usage, `container.cpu.usage.total`? If so, these metrics are easily calculated using the existing metrics. For example:

```
(container.cpu.usage.usermode / container.cpu.usage.total)*100
``` 

The calculation can be done using a `processor` or using any chosen backend query language. I would prefer users utilise the existing timeseries rather than generating new ones - it means less backend storage and less vendor cost for them. We have to be particularly careful for container metrics, since there tends to be a lot of containers running and therefore a lot of timeseries generated.

> Per-core percent of CPU used by the container also with a core metric attribute

Can you clarify what the percentage calculation would be here? Is this percentage of time spent by the core in a non-idle state vs time the core spent idle? Or is this a percentage of that core's usage with respect to the whole system? 

For `container.cpu.limit`, `container.cpu.shares`, and `container.restart.count`. I don't have any problems adding these in.  It would be great for these to be added as non-default metrics. Their API minimum version is my only possible concern, do you know when these were introduced to the docker API?

**Comment by carlossscastro** [comment]
Hi @atoulme @jamesmoessis ,

Thanks for your quick feedback on this.
I think you're right regarding the cpu percentages. They all can be handled by a processor or even in the backend.
Even the per cpu percentage can be calculated in the same way after a closer look. The aim here would be calculating the percentage for each core and compare it not only with the whole system but also with core limit set for the container (if it exists), but again that can also be handled by a processor give the metrics we have now (together with `container.cpu.limit`).

As for the other 3 additions (`container.cpu.limit`, `container.cpu.shares` and `container.restart.count`) the minimum api version would be 1.25 and would be added disabled by default.

If this looks good to you, feel free to assign the ticket to me and I'll be happy to start working on it soon.

**Comment by jamesmoessis** [comment]
Sounds great @carlossscastro :) Feel free to ping me when the your PR is up. Please try and split these features across a few reasonably sized PRs.

**Comment by carlossscastro** [comment]
Hi @jamesmoessis ,

I created a PR to add those 3 metrics. As they are collected from the same inspect api I think it was reasonable to add them all in the same PR.
Let me know if you prefer otherwise though.

PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21803

Thanks
