### ISSUE TITLE
Support ruok command in zookeeper receiver

### ISSUE THREAD

**Issue by akats7** [open-telemetry/opentelemetry-collector-contrib#21481]
### Component(s)

receiver/zookeeper

### Is your feature request related to a problem? Please describe.

Other zookeeper agents (e.g., datadog) support the ruok command along with the metric set from mntr, I wanted to inquire regarding adding a scraper to get the ruok response, and potentially adding it as an attribute as it likely doesn't belong in a metric table as a standalone.

### Describe the solution you'd like

We would like the ruok response to be scraped along with the mntr metric set.

**Comment by akats7** [comment]
Hi @djaglowski, wanted to follow up

**Comment by djaglowski** [comment]
Hi @akats7. Thanks for the proposal.

Am I correct in understanding that this command is essentially a boolean health check? If so, my suggestion would be to model this as an `uptime` metric. [Here are several examples](https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-collector-contrib+uptime+language%3AYAML&type=code&l=YAML). What do you think about this approach?

Otherwise, can you clarify where you would add this as an attribute?

**Comment by akats7** [comment]
Hey @djaglowski, thanks for the quick response.

Yep it is a boolean health check, after looking at the example set, I stumbled upon a mongodb health metric ([here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/mongodbreceiver/metadata.yaml#L334)) that seems to be a analogous to what we're trying to see with zookeeper. It's of kind gauge with a numeral 1 or 0 to represent health. I think this would be a good fit.

**Comment by djaglowski** [comment]
@akats7, that makes sense. Sounds good to me.

**Comment by akats7** [comment]
Hey @djaglowski, the zookeeper server closes the socket after running each command, so to run the ruok command in the same scraper, we have to use multiple connections. I wanted to run it by you before I update the existing tests.

I'll open and link a preliminary PR.
