### ISSUE TITLE
[chore] [CI] Include updating the otelcontribcol ocb manifest in make update-otel target

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#21632]
`make update-otel` should additionally update collector core version in `cmd/otelcontribcol/builder-config.yaml` and run `make genotelcontribcol` to avoid doing it manually every time

**Comment by mx-psi** [comment]
Labeling as 'release-retro' since I stumbled upon this on the v0.81.0 release. I think it should also include `oteltestbedcol` and running `make genoteltestbedcol`.

> Is this is a dupe of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18451?

IMO #18451 depends on this issue but they are not duplicates of each other

**Comment by gord02** [comment]
Hello everyone! I'd like to tackle this task but I could use more context on the part about updating the collector core version. Is there an existing makefile command that updates the builder-config.yaml file? How should I go about implementing this aspect?

**Comment by mx-psi** [comment]
Bumping up the priority of this again, since it came up again on the v0.97 release

**Comment by led0nk** [comment]
#32038  open and going into stale. I'm not quite sure if this feature is still wanted, but i don't want to ping too much 😅

**Comment by mx-psi** [comment]
@led0nk So long as you do it respectfully, feel free to ping if necessary here or on the CNCF Slack, specially if somebody has already started reviewing your thing

**Comment by led0nk** [comment]
@mx-psi i recently had a look into this and I think this kept happening, due to updating `go.mod` file after making the update to `builder-config.yaml's`:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/01258c5ae9b945d64170d3010dee71dcc20796bb/Makefile#L382-L384

But since we used the main `go.mod`-file to pull versions from, we have to define a new source, which can provide the needed versions, wdyt?

**Comment by mx-psi** [comment]
Ah right, that makes sense, yes. Not sure what the best source of truth is but changing this should fix it

**Comment by led0nk** [comment]
I'm not sure if I'm correct, but seems like the main `go.mod`-file moved to `cmd/otelcontribcol/go.mod` since it was changed here:

https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/cfd83af71471ae54f6489355c47cac56c5f746e1#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6

So I'd change the source file where we pull from to that, if you confirm.

Another option would be:

https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-contrib/manifest.yaml

But this would probably be a "non-clean" version, since we got a main `go.mod`-file in this repo.

**Comment by mx-psi** [comment]
Hm, yeah, I guess I am somewhat confused about taking `cmd/otelcontribcol/go.mod` as the source of truth to then update the file `cmd/otelcontribcol/go.mod` is generated from, but if we do things in the right order it makes sense to use it.
