### ISSUE TITLE
SpanMetrics converter: include http.request.status_code as metric attribute

### ISSUE THREAD

**Issue by mariomac** [open-telemetry/opentelemetry-collector-contrib#22011]
### Component(s)

processor/spanmetrics

### Is your feature request related to a problem? Please describe.

After converting my HTTP request traces to metrics, we expected that the `status_code` field contained the HTTP response status (e.g. 200, 404, etc...). After digging into it, we realized that it actually contains the `Unset`, `Ok` and `Error` values about the Span status.

### Describe the solution you'd like

I'd suggest that `status_code` metrics attribute value is set from `http.request.status_code` (or e.g. `rpc.grpc.status_code` for GRPC services).

**Comment by albertteoh** [comment]
`status_code` is part of the [OTEL trace specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-status), and I think it's important to stay true to that; moreover, because that value is always present, we can rely on it as one of the "standard" dimensions of a metric.

On the other hand, `http.request.status_code` is not guaranteed to be present, so I don't think we can rely on it for status codes.

Have you tried adding `http.request.status_code` to the `dimensions` configuration of the `spanmetricsconnector`? Example: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/spanmetricsconnector/README.md#examples.

**Comment by mariomac** [comment]
No I didn't try, as I was working on a managed instance. But thank you for the explanation and the exposition of the solution!
