### ISSUE TITLE
[processor/resourcedetection] Additional system attributes

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#22045]
### Component(s)

processor/resourcedetection

### Is your feature request related to a problem? Please describe.

I would like to add some additional attributes to be fetched by the system detector. These would provide useful context on the machine that is generating telemetry and would be useful to my vendor for infrastructure monitoring. All of the following are in one of the specs (ECS or OTel's). I will open separate issues for other attributes not in the spec.

### Describe the solution you'd like

Add the following `host` or `os` attributes:

- [x] #24541
- [x] #24765
- [x] #22939
- [x] #29587

Some of these are available in Elastic Common Schema, I will work on the semantic conventions repository to add these before putting them in the `system` detector.

### Describe alternatives you've considered

We could add these to a different processor or detector, but the system detector seems like the best place to put these.

### Additional context

As far as I can tell, no other detector supports these, so there should be no problems similar to #21233, so we can safely add these by default.

**Comment by mx-psi** [comment]
> @mx-psi can we wait for #21482 to land before this? I believe most of the new fields are better to be added as optional.

I don't think these attributes suffer from the same issues as `host.name` or `host.id`: for the most part there is single well defined value that they should have, so while I think it is useful to be able to enable/disable them, I don't think #21482 should block this. Do you have a specific example on what other component/SDK detector these would conflict with?

I am also undecided on whether they should be optional or not; I am not against making them optional but I think we should understand why we want to make them optional (specially considering the precedent on the resource detection processor which has historically been "just add everything as enabled by default")

**Comment by dmitryax** [comment]
Enabling all the attributes significantly increases the payload for the users that enable the `system` detector, and not all of them seem to be essential as `host.name` or `host.id`. Given that it's a big list, it's great to evaluate them and define optional/default now instead of changing them later.

Also, I think all of them should be defined in [the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/ce2c5946faa9c961ea01d89c7aed83621865b67b/specification/resource/semantic_conventions/os.md). Anything that is not defined there yet, should be optional to avoid future breaking changes in future. Once it's there, we can align default/optional with the spec's required/recommended.
