### ISSUE TITLE
[pkg/ottl] Expose a logger to the contexts

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#22076]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

Currently the OTTL framework doesn't provide any way to pass a logger to the contexts.  This makes it challenging for contexts to report warnings or debug info to users when they are facilitating getting and setting.

### Describe the solution you'd like

We should implement a solution that lets components that depend on OTTL pass their logger into the parser and all the way into the contexts.

### Describe alternatives you've considered

We could use print statements, but thats not as good.

### Additional context

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21773#discussion_r1197335892

**Comment by swar8080** [comment]
Hey @TylerHelmuth, I can help with this

Do you think all components should be required to pass a logger, or should it be optional with a common fallback logger? All components have a logger somewhere up in the callstack, so I don't mind passing it along up until the point where OTTL is used if that's preferred. From the description it sounds like the goal is to make the logger accessible to internal contexts like `MetricContext` - which looks do-able by storing it on the `TransformContext`s that components create. I was thinking of doing one type of context to start to get some early feedback

Also is the components' loggers is preferred over a common OTTL-created logger because they'd prefer to see the name of the component using OTTL in the logs?
