### ISSUE TITLE
sapmexporter: Add warning to user for insecure storage of user credentials at rest

### ISSUE THREAD

**Issue by alolita** [open-telemetry/opentelemetry-collector-contrib#2232]
**Is your feature request related to a problem? Please describe.**
When using the the sapmexporter to connect with the vendor backend service, the user has to input API tokens in plain text which is exposed at rest. This is a security exposure that needs to be communicated to the user.

**Describe the solution you'd like**
The solution proposed includes -
* adding a warning which is actively communicated to the user 
* recommend storing the token securely at rest (encryption at rest)
* recommend adding clear documentation itemizing security risks bundled in the exporter folder

**Additional context**
Unit tests exist for checking unauthorized access but these tests are not enough for an user to understand this security risk. See related unit test - 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/sapmexporter/exporter_test.go#L59

**Comment by flands** [comment]
@alolita this may or may not be true depending on how the user has configured the system and I am also unsure how you could confirm whether this is the case or not. In k8s you could use something like https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/. In addition, assuming the collector runs standalone (i.e. no application running in same location), which is the recommendation today, then encryption does not really help given compromising the Collector (only attack vector) exposes the token regardless. Perhaps the solution here is to create a security.md with recommendations on hardening. 

Also note this issue is for any sensitive information -- TLS would be another such place.

**Comment by alolita** [comment]
Hi @flands I agree there are multiple scenarios of how the user has configured their system. Agree TLS is another alternative. Our security guidance for the sapmexporter is to add documentation about alerting the user to store their credentials securely at rest. This guidance also applies to other OTel Exporters since we're seeing exposed credentials for other components too. Let me know if you need more details.

**Comment by mx-psi** [comment]
Hi all, since this is an issue that affects several exporters (see #2230, #2231, #2233) I am interested in finding a common solution, such as a docs page with security recommendations for the deployment of the OpenTelemetry Collector that we can link from each exporter's documentation and/or some sort of automated warning.

I agree with @flands that this might not be an issue depending on the system configuration. On systems where it is an issue, the OpenTelemetry Collector has builtin ability for environment variable expansion in the configuration, so one could retrieve the credentials via an environment variable set by a secret manager (such as e.g. the one mentioned above for k8s). I think that is a reasonable solution to recommend on insecure environments. Would that address the security concerns of this and related issues?

Additionally, one could mark certain settings as sensitive, and detect whether they were stored in plain text or loaded via an environment variable. That could help in emitting a warning if they were stored in plain text, but I don't think that is desirable when e.g. the Collector is running standalone, and I don't think we can reliably differentiate between that and unsafe cases.
