### ISSUE TITLE
[pkg/stanza]: deduplicate documentation for receivers

### ISSUE THREAD

**Issue by sumo-drosiek** [open-telemetry/opentelemetry-collector-contrib#22775]
### Component(s)

pkg/stanza

### Describe the issue you're reporting

I don't see a reason for duplication of receiver and operator documentation. It's annoying that every change in some of stanza operators require double work in terms of docs. I believe the possible solutions are to link from receiver to operator (instead of copying) or just drop operator configuration. Example receiver is journaldreceiver:

- [receiver/journaldreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/fbd9a994ad37d0053346c19409636b5ab9949a98/receiver/journaldreceiver/README.md)
- [pkg/stanza/docs/operators/journald_input.md](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/fbd9a994ad37d0053346c19409636b5ab9949a98/pkg/stanza/docs/operators/journald_input.md)

**Comment by djaglowski** [comment]
I agree we should dedup the docs but I think it's important to present users a "complete" picture in each receiver's readme.

There are two major areas of duplication that come to mind:
1. Each stanza-based receiver has an underlying input operator
2. Every stanza-based receiver shares common "operators" field

I think each of these may need a separate solution. My proposal would be:
1. Delete most of the docs for underlying input operators. Ensure all relevant info is presented in the corresponding receiver readme. Retain the document but mostly just link to the receiver readme.
2. Create a common document for shared aspects such as operators, and auto-inserted into into the receiver readmes.

**Comment by sumo-drosiek** [comment]
@djaglowski

> 2. Create a common document for shared aspects such as operators, and auto-inserted into into the receiver readmes.

As I understand correctly, you would like to automate it (something like `metadata.yaml`)?

**Comment by djaglowski** [comment]
@sumo-drosiek, hopefully it's not necessary to abstract it into a yaml structure, but otherwise that's what I was suggesting.

It could work something like this:
1. Create a common readme file e.g. `pkg/stanza/docs/operators/common.md`
2. Delete common info from stanza-based receiver readmes. Replace with a pair of "key comments" e.g.
  - `<!-- start common stanza info -->`
  - `<!-- end common stanza info -->`
3. Define a make target that finds these strings and inserts the contents of `common.md`.
4. Hook this into `make generate` so this is always up to date? (Or maybe we just run it when necessary.)
