### ISSUE TITLE
Design and implement persistence mechanism for log receivers

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#2287]
Related to #2264 

stanzareceiver currently supports persistence of log ingestion state (e.g. tracking how much of a file has been tailed) into a bbolt database file. 

With the migration to multiple log receivers, we will need to decide how to manage persistence. 
- Will each receiver have the ability to point to a persistence file? 
- Is it ok for receivers to specify the same file? (I think so, but needs validation)
- Is it reasonable to allow each receiver to have its own persistence file? (Probably, but this raises questions of clutter management)
- Is there a reasonable default location for such a file or files? 
  - If so, what is it? 
  - If not, is the default to not persist state?

**Comment by tigrannajaryan** [comment]
>Will each receiver have the ability to point to a persistence file?

Maybe optionally, but I would prefer that the default location works out of the box.

(Question: do we need a different location for Mac or just use the same as Linux? On Mac I think that should be /Library/otelcol or something?)

>Is it ok for receivers to specify the same file? (I think so, but needs validation)

I would say this is probably preferably for end user, provided that internally we can handle synchronization correctly.

>Is it reasonable to allow each receiver to have its own persistence file? (Probably, but this raises questions of clutter management)

I'd prefer not to. What do we gain by that?

>Is there a reasonable default location for such a file or files?
>If so, what is it?
>If not, is the default to not persist state?

I would aim to have a default location so that it is not a required config option and persist by default (maybe have an option to disable). Possible options for the default directory for checkpoints file are:
1. *nix: $TEMP, Windows: %TEMP% (Probably not a good idea).
2. *nix: /var/lib/otelcol, Windows: %ProgramData%/otelcol

**Comment by djaglowski** [comment]
I agree with the above, except that I'm not sure we can allow users to specify a persistence file for each receiver without also allowing multiple persistence files. 

It might complicate implementation to support independent persistence files but the alternatives seem awkward at best.

**Comment by tigrannajaryan** [comment]
Can we assume that in vast majority of case the default locations are good enough? Then we can make choosing the non-default somewhat awkward. Possible options: 
- Allow any receiver to override the default location. Receivers can specify different locations. I assume implementation wise this is not difficult?
- Allow receivers to override the default location. They must all specify the same location or it is a config error.
- Configure the single location via an extension. All receivers will get the same location from the extension.
Neither is ideal, but I can't think of anything else.

**Comment by djaglowski** [comment]
> Can we assume that in vast majority of case the default locations are good enough?

Yes, I think so. 

> They must all specify the same location or it is a config error.

This would be my preferred, until we have a use case that requires otherwise.

**Comment by tigrannajaryan** [comment]
See discussion about a suggested approach here https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2716#issuecomment-800598560

@djaglowski since adding the storage to the core can take some time, I suggest that we implement the centralized generic storage as an extension first. We will iron out the interface and the desired functionality on this extension and once we are certain it is what we want we can think about making it a core feature.

As an extension it will require a tiny bit of config to be enabled:
```yaml
extensions:
  storage:
    # optionally specify settings such as directory or file to store and any other storage options.
service:
  extensions: [storage]
```

This should be sufficient to enable the extensions. Once enabled the components can find the storage extension via `Host.GetExtensions()` call, iterate over the extensions and check if they implement the `Storage` interface (TBD). If the extension is not found then the components fall back to storage-less mode (i.e. for `filelog` it means no offsets saved - and we can print a warning in the logs in this case).

I would expect `Storage` to allow fetching something like a `ComponentStore` given the component name, and `ComponentStore` to expose the functions we need (`set(key, value)`, `get(key)`, `delete(key)`, etc).

(All names above are preliminary suggestions to illustrate the idea).

Thoughts?

**Comment by djaglowski** [comment]
I think this makes a lot of sense.

I should have a design doc ready on Monday, and will begin implementing the extension from there.

**Comment by djaglowski** [comment]
@tigrannajaryan I've compiled our discussion and a small number of additional details into a [design doc](https://docs.google.com/document/d/1So5TGoLBRcukUWtpS8dN-K7_Y6DvBychzewUkfbKw2w/edit?usp=sharing).

There are a few areas which likely still need more input, but I think we have enough clarity that I can get started on an initial implementation tomorrow.

**Comment by tigrannajaryan** [comment]
@djaglowski the design LGTM. Can you please circulate it more widely and ask for comments/reviews?
