### ISSUE TITLE
[META] Work on making sure we organize SIG calls for impact

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#22985]
### Describe the issue you're reporting

We have had 2 consecutive SIG calls where we ran out of time before going through the list of items in the agenda.
The call currently goes by whoever entered items in the agenda first. The call also requires folks to be present in the SIG call, which is difficult for some timezones. It might make sense to adopt a different approach. This issue aims to capture suggestions to make this possible.

Please comment on this issue and offer :+1: to any comment you feel is applicable to resolve this issue. This issue needs to be discussed at a SIG meeting as well.

**Comment by atoulme** [comment]
I propose that we ensure that the agenda be formed of all the `discussion needed` issues listed in this github project, presented in reverse chronological order, oldest first. 
Any user may add this label to their issues. Any triager/approver/maintainer may add this label to any issue of the project.
Once reviewed, the label will be removed.

**Comment by atoulme** [comment]
I propose that we elect a secretary as a rotating duty across triagers/approvers/maintainers to share their screen and present the issue reviewed. The secretary is responsible for placing a comment on the issue. The comment can be a succinct reply summarizing the conversation. The comment can be a call to action or a request for clarification. The comment can be a timestamp of the conversation as part of the recording of the call (discussed at minute 32 of the SIG meeting on 5/31/23).

**Comment by atoulme** [comment]
I propose that we delegate assignees of issues or reassign assignees to issues discussed as per interest expressed during the call. Whoever is assigned to the issue, be it the initial assignee or the assignee selecting to intervene and help with the issue, is responsible for the issue's progress forward. The assignee may well want to bring up the issue for review again with the SIG meeting to explicitly call out that they cannot help further and ask for a reassignment.

**Comment by MovieStoreGuy** [comment]
The way I am thinking about is how can we optimise for async first and use the SIG meetings to surface issues that require broader discussions among the collector leads. 

What if we were to change the SIG meetings for the collector to be a planning and prioritisation conversation instead of agenda based which is more synchronise first?

I think this would help steer the conversation to help get us to the v1 goal and also allow cross geo contributors to also be included in the conversation.

**Comment by mx-psi** [comment]
I want to suggest that we have a separate section on the agenda for PR review requests; this is a relatively common type of agenda item that generally does not need much discussion other than assigning someone to review them and we can probably deal with them faster in a more structured way.

We could place this at the bottom, have people write their name if they are going to volunteer reviewing the PR, and discuss only those that don't have a reviewer assigned at the end.

**Comment by djaglowski** [comment]
I think that the SIG meeting is the primary venue for airing issues that _aren't_ being appropriately addressed by our standard tools and processes. It's unique value is that any community member may raise any issue that they feel is urgent or important.

Obviously there are limitations to what can be discussed in an hour and as the community grows we must rebalance priorities accordingly. However, we should be careful not to adopt an overly prescriptive process, or we may end up burying important business. Therefore, I propose that we should make only incremental changes to the meeting in order to preserve the benefits of the open structure.

**Comment by atoulme** [comment]
@djaglowski who is the time keeper? How do we select them?

**Comment by djaglowski** [comment]
@atoulme, I imagine we would ask for volunteers or assign one similar to what you've proposed above for a secretary.

A less formal approach to timekeeping may work as well. It only requires that collector leads step in when a conversation seems to be going on too long.
