### ISSUE TITLE
Request for minor release 0.20.0

### ISSUE THREAD

**Issue by albertteoh** [open-telemetry/opentelemetry-collector-contrib#2309]
I would like to request for a new minor tag release `0.20.0`. @tigrannajaryan advised that the opentelemetry-collector-contrib [release cadence is bi-weekly](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1631#issuecomment-730403692) and the last release tag [`0.19.0`](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.19.0) was 14 days ago, so it looks like one is due. :)

The motivation is to use the [spanmetrics processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/403) though the PR was merged after the latest tag [`0.19.0`](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.19.0).

I am happy to put in the work to prepare the release, but it seems the release engineer will [need to be an approver](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/release.md), of which I'm not.

**Comment by mx-psi** [comment]
See #2319

**Comment by sodabrew** [comment]
Since the 0.20 release is out for this repo now, I'll note here that the tag isn't up yet on GitHub... ;) I'm looking forward to using https://github.com/open-telemetry/opentelemetry-collector-builder to build my local binary! This whole thing is really coming together! :)

@albertteoh awesome work towards the spanmetrics processor. I read over https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/403 to learn more about how to configure it!

**Comment by albertteoh** [comment]
Thanks @mx-psi @sodabrew :)

**Comment by albertteoh** [comment]
Looks like [0.20.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.20.0) is released, tagged and docker images available. Thanks everyone!
