### ISSUE TITLE
[all] Replace interface{} with any

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#23811]
### Describe the issue you're reporting

Go 1.18 introduced the `any` type as an alias to `interface{}`. To keep our codebase in line with current best practices, we should format all existing code to use `any` instead of `interface{}` and forbid uses of `interface{}` through a linter/gofmt.

Golangci-lint has [this example](https://golangci-lint.run/usage/linters/#gofmt) but it didn't work for me.

**Comment by astencel-sumo** [comment]
It does work for me. After adding the following to the `.golangci.yml` file:

```yaml
diff --git a/.golangci.yml b/.golangci.yml
index 8f0aa18f95..5c4ff74a7d 100644
--- a/.golangci.yml
+++ b/.golangci.yml
@@ -85,6 +85,9 @@ linters-settings:
   gofmt:
     # simplify code: gofmt with `-s` option, true by default
     simplify: true
+    rewrite-rules:
+      - pattern: interface{}
+        replacement: any
```

running `make golint` fails with this:

```console
aerospikereceiver/cluster/node_test.go:79: File is not `gofmt`-ed with `-s` `-r 'interface{} -> any'` (gofmt)
        commands := []interface{}{"node", "statistics"}
```

which is I think expected?

The problem is we need to duplicate this configuration:
- put it in `.golangci.yml` file for `make golint` - to validate files
- in `Makefile.Common` file for `make fmt` - to format files

Is there a way to share the configuration between `golangci-lint` and `go fmt`? :thinking:

**Comment by mx-psi** [comment]
:thinking: maybe my local setup is broken somehow. `golangci-lint` also runs `gofmt` if you pass the `--fix` option to it. One option would be to rework `make fmt` to just use `golangci-lint` for everything.

**Comment by lucasoskorep** [comment]
working on this

**Comment by codeboten** [comment]
Thanks @lucasoskorep!
