### ISSUE TITLE
Add file count metric to filestats receiver

### ISSUE THREAD

**Issue by cxhiggins** [open-telemetry/opentelemetry-collector-contrib#24651]
### Component(s)

receiver/filestats

### Is your feature request related to a problem? Please describe.

I use OpenTelemetry in a deployment which saves all coredumps to a specific folder, and want to export a metric describing the number of cores dumped. This would allow us to enable alerting when processes crash.

### Describe the solution you'd like

Ideally the filestats receiver would implement a `file.count` metric, or something similar, which tracks the number of files which match the specified `include` parameter.

| Unit | Metric Type | Value Type |
| ---- | ----------- | ---------- |
| 1 | Gauge | Int |

### Describe alternatives you've considered

I tried using [hostmetricsreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/README.md) with a `root_path` set to our coredump directory, but unfortunately all instances of this receiver must share the same `root_path` and our other use of the receiver took priority.

**Comment by atoulme** [comment]
That's a cool enhancement. Would you like to contribute it?

**Comment by atoulme** [comment]
Rethinking this - you can get this information by counting the number of MTS coming from the receiver. I think that gets you what you need. The hostmetrics receiver is also no longer setting env vars, so you can use multiple receivers with different root paths. With that, I think I'll close this issue.

**Comment by stef-philipsen-tfs** [comment]
Is it possible to re-open this issue? I think this feature would still be useful.

I want to monitor the amount of files that are currently in a directory.

I'm currently using the Datadog agent for this, which is reporting the number of files in the configured folder. This is reported as one metric/one value.

If I would report it via OpenTelemetry in the way described above, this would mean that I would get as many metrics as there are files, which could get expensive depending on the number of files in the directory. 

The low cardinality version of the metric would suffice in my use case, since I don't need to know which files are in the directory.

**Comment by atoulme** [comment]
OK that’s a valid use. Reopening
