### ISSUE TITLE
Feature Request - Add Trace context to each span (Total Duration and Trace Group)

### ISSUE THREAD

**Issue by amosd92** [open-telemetry/opentelemetry-collector-contrib#24975]
### Is your feature request related to a problem? Please describe.

When trying to solve a performance issue or an availability issue, I want to be able to look for spans with their TRACE context so that I can better filter and understand what is going on.

Use-cases (in query phase):
Filter spans from a specific operation where the full trace took more than 1s.
Filter for all spans with status code 500 and easily see what the parent span operation is and what triggers the span I was looking at

Today, we can store traces in multiple storage engines like OpenSearch, Cassandra, etc. We want to avoid running complex queries regardless of the storage engine.

### Describe the solution you'd like

Add to every span two fields:
trace_duration
trace_group

### Describe alternatives you've considered

This capability exists in "Data Prepper" of OpenSearch and was considered, but it happens after SpanMetrics connector.

### Additional context

https://github.com/opensearch-project/data-prepper/blob/main/docs/trace_analytics.md#processor
It actually called Otel_trace_group processor

**Comment by crobert-1** [comment]
I believe it would be best to file this against this https://github.com/open-telemetry/opentelemetry-specification repository, as this request is relevant for the underlying data model, not the collector or its components.

Otherwise, have you tried to use the [attributes processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor) to accomplish this for your use case? There's a chance it might be able to do this.

**Comment by crobert-1** [comment]
I'm going to close this issue for now, but feel free to reach out if I misunderstood something here.

**Comment by amosd92** [comment]
Thank you for the feedback,
I will give the processor a go.
The reason I added it here is that it will probably be a bit faster to implement, given the tail base sample capabilities to work with a "full" trace.
