### ISSUE TITLE
Allow customer certs for aws sdk

### ISSUE THREAD

**Issue by sethAmazon** [open-telemetry/opentelemetry-collector-contrib#25168]
### Component(s)

exporter/awscloudwatchlogs, exporter/awsemf

### Is your feature request related to a problem? Please describe.

Allow root ca bundle certs to be used by the collector. 
In gov cloud they do not use public aws certs.

### Describe the solution you'd like

I wrote a potential solution. By adding the ability for user to specify a location of a cert file. Then add that cert file to tls config. 
https://github.com/amazon-contributing/opentelemetry-collector-contrib/pull/67

**Comment by rapphil** [comment]
In order to add support to CA root certificates, we should considering updating these components to use the standard configuration for TLS used across the collector:

https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configtls/configtls.go#L65
Or alternatively https://github.com/open-telemetry/opentelemetry-collector/blob/55902b6828857ef98ac219f86274437ac2a66e53/config/confighttp/confighttp.go#L31C6-L31C24

We should:
* Embedding this configuration in the the configuration of awsemf exporter and cloudwatchlogs exporter
* Update how we [create the client](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/aws/awsutil/conn.go#L47) based on the configuration
