### ISSUE TITLE
Noisy logs in windows jobs 

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#25843]
### Describe the issue you're reporting

The windows github actions logs are filled w/ "No such file or directory" warnings, this makes debugging issues quite difficult.

```
find: 'D:aopentelemetry-collector-contribopentelemetry-collector-contribprocessortransformprocessorinternaltraces': No such file or directory
```

It would be great to clean these up. See an example of this here: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5881855994/job/15951164610

**Comment by crobert-1** [comment]
I believe this is caused by the `find` command being run on Windows, and how it handles backslashes in the path. For more context, we can look at the make command that's being run in these tests:
```
make -j2 gotest GROUP=processor
```
`GROUP=processor` means the above command will run with `for-processor-target` as the target group. `for-processor-target` is a reference to the variable `PROCESSOR_MODS`, which is defined as:
```
PROCESSOR_MODS := $(shell find ./processor/* $(FIND_MOD_ARGS) -exec $(TO_MOD_DIR) )
```
Fully expanding these variables results in:
```
PROCESSOR_MODS := $(shell find ./processor/* -type f -name "go.mod" -exec dirname {} \; | sort | grep -E '^./')
```

Running the `find` command in `bash` results in all of directories with processors being listed. 
```
./processor/attributesprocessor
./processor/cumulativetodeltaprocessor
...
```
I believe this is where the problem lies in Windows. As shown in the error message, it's an error with the `find` command, and the problem is that there are no forward or backslashes in the path. I believe the solution here is to update the logic in the `PROCESSOR_MODS` (and receiver, exporter, etc) variable to properly find all relevant subdirectories in a Windows environment.

Note: This is hit in all of the windows tests, not just for processors.
