### ISSUE TITLE
[receiver/snmpreceiver] Rename 'oid' to 'column_oid' in structs that have 'scalar_oid' 

### ISSUE THREAD

**Issue by kuiperda** [open-telemetry/opentelemetry-collector-contrib#26263]
### Component(s)

receiver/snmp

### Describe the issue you're reporting

Scalar OID values can now be used as resource attributes on metrics: [#25174](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25174)

With this change, the 'oid' field used on some structs (like ResourceAttributeConfig) could be renamed to add clarity that it is referencing a Column OID specifically. This would be a breaking change as old configs would still use 'oid' for this field.

**Comment by crobert-1** [comment]
Sounds like a valid idea to me. I understand there's a bit of ambiguity now with the introduction of `scalar_oid`, but I will say the [documentation is pretty clear](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/snmpreceiver#resource-attribute-configuration) that `oid` means `column_oid`. In general we want to avoid breaking changes as much as possible, but since this is `Alpha` stability maybe it's better to change it now than later.

**Comment by kuiperda** [comment]
Sorry to leave this hanging here so long. Closing.
