### ISSUE TITLE
Introduce a new resourcedetection detector to extract k8s node UID

### ISSUE THREAD

**Issue by dloucasfx** [open-telemetry/opentelemetry-collector-contrib#26538]
### Component(s)

processor/resourcedetection

### Is your feature request related to a problem? Please describe.

`[receiver/k8sclusterreceiver]` adds the attribute/dimension `k8s.node.uid` which has all the node labels added as properties and send it along a small set of metrics like `k8s.node.condition_ready` 

We would like to expand the use of `k8s.node.uid` attribute/value and add it to all (or specific) metrics/logs/traces emitted by the collector so we can propagate and correlate the labels/properties in our backend.

### Describe the solution you'd like

Adding a detector to the resourcedetection that pull node specific metadata, in particular k8s.node.uid, would be the ideal solution

### Describe alternatives you've considered

I have looked into `k8sattributes` processor, but it does not pull/expose labels from nodes.
Moreover, I have considered expanding `k8sattributes` processor to add node labels to it, but after internal discussion, we realized that `k8sattributes` processor scope is cluster wide whereas the ask here is for metrics related to a specific node.

### Additional context

PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26524

**Comment by bryan-aguilar** [comment]
I think the k8sattributes processor already does something similar to this for pods and namespaces. From its README
> The k8sattributesprocessor can also set resource attributes from k8s labels and annotations of pods and namespaces

Could this functionality be expanded to also set resource attributes from a nodes labels and annotations? 

Further question since I am not familiar with the k8sclusterreceiver. Do you want the node labels from which the metric data point originated from or from where the collector is running?

**Comment by dmitryax** [comment]
> Could this functionality be expanded to also set resource attributes from a nodes labels and annotations?

Potentially, yes.

> Further question since I am not familiar with the k8sclusterreceiver. Do you want the node labels from which the metric data point originated from or from where the collector is running?

"from where the collector is running" for this issue. That's why we think the resource detection processor is the best place, as other detectors do similar work. We want to have `k8s.node.uid` resource attribute applied to all the telemetry data when the collector is running in the agent mode, including telemetry data that don't have any other k8s attributes (e.g. hostmetrics receiver metrics)

"node labels from which the metric data point originated" -- this ask (when/if needed) would go to k8sattributes processor. So the collector can set this attribute in both agent and gateway modes when it's possible to deduct it from the existing k8s attributes of the client connection.

**Comment by bryan-aguilar** [comment]
Makes sense to me, thank you for the clarification. Sounds like this would fit in as an enhancement to the eks resource detector.
