### ISSUE TITLE
Elasticsearchexporter not working

### ISSUE THREAD

**Issue by neplooho** [open-telemetry/opentelemetry-collector-contrib#2674]
**Describe the bug**
_**if enabled**_, elasticsearchexporter fails on method pushLogsData
**Steps to reproduce**
add elasticsearchexporter to components and configure pipeline with i.e. filelog receiver and elasticsearch as exporter, (logging exporter optional)
**What did you expect to see?**
I expected elasticsearchexporter to push data it received from filelog receiver into elastic
**What did you see instead?**
Instead I can see logging exporter working fine, so pipeline receives log from filelog and transfers it to exporters. But exporter of type elasticsearch fails to push data
**What version did you use?**
7c28ef1e5a4bab5bcaf2f01116f555682ffdce67
This is the latest commit in repo I cloned, not far from v.0.22.0 release
**What config did you use?**
otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:
  filelog:
    include: [ /mnt/logs/application.log ]
    start_at: beginning

exporters:
  logging:
    logLevel: debug
  elastic:
    apm_server_url: http://apm-server:8200
  elasticsearch:
    endpoints: [http://elasticsearch:9200]

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [elastic]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [elastic]
    logs:
      receivers: [filelog]
      processors: []
      exporters: [logging, elasticsearch]
**Environment**
go version: go1.16.2 windows/amd64
I run collector in docker container based on scratch
**Additional context**
If using image from otel registry it fails because it can't recognize elasticsearch exporter. I tried to lookup components file and discovered that it was just not included in build. So I decided to try to enable it by myself. What is status on that exporter and why it's not included in image? Does logs pipeline support any way to export logs into elastic? If no what exporters currently available for logs pipeline?

**Comment by urso** [comment]
Currently only the `elastic` exporter is available for the Elastic stack. The elastic exporter only supports metrics and traces, and requires Elastic APM Server to be available.

A separate Elasticsearch exporter for publishing logs (and later metrics) directly to Elasticsearch is still in development. The exporter is not registered with the otel collector contrib distribution yet (it is not compiled into the collector), because it is not finished (and not tested) yet. The pushLogs will currently panic, as the event transformation from protobuf to JSON is still missing.

You can follow the progress on https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1800.
Unfortunately work has stalled a little as I was out of office, but I hope to have the initial version of the exporter available soon.
