### ISSUE TITLE
Include Connectors when using Cfgmetadatagen

### ISSUE THREAD

**Issue by BTripp1986** [open-telemetry/opentelemetry-collector-contrib#26990]
### Component(s)

cmd/configschema

### Is your feature request related to a problem? Please describe.

As part of a tool have built I use the cfgmetadatagen to generate metadata for the component configs but it does not generate metadata for connectors. Most connectors don't require any additional config, but the countconnector and spanmetricsconnector do require additional config.

### Describe the solution you'd like

I would like connectors to be included when generating metadata with the cfgmetadatagen.

### Describe alternatives you've considered

I am currently using regex to parse the source files, a solution I was using for all components until I discovered the cfgmetadatagen. I am now refactoring my app to use cfgmetadatagen, but it would be great to have a consistent format from which to get config fields and default values.

### Additional context

It seems that this would be a fairly trivial addition, but I could be wrong. I am a Go novice so I could potentially create a PR for this, but if this is deemed a valid feature request it would be great if someone more competent with Go could add the feature.

**Comment by mx-psi** [comment]
I am in favor of this

**Comment by haoqixu** [comment]
I have submitted a draft PR (#29001), but it turns out that `configschema` will return error on the `forwardconnector`. 

`forwardconnector` returns an anonymous empty struct as [default config](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.88.0/connector/forwardconnector/forward.go#L31) and `reflect.Type.PkgPaht()` returns empty string for non-defined types. As a result, `configschema` failed to find package path for `forwardconnector` (via `configschema.DirResolver.TypeToPackagePath()`).

I think maybe we can treat non-defined types as empty config and skip the comment search for them. 🤔

**Comment by mx-psi** [comment]
> I think maybe we can treat non-defined types as empty config and skip the comment search for them

I would be in favor of just fixing the forward connector by defining a 
``
