### ISSUE TITLE
azuremonitorexporter does not implement ExportSpans

### ISSUE THREAD

**Issue by itschip** [open-telemetry/opentelemetry-collector-contrib#27053]
### Component(s)

exporter/azuremonitor

### Describe the issue you're reporting

I am having  trouble understanding why the NewFactory and CreateTracesExporter won't match with the WithBatcher.

```go
func initMonitor() (*sdktrace.TracerProvider, error) {
	key := os.Getenv("INSTRUMENTATION_KEY")
	exporterConfig := azuremonitorexporter.Config{
		InstrumentationKey: configopaque.String(key),
	}

	factory := azuremonitorexporter.NewFactory()

	azExporter, err := factory.CreateTracesExporter(context.Background(), exporter.CreateSettings{}, exporterConfig)
	if err != nil {
		panic(err)
	}

	tp := sdktrace.NewTracerProvider(
		sdktrace.WithSampler(sdktrace.AlwaysSample()),
		sdktrace.WithBatcher(azExporter),
	)

	otel.SetTracerProvider(tp)
	otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(propagation.TraceContext{}, propagation.Baggage{}))

	return tp, nil
}
```

`azExporter` does not implement `ExportSpans`. 

Am I doing something wrong here, or is there something that is outdated?

**Comment by crobert-1** [comment]
I don't believe this is the default functionality of the exporters defined in the OpenTelemetry Collector.

I believe you need to use an exporter defined in [this package](https://pkg.go.dev/go.opentelemetry.io/otel/exporters), which is distinct from the collector and its exporters. You also have some more exporter options defined [here.](https://opentelemetry.io/ecosystem/registry/?language=go&component=exporter)

If your goal is to export data to Azure monitor you have a couple possible options:
1. If Azure Monitor accepts the OTLP data format for traces, you could try to use the OTLP exporter directly.
2. If not, use the OTLP exporter to send traces to an instance of the OpenTelemetry Collector, which can then use the `azuremonitor` to send traces to the backend.

Sorry for the confusion here, I realize multiple usages of the word `exporter` can be confusing. Let me know if you have any questions, otherwise you can refer to the [OpenTelemetry Demo](https://opentelemetry.io/ecosystem/demo/) to see how the traces can be exported to the collector, which can then pass them on to the backend of your choice.

**Comment by crobert-1** [comment]
I'm going to close the issue, but feel free to let us know if you have any other questions!

**Comment by pavgup** [comment]
Heyyo! I'm actually trying to do ALMOST exactly the same thing here and I'm also running into this exporter not supporting ExportSpans. Is the AzureMonitorExporter supposed to be used differently?
