### ISSUE TITLE
Add JMS exporter

### ISSUE THREAD

**Issue by bputt-e** [open-telemetry/opentelemetry-collector-contrib#27258]
### Is your feature request related to a problem? Please describe.

I would like to export OTEL data through Apache ActiveMQ and while options like Kafka/Pulsar exist, JMS is my only option

### Describe the solution you'd like

A JMS exporter that works with JMS backends (i.e. Apache ActiveMQ). I imagine it'll work similarly to the kafka exporter

**Comment by atoulme** [comment]
Do you have any code towards this goal? Did you by any chance look at how golang code can interact with JMS? Any insight?
Would you be interested in supporting this component moving forward?

**Comment by bputt-e** [comment]
No code written at the moment, it appears https://github.com/ibm-messaging/mq-golang-jms20/tree/main might be worthy to utilize. As far as supporting this component, it depends, we're trying to find another way to egress the data without requiring jms

**Comment by swar8080** [comment]
Maybe this would get more traction and usage if it was specifically for RabbitMQ instead of JMS? That misses out on SQS and ActiveMQ support, but RabbitMQ is pretty popular, and then this wouldn't be limited to Java applications! That's the approach datadog is using for their telemetry pipeline, with separate exporters for [RabbitMQ](https://vector.dev/docs/reference/configuration/sinks/amqp/) and SQS

With that approach, there's the [RabbitMQ go client](https://github.com/rabbitmq/amqp091-go). It uses the AMQP 0.9.1 protocol which unfortunately doesn't seem compatible with any other major queues

I'm starting to build this for fun...currently looking at similar exporters like kafka and apache pulsar. Let me know if anyone wants to team-up or has suggestions for how to build it

**Comment by atoulme** [comment]
As you do this note we are trying to have encoding extensions to share across components.

**Comment by swar8080** [comment]
It looks like JMS is just an API specification, not a common wire protocol. Each queue expects its own wire protocol, like OpenWire for ActiveMQ, and an adapter built on-top of the AMQP protocol for RabbitMQ

@bputt-e an exporter specifically for ActiveMQ would probably be needed if you're still interested. https://github.com/Azure/go-amqp is the best-maintained client library I found for it
