### ISSUE TITLE
Add new calls to adopt status reporting for the prometheus receiver

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-collector-contrib#27605]
### Component(s)

receiver/prometheus

### Is your feature request related to a problem? Please describe.

With the merging of https://github.com/open-telemetry/opentelemetry-collector/pull/8169, we should begin moving over some components to start reporting. The prometheus receiver is very widely used and would be a great first candidate.

### Describe the solution you'd like

Adhere to the ComponentStatus interface.

### Describe alternatives you've considered

n/a

### Additional context

I can take this on :)

**Comment by arjunmahishi** [comment]
I was looking around to see if there are any issues I can pickup. Is this still relevant?

Looks like some things have changed since this issue was created. 

1. https://github.com/open-telemetry/opentelemetry-collector/pull/8169 introduces `ReportComponentStatus`. This seems to be deprecated in the favor of `ReportStatus`. 
2.  I see `ReportStatus` being used in `prometheusreceiver` (in 2 places). Is there anything pending?
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/8ae1539c84a55140075063d27e62eb561f9b5dab/receiver/prometheusreceiver/metrics_receiver.go#L243

@jaronoff97 @bryan-aguilar
