### ISSUE TITLE
Switching to resource_attributes enabled all resource attributes instead of opt-in like before

### ISSUE THREAD

**Issue by Tadimsky** [open-telemetry/opentelemetry-collector-contrib#28832]
### Component(s)

processor/resourcedetection

## Description

I got a warning in the collector to switch over to using `resource_attributes` instead of `attributes` for my ECS resource detection.
I did so and then noticed that my metric cardinality increased significantly.

It looks like `resource_attributes` changed the behaviour from opt-in to opt-out and for ECS everything is enabled by default.

PR:
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23253

ECS metadata file:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/resourcedetectionprocessor/internal/aws/ecs/metadata.yaml

This was not called out in the Changelog that it would enable all of these properties by default.
It also now means everyone using the `resource_attributes` has to keep up to date on the list of attributes and disable them if any more are added. This seems like it would be a breaking change each time we add a new property.

Should we disable them all by default? Or at least match the spec described here: https://github.com/open-telemetry/semantic-conventions/blob/eacb63da1139c8802448614c040d40cd321d6602/specification/resource/semantic_conventions/cloud_provider/aws/ecs.md

### Collector version

v0.34.0

## Environment
ECS Fargate

**Comment by dashpole** [comment]
@dmitryax @mx-psi

**Comment by dmitryax** [comment]
I believe we need to reconsider the default list of attributes. 

Another issue is the config generated by mdatagen only supports going from the default set of metrics/attributes. I think we need to support a way to disable or enable all of them with a one line config option. Then users can opt in or opt out. I need to think more about how the config interface would look like. Any suggestions are welcome.

**Comment by mx-psi** [comment]
> Should we disable them all by default? Or at least match the spec described here: https://github.com/open-telemetry/semantic-conventions/blob/eacb63da1139c8802448614c040d40cd321d6602/specification/resource/semantic_conventions/cloud_provider/aws/ecs.md

Not sure what you mean here with 'match the spec'. AFAICT all attributes added by the detector are in the specification:
- [`cloud.` namespace](https://github.com/open-telemetry/semantic-conventions/blob/v1.23.0/docs/resource/cloud.md)
- [`aws.ecs` namespace](https://github.com/open-telemetry/semantic-conventions/blob/v1.23.0/docs/resource/cloud-provider/aws/ecs.md)
- [`aws.logs` namespace](https://github.com/open-telemetry/semantic-conventions/blob/v1.23.0/docs/resource/cloud-provider/aws/logs.md)

All of them are marked as ['Recommended'](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.27.0/specification/common/attribute-requirement-level.md#recommended), which means that:

>  Instrumentations SHOULD add the attribute by default if it's readily available and can be [efficiently populated](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.27.0/specification/common/attribute-requirement-level.md#performance-suggestions). 

and that we should avoid adding it

> due to [performance](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.27.0/specification/common/attribute-requirement-level.md#performance-suggestions), security, privacy, or other consideration[s]

I think the current behavior is the right choice with regards to what the specification says. Do you think there are reasons to not add a specific attribute (performance, security or otherwise)?
