### ISSUE TITLE
Replace existing deb/fpm workflows with goreleaser

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#28830]
### Describe the issue you're reporting

Currently we build the fpm/deb packages differently than we do in the releases repo, this should be consistent. It will also resolve the issue of updating to the latest version of ubuntu.

**Comment by cwegener** [comment]
> It will also resolve the issue of updating to the latest version of ubuntu.

That issue is actually unrelated to the package building. It's an issue with the package installation testing that happens after the packages are built, see #30239 and #30202 



Consistently building the binaries the same way during development and release will be good to have for some peace of mind though.

I'm happy to have a look at how big that migration task is and make a plan for the migration.
