### ISSUE TITLE
[pkg/stanza] not drop logs on timestamp parsing error

### ISSUE THREAD

**Issue by newly12** [open-telemetry/opentelemetry-collector-contrib#29003]
### Component(s)

pkg/stanza

### Is your feature request related to a problem? Please describe.

in case of timestmap parsing error, fall back to observed timestamp instead of dropping logs

### Describe the solution you'd like

add a config for this behavior

**Comment by djaglowski** [comment]
I think there are two separate proposals here.

1. Ensure logs are not dropped. This _should_ be possible today but it sounds like you've experienced otherwise? Would you be willing to provide a test case which demonstrates this?

2. Fall back to observed timestamp. This is not the appropriate behavior as defined by our data model. The timestamp should remain empty and it is up to exporters to determine what to do. See [`ObservedTimestamp`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-observedtimestamp): `For converting OpenTelemetry log data to formats that support only one timestamp or when receiving OpenTelemetry log data by recipients that support only one timestamp internally the following logic is recommended: Use Timestamp if it is present, otherwise use ObservedTimestamp.`

**Comment by crobert-1** [comment]
@newly12 Can you confirm whether or not logs were being dropped, as asked in question 1 [above](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29003#issuecomment-1810819407)?

**Comment by newly12** [comment]
@djaglowski sorry for late response. you are correct, if I have `on_error` set to `send`, the entry is still sent. 

> Fall back to observed timestamp. This is not the appropriate behavior as defined by our data model. The timestamp should remain empty and it is up to exporters to determine what to do. See [ObservedTimestamp](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-observedtimestamp): For converting OpenTelemetry log data to formats that support only one timestamp or when receiving OpenTelemetry log data by recipients that support only one timestamp internally the following logic is recommended: Use Timestamp if it is present, otherwise use ObservedTimestamp.

sounds good.
