### ISSUE TITLE
[exporter/prometheusremotewriteexporter] does not compile on Go v1.21

### ISSUE THREAD

**Issue by gr0l0rg** [open-telemetry/opentelemetry-collector-contrib#29112]
## Description

Building custom collector that imports `exporter/prometheusremotewriteexporter` fails on Go 1.21

## Steps to Reproduce

Import  `exporter/prometheusremotewriteexporter` v0.88 while building on Go 1.21.x

## Expected Result

Successful compilation

## Actual Result
Compilation fails with this error
```
../go/pkg/mod/github.com/prometheus/prometheus@v0.47.2/model/labels/labels.go:365:23: type func(a Label, b Label) bool of func(a, b Label) bool {…} does not match inferred type func(a Label, b Label) int for func(a E, b E) int
```

I opened an issue in the prometheus repo [here](https://github.com/prometheus/prometheus/issues/13128) and it looks like it was fixed in the version v0.48.0. I guess you need to upgrade the dependency version in order to compile on Go 1.21.

### Collector version

v0.88

## Environment
Exporter v0.88
Go v1.21.x

**Comment by Aneurysm9** [comment]
In addition to what @crobert-1 has said about picking up the newer Prometheus library versions when they are released, I'll also note that the collector contrib `v0.88.0` release was [built with Go 1.21.3](https://github.com/open-telemetry/opentelemetry-collector-releases/actions/runs/6625913247/job/17997806607#step:6:8).  If you encounter recurrence of this failure after the Prometheus dependency is updated please provide a minimal reproduction so that we can further investigate the issue.
