### ISSUE TITLE
flag includes invalid characters 

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#29158]
### Component(s)

exporter/googlemanagedprometheus

### What happened?

See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6852247654/job/18630332796?pr=29122

```
go test -race -timeout 300s -parallel 4 --tags="" -cover ./... -covermode=atomic -args -test.gocoverdir="/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/coverage/unit"
?   	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlemanagedprometheusexporter/internal/metadata	[no test files]
panic: invalid ID "gcp.untyped_double_export": invalid character(s) in ID
```

**Comment by codeboten** [comment]
@mx-psi

**Comment by dashpole** [comment]
The feature gate is still needed.  It is for an internal (to google) use of the collector, so we don't advertise it in our README.  It will be removed without graduation after https://github.com/open-telemetry/opentelemetry-specification/issues/3058 is fixed, and implemented in the collector.

Is there a way to exempt that feature gate?  Otherwise, I can update the GCP exporter to use a different name.  What characters are allowed?

**Comment by codeboten** [comment]
@mx-psi @dashpole since this will be blocking the release, I would suggest allowing the underscores for now. WDYT?

**Comment by mx-psi** [comment]
Filed open-telemetry/opentelemetry-collector/pull/8865 in case we want to allow underscores instead of fixing this gate. If the fix by David can be filed by EOD, I think we should go with that, otherwise my PR should be mergeable as is.

**Comment by codeboten** [comment]
Adding @jpkrohling to ensure there isnt a release made until this is cleared up. I also labeled the PR as release:blocker

**Comment by codeboten** [comment]
Thanks for the quick fix @dashpole, I've updated the dependency here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29122/commits/6b4398cc57656d3e61a5a6bb2aa7d5698394ebdd

**Comment by dashpole** [comment]
I just cut a release.  Can you update to v0.45.0?
