### ISSUE TITLE
Support for OAuth for Elastic Search exporter

### ISSUE THREAD

**Issue by davidbuchanan** [open-telemetry/opentelemetry-collector-contrib#29329]
### Component(s)

exporter/elasticsearch

### Is your feature request related to a problem? Please describe.

Yes due to firm wide security policy our requirements firm cannot use basic Auth or apk-key option for authentication.

### Describe the solution you'd like

Allow mechanism for this component to use OAuth as an authentication method.

### Describe alternatives you've considered

Basic Auth and api-kay

**Comment by crobert-1** [comment]
Good idea. There's an existing [oauth extension](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/oauth2clientauthextension) that could be used for this, but it requires exporters to use the standard [HTTP exporter configuration module](https://github.com/open-telemetry/opentelemetry-collector/tree/main/config/confighttp#client-configuration). The elastic search exporter currently defines all of its own configuration options, rather than relying on the standard package. 

The code owners would have to look into the effort required here to move to use the standard library, and this would probably be a breaking change, but I think this is a valid request.
