### ISSUE TITLE
[processor/resourcedetection] eks detector does not check if it's running on AWS

### ISSUE THREAD

**Issue by jrcamp** [open-telemetry/opentelemetry-collector-contrib#2977]
The eks detector in resourcedetection only checks if it's on k8s and does not verify that it is on AWS.

**Comment by alolita** [comment]
@aateeqi can you take a look at this issue?

**Comment by aateeqi** [comment]
@alolita At this stage, this might not be able to be done and we may have to rely on our current check. 

My original idea was to use instance metadata to detect if we're running on AWS but this may not be possible since metadata is not available in fargate.

In the current state, we assume that the customer only include `eks` in their config if their running on AWS which may be a fair assumption.

**Comment by jefchien** [comment]
@aateeqi Can this be closed?
