### ISSUE TITLE
[receiver/googlecloudpubsub] do not skip lifecycle tests

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#29997]
These tests should not be skipped

              add issue to not skip lifecycle tests

_Originally posted by @codeboten in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29940#discussion_r1429205449_

**Comment by webstradev** [comment]
Are all of these just a case of removing the part from the metadata.yml that skips the lifecycle tests?

**Comment by codeboten** [comment]
@webstradev for these issues:
- the config has to be removed from metadata.yml
- the tests must be run
- whatever is failing must be fixed :)

**Comment by webstradev** [comment]
In that case happy to pick one or some of these up. Do any of them have priority over others.

**Comment by hamzmu** [comment]
@codeboten is this issue still open?

**Comment by codeboten** [comment]
@hamzmu yup, see config: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5965ee64e4e45476beb71b8e2a7eb6116a09a9a0/receiver/googlecloudpubsubreceiver/metadata.yaml#L17

@webstradev not sure if any are higher priority, feel free to start with any of these :)

**Comment by Sanket-0510** [comment]
after changing the metadata.yaml in order to run the lifecycle test I get this error in lifecycle test 
![Screenshot from 2024-03-03 18-46-42](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/104385297/24bf48b9-d97e-49d6-98c1-41d1faaa3370)

I am not sure if its my system issue or some configuration in the test needs to be fixed, @codeboten can you throw some light over this?
