### ISSUE TITLE
[receiver/podman] do not skip lifecycle checks

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#29994]
This test should not be skipped.

              add issue to not skip lifecycle checks

_Originally posted by @codeboten in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29957#discussion_r1429195847_

**Comment by hamzmu** [comment]
@codeboten is this issue still open?

**Comment by codeboten** [comment]
@hamzmu yup, tests are still skipped: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5965ee64e4e45476beb71b8e2a7eb6116a09a9a0/receiver/podmanreceiver/metadata.yaml#L13

**Comment by atoulme** [comment]
Done!

**Comment by Sanket-0510** [comment]
can I take this one?

**Comment by Sanket-0510** [comment]
here also if you run the Lifecycle test for podmanreceiver it will fail
![Screenshot from 2024-03-03 18-09-25](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/104385297/be871cf7-72dc-4d12-adc6-f1443b47f3b1)


Error - permission denied

**Comment by hamzmu** [comment]
@codeboten @rogercoll any idea how to run the tests? This is one of my first prs and a similar issue suggested to ran the following:
`make generate, make -C receiver/podmanreceiver test`
giving me the following error/message:
<img width="968" alt="Screen Shot 2024-03-09 at 12 08 28 AM" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/75766435/00d6ad8c-ac0d-4902-a3a8-0a2c134fc2d7">
Is there anything else I need to validate the tests?

**Comment by rogercoll** [comment]
WIP

**Comment by rogercoll** [comment]
The current lifecycle of the podman's receiver (also the docker one) depends on the `start` scraper's functionality. On start, it tries to get all the healthy containers so it does not need to fetch them all on every scrape. The lifecycle checks fail, as it requires a Podman's socket on startup (`unix:///run/podman/podman.sock`) to fetch all the containers: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/podmanreceiver/receiver.go#L72


I think for the dockerstats receiver works because the socket is available on the CI. It fails on my local environment (docker disabled):

```
=== RUN   TestComponentLifecycle/metrics-lifecycle
    generated_component_test.go:62: 
        	Error Trace:	/home/neck/Documents/github/rogercoll/opentelemetry-collector-contrib/receiver/dockerstatsreceiver/generated_component_test.go:62
        	Error:      	Received unexpected error:
        	           	Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
        	Test:       	TestComponentLifecycle/metrics-lifecycle
--- FAIL: TestComponentLifecycle (0.01s)
    --- PASS: TestComponentLifecycle/metrics-shutdown (0.00s)
    --- FAIL: TestComponentLifecycle/metrics-lifecycle (0.00s)
```

@codeboten Do you know how this issue is approach by other components? Should we change the scraper start logic? It seems to me, that enabling the socket on the CI is more an integration test.

**Comment by rogercoll** [comment]
For the moment, I create PR to align the shutdown method with the dockestats receiver.
