### ISSUE TITLE
When I add the basic/auth  extention to opentelemetry it throwing an error decoding 'extensions': unknown type: "basicauth"

### ISSUE THREAD

**Issue by nikhil-ht-el** [open-telemetry/opentelemetry-collector-contrib#30251]
### Describe the issue you're reporting

here is my openetelemetry config file 
```
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:5555

exporters:
  logging:
    loglevel: debug
  otlphttp:
    endpoint:https://tempo-dev.com
    auth:
      authenticator: basicauth/client
extensions:
  basicauth/client:
    client_auth: 
      username: ${username}
      password: ${password}
service:
  extensions: [basicauth/client]
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [otlphttp]
    traces:
      receivers: [otlp]
      exporters: [otlphttp,logging]

```
I want to push basic auth header when pushing the traces and matrics to the tempo address so that is why I added the basicauth/client  extension in opentelemetry but it throwing the below error.(using otel/opentelemetry-collector:0.87.0 version)

```
Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'extensions': unknown type: "basicauth" for id: "basicauth/client" (valid values: [zpages memory_ballast health_check pprof])
2024/01/02 10:34:19 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'extensions': unknown type: "basicauth" for id: "basicauth/client" (valid values: [zpages memory_ballast health_check pprof])
```

**Comment by crobert-1** [comment]
Hello @nikhil-ht-el, this is because you're using what is referred to as the `core` distribution OpenTelemetry Collector, not the `contrib` distribution. Note your image name: `otel/opentelemetry-collector:0.87.0`. If you use the contrib image, the extension will be included.

This image should work instead: `otel/opentelemetry-collector-contrib:0.87.0`

[Note in the README the supported distributions.](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/basicauthextension#basic-authenticator)

**Comment by crobert-1** [comment]
Please feel free to let us know if you have any more questions, happy to help! If you run into more issues with this extension please file a new issue. 👍

**Comment by nikhil-ht-el** [comment]
Thanks @crobert-1
