### ISSUE TITLE
[exporter/kafkaexporter] Messages Above Producer.MaxMessageBytes Will Be Retried Instead Of Dropped

### ISSUE THREAD

**Issue by rjduffner** [open-telemetry/opentelemetry-collector-contrib#30275]
### Component(s)

exporter/kafka

## Description

We are noticing that when a log gets created that is larger than Producer.MaxMessageBytes, the kafka exporter fails to send it and then retries.

```
2024-01-03T16:17:49.375Z	info	exporterhelper/retry_sender.go:177	Exporting failed. Will retry the request after interval.	{"kind": "exporter", "data_type": "logs", "name": "kafka", "error": "Failed to deliver 1 messages due to kafka: invalid configuration (Attempt to produce message larger than configured Producer.MaxMessageBytes: 1126653 > 1000000)", "interval": "5.817752834s"}
```

We are not sure why its retrying as this message will never be able to be sent (as its above Producer.MaxMessageBytes).

Is there any clarity as to this choice? I understand we could use the on_error: drop feature (and we probably will) but I am curious as to why its not log and drop already?

## Steps to Reproduce

Create a message larger than Producer.MaxMessageBytes and attempt to export it via the kafka exporter.

## Expected Result

Error is logged and then message is dropped

## Actual Result

Error is logged and then message is retried

### Collector version

0.87.0

## Environment
EKS
Amazon Standard AMI
Splunk OTEL Collector Helm Chart

### Log output

```shell
2024-01-03T16:17:49.375Z	info	exporterhelper/retry_sender.go:177	Exporting failed. Will retry the request after interval.	{"kind": "exporter", "data_type": "logs", "name": "kafka", "error": "Failed to deliver 1 messages due to kafka: invalid configuration (Attempt to produce message larger than configured Producer.MaxMessageBytes: 1126653 > 1000000)", "interval": "5.817752834s"}
```

**Comment by crobert-1** [comment]
Hello @rjduffner, thanks for filing this issue! It looks like the problem you're facing is a result of a lack of granularity in errors returned by [Sarama](https://github.com/IBM/sarama), and the [exporter's retry functionality](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/70425e78a68e9decd5a180d1569af153cb4e9b2d/exporter/kafkaexporter/factory.go#L208). 

The kafka exporter is using Sarama as the kafka client. Sarama is [failing with the error message](https://github.com/IBM/sarama/blob/d9abf3cfb14d41fbc059d0f36195603000b1aad2/async_producer.go#L455) you've shown, and returning as expected. However, on the collector side of things, [as long as the error isn't permanent](https://github.com/open-telemetry/opentelemetry-collector/blob/8ee1f1374361c388786e61288f701be49b4f580f/exporter/exporterhelper/retry_sender.go#L101) it will attempt to retry exporting the data. This error is not considered permanent by Otel or Sarama.

I think the best option may be to add logic to the exporter to detect what kind of error was hit, and upgrade the error to permanent to allow dropping data instead of infinite retries. It looks like there's an [open issue against Sarama](https://github.com/IBM/sarama/issues/2655) that discussses detecting this kind of error, we could add similar logic to the exporter's functionality.

**Comment by rjduffner** [comment]
Thanks for the explanation @crobert-1.
