### ISSUE TITLE
Use OTLP headers to dynamically set prometheusremotewrite exporter values

### ISSUE THREAD

**Issue by justindesilets** [open-telemetry/opentelemetry-collector-contrib#30310]
### Component(s)

exporter/prometheusremotewrite

### Is your feature request related to a problem? Please describe.

When the otel-collector is started, the prometheusremotewrite reads in the configuration and then runs statically for the duration of the process. This prevents you from building a horizontal ingestion point where you could have multiple tenants sending metrics in and then having them dispatched to different endpoints / tenant IDs.

### Describe the solution you'd like

Using the OTEL_EXPORTER_OTLP_METRICS_HEADERS with each tenant's application, they would send their remote URL and credentials as a headers. The prometheusremoteagent would then apply this to its writes to the matching Cortex backend, storing each tenants metrics into their own tenant space.

### Additional context

The intent here is to be able to provide an scalable multi-tenant ingestion point where internal teams could send all of their metrics to. This would allow for a self-service model for these tenants to easily be able to silo their data from each other when storing it into Cortex.

**Comment by jmichalek132** [comment]
I am not sure this is possible to implement, as far as I know the the context of the headers of incoming metrics into OTEL collector is not available to exporters. but maybe similar to https://github.com/blind-oracle/cortex-tenant we could use a configurable resource attribute as tenant.

**Comment by jmichalek132** [comment]
A discussed during the Opentelemetry Prometheus WG the goal of this exporter is to mirror prometheus remote write capabilities. Since Prometheus doesn't support this, we don't want to diverge from prometheus, also the use case you are describing should be solvable while using existing proxies such as  https://cortexmetrics.io/docs/guides/auth/#cortex-tenant or https://github.com/cortexproject/auth-gateway.
Could you @dashpole please close this issue?
