### ISSUE TITLE
[CDCD] Investigate why goimports liter isn't firing for lifecycle generated tests

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#30439]
The tests are generated with not aligned imports, but there are no linter complaints. See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30419 as an example.

Investigate why it's happening and propose a solution.

**Comment by dmitryax** [comment]
Looks like the linter needs to be explicitly enabled on generated files. I think we should do thath

**Comment by codeboten** [comment]
gci skips generated code by default. I've submitted a PR to enable it, not sure how much still will break though 😓

**Comment by braydonk** [comment]
I just ran into this. I was trying to run `make gogci` to update my PR, but it caught all of those generated files as well. So I'm confused to see that apparently `gci` skips generated code by default, because my problem is that it's running on generated code I don't want to touch in my PR. :sweat_smile:
