### ISSUE TITLE
Move carbonreceiver protocol package to an `internal` or `pkg` package

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#30465]
### Component(s)

receiver/carbon

### Describe the issue you're reporting

The carbon receiver protocol package is used by the wavefrontreceiver.

We are trying to limit the API exposed by each collector component and move reusable code to internal or better, pkg packages. Would it be possible to make that change here?

**Comment by mx-psi** [comment]
> to internal or better, pkg packages

Why is `pkg` better? I think we should prefer internal, since this limits usage by outside projects

**Comment by aboguszewski-sumo** [comment]
Technically it should be no problem. However, there is this comment:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/1de0e36f76a5e6a9a9ced094b7b90529ea3beae6/receiver/wavefrontreceiver/receiver.go#L51
and the issue seems to be [as old as the receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9866494271d4468e75ce7388c1a9852e66564f45/receiver/wavefrontreceiver/factory.go#L98), so at this point it seems to me as if existence of wavefront receiver as a separate receiver was a technical debt (correct me if I'm wrong). 

Wouldn't in this case be better to deprecate wavefront receiver and recommend creating new parsers if you want to reuse the carbon receiver? Since this issue is so old, I don't know what was the original intention. The only thing I saw is that the wavefront receiver is indeed older than regex parser for carbon receiver ([this](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/116) vs [this](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/129)).

**Comment by atoulme** [comment]
> > to internal or better, pkg packages
> 
> Why is `pkg` better? I think we should prefer internal, since this limits usage by outside projects

I imagined that there was so much value in the code it might interest folks to use it as a library. I meant it as a compliment.

`internal` is the right choice, agreed.

**Comment by mx-psi** [comment]
> I imagined that there was so much value in the code it might interest folks to use it as a library. I meant it as a compliment.

:smile: I see. For the record, my preference to make something `internal` is just to make it easier to maintain, not a judgement call on the library haha

**Comment by atoulme** [comment]
No problem at all, just trying to entice people while I give them work :)
