### ISSUE TITLE
Delete cmd/mdatagen from contrib

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#30497]
### Component(s)

cmd/mdatagen

### Describe the issue you're reporting

cmd/mdatagen is moving to opentelemetry-collector.

Perform the following actions:
* [x] Deprecate the cmd/mdatagen with a "Deprecated" comment - #30498
* [x] Publish a new version of the package with the deprecation
* [x] Sync up the code changes from contrib to core
* [x] Delete the code

**Comment by atoulme** [comment]
This issue is blocked by https://github.com/open-telemetry/opentelemetry-collector/issues/9281

**Comment by atoulme** [comment]
I filed https://github.com/open-telemetry/opentelemetry-collector/pull/9436 to move any changes that were only made in contrib to core.

**Comment by atoulme** [comment]
I have announced this move in the SIG meeting yesterday https://docs.google.com/document/d/1r2JC5MB7GupCE7N32EwGEXs9V_YIsPgoFiLP4VWVMkE/edit#bookmark=id.uzx4ruz8h632 - would you like to announce this change in the CNCF slack @adrielp ? Is there anything else we need to do to announce this change?

**Comment by adrielp** [comment]
@atoulme , I'd be totally happy to help do that if that's the approach y'all want to take 😊 . I do think it'd be a good idea for those in slack that don't attend the SIGs. The SIG is how I find out about it and found it very helpful. The only reason I commented on this was because I thought maybe there was another method of communication y'all use to communicate with distro maintainers, etc. Slack was definitely the avenue I thought of because I've seen messages in the various otel channels in the past for calls to action on system stability, etc.

**Comment by atoulme** [comment]
Probably opentelemetry-collector by default
