### ISSUE TITLE
awss3exporter: Add Protocol Buf storage format

### ISSUE THREAD

**Issue by adcharre** [open-telemetry/opentelemetry-collector-contrib#30681]
### Component(s)

exporter/awss3

### Is your feature request related to a problem? Please describe.

Currently the only supported format for writing trace data to an S3 bucket is JSON which is not very concise. As a result this use more space than necessary in the S3 bucket and more CPU and network resources.

### Describe the solution you'd like

Add support for writing all OpenTelemetry data in ProtoBuf format.
ProtoBuf output is approximately half the size of JSON formatted data.

**Comment by crobert-1** [comment]
It looks like a code owner has recently filed an issue to separate encodings from this exporter ([here](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30554)). I think it makes sense to add support for sending data encoded in the protobuf format, but the proper implementation would be to rely on the encoding extension rather than the exporter itself implementing this logic.

**Comment by atoulme** [comment]
Please take a look at https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31801, any review helps, thanks!
