### ISSUE TITLE
Duplicate metrics on vcenter receiver in a dual cluster deployment

### ISSUE THREAD

**Issue by adasescu** [open-telemetry/opentelemetry-collector-contrib#30879]
### Component(s)

receiver/vcenter

## Description
Metrics from VMs belonging to a cluster are shown in the other cluster as well.
In our vCenter we have the following tree structure:

```
<root>
+-Datacenter1
   +-Cluster1
   | +-Host1
   | +-Host2
   +-Cluster2
   | +-Host-C2-1
   | +-Host-C2-2
   | | +-VM1
   | | +-VM2
   | | +-VM3
   | | +-VM4
   | +-Host-C2-3
   | +-ResourcePool1 
   | | +-VM1
   | | +-VM2
   | | +-VM3
   | | +-VM4
```
Metrics from VM1, VM2, VM3 and VM4 appear under Cluster1->Host-C2-2 and on Cluster2->Host-C2-2. It seems that the relationship between the cluster and the host isn't reflected in the scraper code.

Also I couldn't find integration tests for multiple clusters examples.
## Expected Result
The metrics for VMs to be under the cluster they belong to.

## Actual Result
The VMs are reported under both clusters.

### Collector version

0.77.0-dev, 0.90.1-dev

## Environment
vCenter Version: 7.0.3 Build: 19234570

**Comment by djaglowski** [comment]
@schmikei, this seems like an important bug. Are you able to take a look?

**Comment by schmikei** [comment]
> @schmikei, this seems like an important bug. Are you able to take a look?

Yeah I think there may be a legitimate issue since VMs are not directly assigned  to a cluster when requested from the API Inventory. The inventory for the VMs are at a per datacenter level from my understanding so each VM will need a request its host into cluster if my head is heading in the right direction for a fix. 

I can take a look into seeing if we can derive it from the runtime host but it may have some performance implications for each VM if we have to do that lookup step anywhere in the scrape.

Will try and take a look!

**Comment by schmikei** [comment]
Small update on this, just have been swamped with other work

I believe I have a fix related to mapping in memory the VM references associated from their Host or Resource Pool from the Inventory API to their respective Cluster. I think I have most of the spiked out code in place, will hopefully get a PR out sometime this week if not next week.

**Comment by djaglowski** [comment]
Thanks @schmikei
