### ISSUE TITLE
[receiver/azuremonitor] Handle errors; don't ignore them

### ISSUE THREAD

**Issue by nslaughter** [open-telemetry/opentelemetry-collector-contrib#31268]
### Component(s)

receiver/azuremonitor

## Description

Code currently fails silently when getting clients from Azure SDK for metrics and metric definitions.

## Steps to Reproduce

Read the code called by start method of scraper. It currently holes errors when instantiating SDK clients the scraper uses.

Look at [getArmClient](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d6068f1c01f6ade3517d87d83863ba4217a55775/receiver/azuremonitorreceiver/scraper.go#L137) and [azureScraper.GetMetricsValuesClient](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d6068f1c01f6ade3517d87d83863ba4217a55775/receiver/azuremonitorreceiver/scraper.go#L157).

## Expected Result

Handle errors.

## Actual Result

Ignores errors.

### Collector version

v0.94.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
# N/A
```

### Log output

```shell
N/A
```

### Additional context

N/A

**Comment by crobert-1** [comment]
Agreed, the errors shouldn't be hidden and ignored. I checked and found this has been the functionality since this component was introduced, but there's no comment as to why they're ignored.

I see this is in the call stack of every `scrape` call, so either an error here is pretty impactful, or it would spam logs. I'm not familiar enough with this receiver to know which is true.
