### ISSUE TITLE
[receiver/k8sobjects] Allow regexp with excluding namespaces in watch

### ISSUE THREAD

**Issue by mk-raven** [open-telemetry/opentelemetry-collector-contrib#31761]
### Component(s)

receiver/k8sobjects

### Is your feature request related to a problem? Please describe.

In many cases we are not interested get events from some namespaces. Its could be great if we can use it and dont make overhead about amount of event data in our storage.

### Describe the solution you'd like

For example  allow namespaces = [opentelemetry*], excluded namespace = [*system]

**Comment by TylerHelmuth** [comment]
@mk-raven we have a `namespaces` configuration option that allows you to specify the namespaces from which to collect

**Comment by hvaghani221** [comment]
@mk-raven This should not be implemented at the receiver level since the kube-apiserver doesn't support the use of wildcards in the namespace. 

I recommend getting events from all namespaces and using [filterprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor) to include/exclude events from specified namespaces.

**Comment by TylerHelmuth** [comment]
Since we have existing solutions I am going to close this issue.  @mk-raven please let me know if the proposed solutions dont work and I can reopen and we can keep discussing.
