### ISSUE TITLE
Add StackTrace to exporter/awscloudwatchlogs

### ISSUE THREAD

**Issue by podger** [open-telemetry/opentelemetry-collector-contrib#31905]
### Component(s)

exporter/awscloudwatchlogs

### Is your feature request related to a problem? Please describe.

Is there any technical reason why the stacktrace is not supported in this exporter?

### Describe the solution you'd like

Add the Stacktrace for the cloudwatchlogsexpoter

**Comment by crobert-1** [comment]
Excuse my ignorance, can you share what `StackTrace` means in the context of this exporter?

**Comment by podger** [comment]
@crobert-1 Maybe I'm misusing this exporter but in my use case I use it to upload my application logs (errors, crash, info etc) to cloudwatch. Only the exception message is uploaded. The stacktrace is somehow lost.

**Comment by crobert-1** [comment]
No worries! Thanks for clarifying, that makes sense. The next step is to try to better understand what component is causing the result to be different than what's expected. 

Can you share your full config? Also, can you use the [debug exporter](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/debugexporter) configured with `verbosity: detailed` in your pipeline instead of the Amazon CloudWatch Logs exporter, and then share the output? This will help determine if the exporter itself dropping the stack traces, or if your logs simply don't have them in the first place.

**Comment by podger** [comment]
Trying to setup the debugging exporter I figured it out myself. The .NET LogRecord doesn't track the StackTrace, I have to use different method: Activity.RecordException to track the exception within the trace and I have all metadata there.

Thanks for the help anyway! :)
