### ISSUE TITLE
[exporter/datadog] Host name attributes not honoured in infrastructure list

### ISSUE THREAD

**Issue by atmask** [open-telemetry/opentelemetry-collector-contrib#31934]
### Component(s)

datadog exporter

## Description

datadog exporter does not currently honour several OTEL semantics. In particular, `availability_zone` and `host.name`

## Steps to Reproduce

Configure OTEL collector with the `cloud._availability_zone`, `host.name`, `datadog.host.name`, and `datadog.host.use_as_metadata=true` attributes and the hostmetrics receiver.

## Expected Result

The infra list display hostmetrics under the designated hostname and AZ

## Actual Result

The host name is ignored in favour of cloud vendor specific VM id (which is listed no where on the attributes when using the debug exporter for validations). 

## Workaround
I has to go and configure the fallback `hostname` on the dd exporter to get the correct node name to display. AZ is still broken 

### Collector version

0.96.0

**Comment by mx-psi** [comment]
@atmask Thanks for filing this issue. I think the information you are seeing in the infrastructure list is not the one from your OTLP resources but instead the legacy one that used to be the only sent by the Collector. To validate this and help you further, we will need more data on your configuration and payloads.

So that you don't have to share this information in public, would you mind [filing a support ticket](https://www.datadoghq.com/support/)? You can link to this comment and mention me so that it gets to me. If you already have one, feel free to share the reference number instead.

I will share the resolution of the ticket here once we have dealt with it for people following from home :)

**Comment by atmask** [comment]
@mx-psi , thanks. I opened a support ticket #1603724 with more details and attached the config
