### ISSUE TITLE
Update weekly report to include waiting-for-code-owners

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#32490]
### Describe the issue you're reporting

It would be helpful to see issues/prs with `waiting-for-code-owners` labels on the weekly report, to give maintainers some insight as to where there's a need to get more help from code owners

**Comment by LucaLanziani** [comment]
I was trying to add this but I believe the next run of the job it will fail because there is not JSON data in the latest issue:

https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33243

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/46883/4fdb7738-587e-4f73-a688-aed80b8da539)

vs

https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32407

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/46883/dc66f088-20a6-4e3b-b2bb-183bf5ecd3ee)

**Comment by LucaLanziani** [comment]
This issue was introduced here https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/c7ae39b72de203bbae0cea031728ed630f1dc293

And the reason the job will fail is here:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/workflows/scripts/generate-weekly-report.js#L279-L290

**Comment by LucaLanziani** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33330
