### ISSUE TITLE
Hangfire: Span and Trace Id should be added to hangfire job parameters.

### ISSUE THREAD

**Issue by anhaehne** [open-telemetry/opentelemetry-collector-contrib#32517]
### Is your feature request related to a problem? Please describe.

When opening a job in the Hangfire dashboard i want to be able to associate the hangfire job with the activity. Right now only the reverse is possible as the hangfire job id is added to the activity context.

### Describe the solution you'd like

I would like the trace and span id to be added to the hangfire job parameters. Right now only the opentelemetry_activity_context is added.

**Comment by crobert-1** [comment]
Hello @anhaehne, can you share the configuration of the OpenTelemetry Collector that you're using? This would be helpful for us to properly direct your request.

**Comment by anhaehne** [comment]
Hi @crobert-1, im not using an Collector right now. I plan to collect it in the future but right now i just want to use the span and trace id to correlate hangfire job with a given excution.

The only code i added to my startup.cs is:

`services.AddOpenTelemetry().WithTracing(b => b.AddHangfireInstrumentation()); `

**Comment by crobert-1** [comment]
Okay, I believe in that case since this isn't collector related it should be filed in the [opentelemetry-dotnet repo](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main). (That might not be exactly correct either since I don't have much experience with C# instrumentation, but they should be able to help or redirect from there 👍 )
