### ISSUE TITLE
Support a configurable default agent configuration to be implemented by OpAMP supervisor

### ISSUE THREAD

**Issue by pabloem** [open-telemetry/opentelemetry-collector-contrib#32598]
### Component(s)

cmd/opampsupervisor

### Is your feature request related to a problem? Please describe.

I am implementing the OpAMP protocol across our fleet, and I find that I want agents to implement a default configuration if the supervisor is unable to reach the OpAMP server.

- Why?

We want most hosts to have a simple default config: Receive OTLP logs in a given port and forward them to our log-processing infrastructure. I want to be sure that this configuration will be enabled even in restricted environments (e.g. environments managing sensitive data - thus blocked by firewalls, etc).

Happy to discuss further.

### Describe the solution you'd like

I propose a new parameter `agent.base_config` in the supervisor that points to a base configuration file that is enabled if we can't get another one. Basic implementation is here:

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32192

Another feature of the PR above is that it avoids overwriting the `effective.yaml` config to be sure we don't overwrite a config that might have worked in the past.

**Comment by tigrannajaryan** [comment]
>I propose a new parameter agent.base_config in the supervisor that points to a base configuration file that is enabled if we can't get another one. 

This seems very similar to `collector.config_file` setting defined here https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/opampsupervisor/specification#supervisor-configuration

Would `collector.config_file` work for you?

**Comment by pabloem** [comment]
yes looks like that should work.

**Comment by evan-bradley** [comment]
Just to clarify: do we expect `collector.config_file` will be used even if the Supervisor cannot connect to the OpAMP server? The description says it will be merged with the remote config.

I would expect that a "fallback" config that is used in the case the server is unreachable would be different from a config file that is layered on top of the remote config. @pabloem how do you want this to work in your use case?

**Comment by tigrannajaryan** [comment]
> Just to clarify: do we expect `collector.config_file` will be used even if the Supervisor cannot connect to the OpAMP server? The description says it will be merged with the remote config.

Perhaps we make this the "fallback" config? Does it need to be different?

**Comment by evan-bradley** [comment]
I think the two use cases are different. My understanding of the intent of the current option is based on the description:

>Path to optional local Collector config file to be merged with the config provided by the OpAMP server.

Based on this, my expectation is that this file would supplement/overwrite config provided by the server. I would expect the "fallback" and "extra config" cases to be different. For example in the fallback scenario I may have a specific backend I want to send to.

I would be fine just making this a fallback option and only providing a file that is merged with the config from the server if we have user requests for it. I think inlining config from local files inside the server config (e.g. `${file:extra_config.yaml}`) should be sufficient for now.

**Comment by f7o** [comment]
Would be great to have that option. As of today and with this change( https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35430), the supervisor relies on OpAmp server to be available and on top of that has to send a config to the agent. 

(referring to the opamp-go repo, where it sends a "emtpy" remote config, but not really empty config down overriding the defaults in the supervisor, which essentially removes the nop pipeline).

I can imagine a lot of use cases where it's desirable to have the supervisor manage the collector and run with the last recent effective config. That's imho one of the essential part of it. 

Otherwise, why even persist it, if the OpAMP server is mandatory for the agent to work at all time, the concept of agent/server for a telemetry collection system is kind of obsolete and a lot less reliable that way.
