### ISSUE TITLE
OTLP Json file reading new file as it is added to the watched directory

### ISSUE THREAD

**Issue by yasha145** [open-telemetry/opentelemetry-collector-contrib#32619]
### Component(s)

receiver/otlpjsonfile

### Describe the issue you're reporting

is otlpjsonfile receiver is capable or reading changes to the file only or it responds when there is a new file added to the watched directory?

**Comment by djaglowski** [comment]
The receiver will find new files according to the `include` pattern and `poll_interval` specified in the configuration. If you are testing the behavior manually and not seeing expected results, make sure to vary the first part of the file because it will automatically deduplicated based on initial content. You can read more about this [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/fileconsumer/design.md#deduplication-of-files).

**Comment by djaglowski** [comment]
Closing this as it appears to be behaving as designed.
