### ISSUE TITLE
Enabling OpAMP Supervisor Authentication with Extension

### ISSUE THREAD

**Issue by dmolenda-sumo** [open-telemetry/opentelemetry-collector-contrib#32762]
### Component(s)

cmd/opampsupervisor

### Is your feature request related to a problem? Please describe.

Some vendors have specific authentication methods and the current authentication method between the OpAMP server and OpAMP supervisor is not sufficient. Currently, the only way to solve this problem is to create fork and add custom authentication methods there.

### Describe the solution you'd like

It would be useful to reuse the [authentication extensions](https://opentelemetry.io/docs/collector/building/authenticator-extension/) that are already available. To do this, the supervisor needs to be modified to include the extension in its build. Furthermore, the current supervisor configuration must be extended to allow for the definition of the extension and enable its use in the server definition.

The first step will be to attempt to add extensions to the supervisor in their current form along with all the required dependencies. This will help us determine the number of dependencies needed and whether this number is acceptable for us.

### Describe alternatives you've considered

An alternative would be to somehow separate the logic responsible for authentication from that required by the collector of each extension. This would reduce the number of dependencies needed for the supervisor.  Unfortunately, this solution requires changes to the collector, which will make it much more time-consuming. For this reason, we decided to try the first approach for now.

_No response_

**Comment by BinaryFissionGames** [comment]
Hey @dmolenda-sumo, have you made any progress on this? 

I'd be happy to help with prototyping some different options if you'd like, I think last this was discussed we were considering what the best way to implement this was (e.g. if we had to separate out a different interface for these extensions or not).

**Comment by BinaryFissionGames** [comment]
I'm still interested in helping with this issue!

**Comment by djaglowski** [comment]
I'm going to assign this to @BinaryFissionGames since he's available to work on this now but please let us know @dmolenda-sumo if you were already in progress.

**Comment by dmolenda-sumo** [comment]
Unfortunately I won't be able to work on this issue :(. It's great that @BinaryFissionGames will be able to work on it

**Comment by cforce** [comment]
It would be great if general the concept of "extension" like in opentelemetry collector would be supported, especially the oauth2clientauthextension (https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/oauth2clientauthextension)n would be useful

**Comment by BinaryFissionGames** [comment]
I've taken some time to explore some possibilities here, and we have a few options:

## Option 1: Create some adapter between [websocket.Dialer::DialContext](https://pkg.go.dev/github.com/gorilla/websocket#Dialer.DialContext) and [http.RoundTripper](https://pkg.go.dev/net/http#RoundTripper)

This is the simplest approach, but it has some downsides. Essentially, the [auth.Client](https://github.com/open-telemetry/opentelemetry-collector/blob/63157855b856e9632275c6b1f617e65bf226b4a5/extension/auth/client.go#L18) interface works by allowing an extension to define a RoundTripper. If we can adapt RoundTripper to a Dialer-like interface, we can re-use the existing extensions with no modifications.

For purely http authentication (not websockets), we'd be able to use the normal RoundTripper without any modifications.

Pros:
* We can use the existing authentication extensions as is with no modification.

Cons:
* The interface of the dialer is more restricted than the RoundTripper; the RoundTripper may modify any part of an http request, but only the headers and URL are available for modification in a websocket dialer. This can lead to an authentication extension not working correctly for websockets, while it works perfectly fine for http requests.


## Option 2: Add a new method to the auth.Client interface

This approach is more work, but is much more clear on the limitations of authenticating websockets.

In this approach, we'd add another method to the auth.Client interface, that allows the auth extension to return a Dialer-like interface (implements DialContext for websockets). This would be very similar to the RoundTripper method, where a base dialer is passed in and expected to have it's DialContext method called.

Pros:
* The intention of this method is clear, as well as restricted to only what 
* Future components that need to support websocket auth could use this same interface easily.

Cons:
* Existing auth extensions would need to be updated to support websockets separately

## Option 3: Don't re-use authentication extensions

In this approach, we don't re-use authentication extensions, but instead write separate code to handle authentication in the supervisor.

Pros:
* Doesn't require any disruption to core collector
* Don't need to import any collector packages

Cons:
* Lots of work that could be avoided through re-use
* Bugfixes/features added to collector auth will not automatically come to the supervisor
* Solution would not really make sense in the OpAMP extension, since auth extensions exist

---

In my opinion, option 2 makes the most sense. It's the most work, but is also the most robust option that is also the most flexible.

The interface for dialing a websocket connection just isn't fully compatible with the RoundTripper interface, and I think that could cause us issues down the road, so I don't feel option 1 is fully suitable. 

Option 3 doesn't make sense long-term, because we'd really like these auth methods to be usable in both the extension and supervisor if possible, and I think having a completely separate auth system just for OpAMP is confusing to a user.

@evan-bradley @tigrannajaryan - would like to know if you have any input on this or any other ideas.

**Comment by evan-bradley** [comment]
@BinaryFissionGames Thank you for the detailed writeup. I can also look into this if necessary, but do you know what connection options are available in other WebSocket libraries? My main concern with option 2 is that we make an interface that is overly specific to the Gorilla WebSocket library.

**Comment by BinaryFissionGames** [comment]
> @BinaryFissionGames Thank you for the detailed writeup. I can also look into this if necessary, but do you know what connection options are available in other WebSocket libraries? My main concern with option 2 is that we make an interface that is overly specific to the Gorilla WebSocket library.

This is a good point. I looked into some other websocket libraries, it seems like these are the three biggest ones:
1. https://pkg.go.dev/github.com/gorilla/websocket
2. https://pkg.go.dev/golang.org/x/net/websocket
3. https://pkg.go.dev/nhooyr.io/websocket

I actually wasn't aware of the third one here. What's interesting about that one is that it actually lets you [specify the http client](https://pkg.go.dev/nhooyr.io/websocket#DialOptions). 

If that's the case, we could actually get the RoundTripper to work. We'd need to use this library in the opamp-go library, but it seems doable, and probably simpler in the long run. I think I'll try that out first and see if we run into any issues.

**Comment by BinaryFissionGames** [comment]
We discussed at the Agent WG, it was decided we do not want to change the websocket library as it would be a big change. I'll explore option 2 a bit more and see if I can make an interface that is library agnostic.

**Comment by cforce** [comment]
>We discussed at the Agent WG, it was decided we do not want to change the websocket library as it would be a big change. I'll explore option 2 a bit more and see if I can make an interface that is library agnostic.

@BinaryFissionGames  is there an update?

**Comment by djaglowski** [comment]
This appears to have been implemented by #35507

**Comment by BinaryFissionGames** [comment]
@djaglowski I haven't been keeping up with this, but to clarify - this issue is for the work needed in the supervisor, that issue was for the extension.

Based on a cursory glance at the commits, it doesn't seem to have been implemented in the supervisor, specifically, yet.

**Comment by cforce** [comment]
@BinaryFissionGames  @evan-bradley  

I am confused if now finally the "auth:" is implemented for the supervisor itself:

Can you simply  give a full example how it shall be used?
