### ISSUE TITLE
Logs Serialisation 

### ISSUE THREAD

**Issue by lydiaong** [open-telemetry/opentelemetry-collector-contrib#32975]
### Component(s)

exporter/awscloudwatchlogs, receiver/filelog

### Describe the issue you're reporting

I am using the file log receiver to read a XML file and exporting the logs to AWS CloudWatch.
My original XML logs in the file looks like this `<?xml version="1.0" encoding="UTF-8" ?>`
However, when it is exported out to CloudWatch, it gets encoded like this `\u003c?xml version=\"1.0\" encoding=\"UTF-8\" ?\u003e\r\n\u003cEvents` 

I did a manual testing to CloudWatch to check if the issue lies with CloudWatch but `<hello>` does not get encoded. Attaching a reference below.
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/75523780/cee738ec-f547-4ae5-815e-f5d5d983a233)

Are any workarounds to this serialization issue?
Thanks!

**Comment by andrzej-stencel** [comment]
As @djaglowski [responded](https://cloud-native.slack.com/archives/C01N6P7KR6W/p1715269031051359?thread_ts=1715265061.225519&cid=C01N6P7KR6W) on CNCF Slack

> I see this kind of question a lot and usually it ends up being that the tool you are viewing it with is adding the escapes in order to show you that it is a string

I agree that it's most likely that the data is fine. Note that `<hello>` looks fine, because the XML is not not embedded in JSON. What if you send `{"body":"<hello>"}`?

Also the best way to verify that the data out of the Collector is fine is to use the [Debug exporter](https://github.com/open-telemetry/opentelemetry-collector/commits/main/exporter/debugexporter/README.md) or the [File exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/fileexporter/README.md) and inspect the output from those.

Please reopen if you find that the output from collector is indeed garbled, and post the output from Debug exporter or File exporter or some other tool confirming this.
