### ISSUE TITLE
need k8s.pod.memory.working_set_memory_limit_utilization metric

### ISSUE THREAD

**Issue by halleystar** [open-telemetry/opentelemetry-collector-contrib#33562]
### Component(s)

receiver/kubeletstats

### Is your feature request related to a problem? Please describe.

need k8s.pod.memory.working_set_memory_limit_utilization,  beacuse  k8s pod oom is  Obtained through working_set_memory / memory limit。But there is only k8s.pod.memory_limit_utilization.

### Describe the solution you'd like

need k8s.pod.memory.working_set_memory_limit_utilization metric

### Describe alternatives you've considered

need k8s.pod.memory.working_set_memory_limit_utilization metric

**Comment by ChrsMark** [comment]
Hey @halleystar! Isn't the container's memory_working_set the crucial one here instead of the Pod's one? The OOM killer is triggered based on the container's memory_working_set metric I think, right?

Since we have multiple `memory` metrics I guess it would make sense to have their `*memory*utilization` equivalent ones. This one also has some good justification, but I would love other's opinions here as well.

We should also consider discussing it as part of the https://github.com/open-telemetry/semantic-conventions/issues/1032 as well.

**Comment by halleystar** [comment]
yes! your are right. It should be  container's memory_working_set. I think we should have a relation  *memory*utilization at  the same time. Otherwise we should provide container request and limit memory to calculate memory usage to observe whether OOM is about to occur.
