### ISSUE TITLE
[exporter/prometheus] Support exporting min/max for histogram metrics

### ISSUE THREAD

**Issue by xiepuhuan** [open-telemetry/opentelemetry-collector-contrib#33645]
### Component(s)

exporter/prometheus

### Is your feature request related to a problem? Please describe.

I don't pay attention to histogram bucket, but I want to know histogram max/min

### Describe the solution you'd like

I don't pay attention to histogram bucket, but I want to know histogram max/min

**Comment by teja-v1** [comment]
Summary stats like Max, Min, and Average play a vital role in data analysis, esp. to find root causes and predict the behavior. 

@dashpole : I don't fully understand why this PR is closed. Can you please help me understand?!

Given the fact that current Prometheus Histograms are cumulative, does it mean OTEL has no plans to support Max & Min values for a specific duration, as Prometheus doesn't support it today?

**Comment by dashpole** [comment]
> does it mean OTEL has no plans to support Max & Min values for a specific duration, as Prometheus doesn't support it today?

Yes, but not because of anything Prometheus does or doesn't support. The issue is how the OpenTelemetry spec defines the min and max for histograms: https://github.com/open-telemetry/opentelemetry-specification/blob/445a6835d755c1913a9acaa227997952ac9b4ea2/specification/metrics/data-model.md#histogram

> (optional) The min (min) of all values in the histogram.
> (optional) The max (max) of all values in the histogram.

That means that min and max are required to be the min and max over the entire cumulative window, so SDKs can't offer a windowed min/max version of the metric.

**Comment by teja-v1** [comment]
@dashpole : Thanks David, now I get that there is no possibility to get min and max for a given duration even with OTEL data format. The value addition is limited to the possibility of getting to know about extreme outliers for the entire window. I see the capability expectations to get max and min on certain label-value combinations of a histogram for a given duration are also parked now. 

Prometheus is a great tool to use, but I can request extended support in the future on this case.

Is there a possibility with OTEL collection and using a columnar DB like ClickHouse (maybe SQL instead of PromQL) to get such a possibility? 

In traditional monitoring, these values are captured and used in data analysis. The latest cloud native telemetry technology offers a variety of benefits, but I will also vouch for maintaining the most frequently used use cases.

Please correct me if I'm thinking wrong, I've not been able to follow monitoring features for a while now.

**Comment by Manuelraa** [comment]
> > does it mean OTEL has no plans to support Max & Min values for a specific duration, as Prometheus doesn't support it today?
> 
> Yes, but not because of anything Prometheus does or doesn't support. The issue is how the OpenTelemetry spec defines the min and max for histograms: https://github.com/open-telemetry/opentelemetry-specification/blob/445a6835d755c1913a9acaa227997952ac9b4ea2/specification/metrics/data-model.md#histogram
> 
> > (optional) The min (min) of all values in the histogram.
> > (optional) The max (max) of all values in the histogram.
> 
> That means that min and max are required to be the min and max over the entire cumulative window, so SDKs can't offer a windowed min/max version of the metric.

All these bullet points apply to a single export of a histogram and can therefore change over time.
At least that is my understanding.

Reading the example picture provided it's visible that every export the min and max values change.
Therefore they should represent the max value collected for this specific export and not since application startup.

At least that makes a lot more sense to me.

**Comment by dashpole** [comment]
The picture is displaying a histogram with DELTA temporality.  That is evident since the start time of the metric is updated at each export.
