### ISSUE TITLE
[Redis Receiver] Rename to generic name

### ISSUE THREAD

**Issue by julianocosta89** [open-telemetry/opentelemetry-collector-contrib#33672]
### Component(s)

receiver/redis

### Describe the issue you're reporting

Currently the Redis receiver is called Redis (as expected 😅), but Redis has recently changed its licensing distribution, and Valkey was created by the community to continue the project as an Open Source driven project.
[Valkey/about](https://valkey.io/about/):
> The transition garnered substantial backing from leading tech corporations including AWS, Google, Oracle, Ericsson, and Snap, with the Linux Foundation stepping in to provide a stable platform for this new direction.

[Linux Foundation Launches Open Source Valkey Community](https://www.linuxfoundation.org/press/linux-foundation-launches-open-source-valkey-community).

It would be great to rename the component to a more generic name, as Valkey works perfectly with it.

I've just sent a PR to the OTel demo replacing Redis with Valkey: https://github.com/open-telemetry/opentelemetry-demo/pull/1619

@rogercoll suggested `datastore`, but anything more generic than the Redis name, would be great.

Not sure how we would do this migration without introducing a breaking change though.

**Comment by puckpuck** [comment]
What about `cachestore` to more accurately represent what type of datastore it is.

**Comment by rogercoll** [comment]
> Not sure how we would do this migration without introducing a breaking change though.

Although I would prefer to rename it to a more generic name, I am afraid we will have breaking changes in the configuration if in the future we try to add more `cachestores` other than redis and valkey. 

Another solution would be to move the redis receiver logic into the internal collector's `pkg` and create a new valkey receiver.

**Comment by puckpuck** [comment]
How much should we care about breaking changes in the demo?

`helm upgrade otel-demo ...` is not guaranteed to work correctly because the init-containers may return successfully before the dependent service is upgraded. You don't "upgrade" a docker setup.

**Comment by atoulme** [comment]
The migration would consist of creating a new receiver with the new name, potentially copying code over. We would then deprecate the old receiver and remove it after a period of 6 months or so.

The change would be pervasive because you'd also want to look at all the metric names and descriptions and update them as part of it.

**Comment by julianocosta89** [comment]
> How much should we care about breaking changes on an upgrade in the demo?
> 
> `helm upgrade otel-demo ...` is not guaranteed to work correctly because the init-containers may return successfully before the dependent service is upgraded. You don't "upgrade" a docker compose setup.

@puckpuck I don't think the issue is the OTel demo here, but everyone else using the `RedisReceiver`.

**Comment by andrzej-stencel** [comment]
Redis and Valkey are now two separate products, even if Valkey was forked from Redis at some point. It's not impossible that the implementations of their metrics endpoints will diverge at some point.

We should leave the Redis receiver as is and create a separate Valkey receiver, potentially re-using the code from the current Redis receiver.

**Comment by rogercoll** [comment]
@julianocosta89 @puckpuck We discussed this topic in yesterday's SIG and, as Andrzej pointed out, we think that the best solution would be creating a new `valkey` receiver. As mentioned, they are two different products that might diverge in the future and having a generic cachestore receiver would need to support any future/other cachestore, thus needing to adopt a new breaking configuration. In my opinion, is the same scenaio as having a `podman` and a `docker` receiver instead of a `container` one.

New component's proposal: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33787

Please feel free to add any context or leave a comment on the issue if you would like to contribute to the new receiver as well.

**Comment by rogercoll** [comment]
> @rogercoll can we close this issue out then given the proposal https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33787 seems to be tracking this ask?

sgtm, what do you think @julianocosta89 ?

**Comment by julianocosta89** [comment]
also good from my end.
thank you 😊
