### ISSUE TITLE
add support for cluster agent

### ISSUE THREAD

**Issue by mike9421** [open-telemetry/opentelemetry-collector-contrib#33825]
### Component(s)

cmd/otelcontribcol, receiver/prometheus

### Is your feature request related to a problem? Please describe.

Initially, I deployed the OTel agent on Kubernetes using a DaemonSet. However, due to the large volume of metrics collected, OTel required a significant amount of resources. At this point, the DaemonSet method can no longer afford to allocate the necessary resources to OTel. 

Therefore, I am considering using StatefulSets or Deployments to deploy the OTel agent. This approach would allow me to specifically deploy the OTel agent on certain nodes and independently increase the resources for those nodes. 

Nevertheless, I've noticed a downside to this method: multiple OTel agents might collect the same metrics (such as those from node-exporter). If I create only a single instance, OTel might not be able to process everything efficiently.

### Describe the solution you'd like

Provide a feature similar to a cluster agent for Kubernetes, which enables the avoidance of duplicate scraping of targets that have already been scraped.

**Comment by dashpole** [comment]
There is a solution for this. I would recommend using the opentelemetry operator with the target allocator: https://github.com/open-telemetry/opentelemetry-operator?tab=readme-ov-file#target-allocator.  It splits up the prometheus targets evenly between replicas.

Otherwise, the prometheus reciever's configuration supports the standard prometheus service discovery mechanisms, including the `hashmod` operator for relabel_configs, which is used by the prometheus operator to shard targets.
