### ISSUE TITLE
Content Matching in httpcheck receiver

### ISSUE THREAD

**Issue by agardnerIT** [open-telemetry/opentelemetry-collector-contrib#34069]
### Component(s)

receiver/httpcheck

### Is your feature request related to a problem? Please describe.

I need to retrieve endpoints and ensure that content is available in the DOM. Just because an endpoint returns a `200 OK` doesn't mean it's healthy. A common pattern these days is to `200 OK` return an "Sorry, we ran into an error" page.

### Describe the solution you'd like

A user should be able to specify a "content match" rule for each endpoint. eg. `"This domain is for use in illustrative examples in documents" in http.response_content` for `http://example.com`

### Describe alternatives you've considered

N/A

**Comment by codeboten** [comment]
Thanks for opening the issue @agardnerIT! An option to address a similar feature was proposed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27015, adding it here for context. 

Going from memory, the discussion in the SIG call was that it would be better to add an attribute to an existing metric rather than adding a separate metric to track this.
