### ISSUE TITLE
Prometheus Receiver: scraping metrics from multiple targets that emits metrics of the same name and label keys

### ISSUE THREAD

**Issue by arpitjindal97** [open-telemetry/opentelemetry-collector-contrib#4986]
Reopen of open-telemetry/opentelemetry-collector#1076 

This issue is not resolved and can be seen in latest version

@liamawhite

**Comment by gouthamve** [comment]
Just want to add a note that this is still happening, even on 0328a79ec6d13896f053ab9d05231f02d0eb7b08

**Comment by gouthamve** [comment]
I am fairly sure this is where it is happening:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/351337c957d0ad8b6a614a9c233c01562747586e/exporter/prometheusexporter/accumulator.go#L143-L156

So we have an "accumulator", which stores the lastValue for each metric and then spits out the metric for conversion to Prometheus format here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/351337c957d0ad8b6a614a9c233c01562747586e/exporter/prometheusexporter/collector.go#L236

Now the problem is that the accumulator creates a signature based on only the attributes for the metric, and not the resource attributes. This signature is used to deduplicate the metrics, and this means when two targets expose the same metrics, then only one metric is stored and the other is overridden.

I'll start working on a test for this and then the fix.
