### ISSUE TITLE
Semantic convention translation processor

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-collector-contrib#5036]
**Is your feature request related to a problem? Please describe.**
We need a processor that can perform the translation between semantic convention schema versions outlined in [OTEP-152](https://github.com/open-telemetry/oteps/blob/main/text/0152-telemetry-schemas.md).

**Describe the solution you'd like**
A processor should be implemented that can be configured with a target schema version.  The processor would then use published schema translation information to process all incoming attributes that are associated with a schema version other than the target schema until they have been converted to the target schema.

**Describe alternatives you've considered**
Alternately, a library that can perform this translation could be created and then integrated in the existing resource and attribute processors.

**Comment by ericmustin** [comment]
hello frens, just checking in on this, we're looking into adding schemaUrl support for opentelemetry-ruby, and wanted to see where the rest of the components described in OTEP-152 stand. As far as I can tell there's nothing in prog on a 'schemaUrl transformation' type processor at the moment? Totally fine, just want to understand where I can track work here, or which SIG mtgs would be the right place to discuss this. Otel-collector sig perhaps?

**Comment by Aneurysm9** [comment]
Tigran has started work on a parser for schema instances at https://github.com/open-telemetry/opentelemetry-go/pull/2267. I think this would be the first step toward building a translation library that would be usable in both the Go SDK and the collector.  When we have that in place building this processor should be relatively straightforward.

**Comment by ericmustin** [comment]
have a rough implementation up in ruby (for ref: https://github.com/open-telemetry/opentelemetry-ruby/pull/979, any reviews/feedback super welcome :) ) . 

It's actually a bit unclear to me whether we should be building out the sort've "parser for schema instances" support in language clients too? Like is opentelemetry-go just a nice home for this parser or is the plan that this translation/conversion ought to eventually have an option to occur in a language specific otel library, via some sort of not-yet-defined processor? (since some vendors don't rely on an otel collector as part of their export pipeline, or the environment itself may not permit a collector, ala client-side js/mobile instrumentation, or serverless/a managed PaaS)
