### ISSUE TITLE
Azure Resource Detector

### ISSUE THREAD

**Issue by bd-clara** [open-telemetry/opentelemetry-collector-contrib#5313]
**Is your feature request related to a problem? Please describe.**
* First we have a bug with this MR #2897

Actually it generates on some of my VM an ID with localhost inside when my detector ordering are `[system, azure]` and override to false, by exemple :
`azure_resource_id:xxxxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxx-xxx-xxxx-shared-services-support-rg/microsoft.compute/virtualmachines/localhost`

Azure Resource ID is part of the VM metadata
`curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01"` with key `.compute.resourceId` or if you really want to build it use `.compute.name` in place of host.name

* Also I think we should have azure_resource_name

Best regards,

**Comment by mx-psi** [comment]
@bd-clara would you mind splitting this into two issues, one for the bug and a different one for the feature request. Also @pmcollins can you have a look at the bug part?

**Comment by pmcollins** [comment]
@bd-clara from what I can tell there isn't a bug here, just a misconfiguration.

The detector ordering should be `[azure, system]` -- the first detector to set the hostname wins, and since the hostname from the system perspective is `localhost`, if that detector is listed first, its value will win. Sounds like you want the value from the Azure API to win, so that detector should be listed first.

This behavior is mentioned briefly in the docs here:

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor#ordering

**Comment by pmcollins** [comment]
Thanks @bd-clara. The collector implementation is a direct port of the SignalFx Smart Agent's logic for generating a unique ID in an Azure environment:

https://github.com/signalfx/signalfx-agent/blob/main/pkg/core/hostid/azure.go#L63

By using the same logic, the collector provides continuity on this dimension for customers migrating from the Smart Agent.

I suppose changing how the ID is generated could be a configuration option, which is doable, but it would mean a request for enhancement. Please feel free to reach out to your Splunk contact if you wish to move this forward.

Regarding the detector ordering, I didn't realize that our default configs apparently have the wrong order -- apologies for that. I intend to send out a fix today so other customers don't encounter this problem.

**Comment by mx-psi** [comment]
Bug was identified as a configuration issue.

@bd-clara please open a new issue for the FR if you are still interested
