### ISSUE TITLE
Add ability to filter log records by body (maybe expr language)

### ISSUE THREAD

**Issue by sumo-drosiek** [open-telemetry/opentelemetry-collector-contrib#5679]
**Is your feature request related to a problem? Please describe.**

I want to filter in/out logs by specific body content

**Describe the solution you'd like**
I can see two solutions. All of them should be implemented in [filterprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/0ba52a57f2345f13c16715418108aa8c57019e1f/processor/filterprocessor)

 - Simple solution: run regex against stringified (or only for string typed) body
 - Complex solution: add support for [expr language](https://github.com/antonmedv/expr/blob/master/docs/Language-Definition.md). This is already done for metrics 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by djaglowski** [comment]
I haven't found enough time to become very familiar with how we're approaching filtering in processors yet, but I'll point out a couple things that may help narrow the scope of what we need to support:

1. Somewhat recently, the logs data model was updated to specify that [the body _should_ be a string in all first party applications](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-body). Based on this, I think filtering capabilities should be primarily focus on the case where this is true.
2. Although, the body _should_ be a string, it is not necessarily so. Therefore, even a simple solution should at least validate that the body is a string, rather than assume.
3. The log-collection library inherited a preference for structured bodies from stanza. However, since this violates the data model guideline mentioned above, the library will be updated fairly soon. (I'm targing this month, but it depends on how much I can focus on this.)

**Comment by TylerHelmuth** [comment]
I am currently working on an enhancement to the transform processor that will enable use to write a `drop` function that can use the OTTL's extensive condition framework, which allows access to the log's body.
