### ISSUE TITLE
[hostmetrics receiver] add utilization metrics

### ISSUE THREAD

**Issue by jlegoff** [open-telemetry/opentelemetry-collector-contrib#6221]
The [semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/system-metrics.md) for system metrics mention several `.utilization` metrics:
* `system.cpu.utilization`
* `system.memory.utilization`
* `system.paging.utilization`
* `system.filesystem.utilization`

However, these metrics are currently not provided by the corresponding scrapers. Is it on the roadmap to add them? Thanks!

**Comment by dmitryax** [comment]
Since all the utilization metrics are derived from existing ones, let's add them as optional (with `enabled: false`) in order to avoid flooding backends that don't expect them to come. Support of optional metrics provided by the [new metrics builder](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6429). So before adding optional metrics we need to make sure that the scraper is migrated to the new metrics builder.

**Comment by jlegoff** [comment]
I think all PRs were merged - closing this issue. Thanks everyone!
