### ISSUE TITLE
Install the JS tool to assign codeowners for components PRs

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector-contrib#6375]
Assigned to @dyladan to give us instructions.

**Comment by dyladan** [comment]
Currently the bot is very "dumb". All it really does is assign and request reviews from specified people. When I see that those people have approved, I merge pull request. We currently only use it in contrib because the SDK/API need a little more maintainer oversight. If we want to have it automatically add labels and even merge, then that would require changes to the tooling.

**Comment by atoulme** [comment]
This is now implemented.
