### ISSUE TITLE
[spanmetricsprocessor] All metrics extracted from spans has the same resource attributes, despite the spans' resources are different

### ISSUE THREAD

**Issue by hstan** [open-telemetry/opentelemetry-collector-contrib#6486]
**Describe the bug**
In the span metrics processor, all metrics extracted from spans are sharing the same resource, even when the spans have different resources. (https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/spanmetricsprocessor/processor.go#L234). 
This only makes sense when there's no resource labels on the metrics. Once we decided to attach resource labels to metrics based on spans resource, this all-metrics-under-same-resource approach seems to be incorrect.

**What did you expect to see?**
When processing `spanA` (under span resource A) and `spanB` (under span resource B), the metrics created should be under metrics resource A and metrics resource B

**What did you see instead?**
All metrics created are under the same empty metrics resource.

**Additional context**
The following PR is an experiment to extract resource from spans and attach to generated metrics, which is when we found the issue. It also changed the way the `buildMetrics` function works to meet our expectations.
https://github.com/atlassian-forks/opentelemetry-collector-contrib/pull/1184/files

**Comment by jpkrohling** [comment]
@albertteoh, are you interested in looking into this?

**Comment by albertteoh** [comment]
Yup, I can take a look at this.

**Comment by chenzhihao** [comment]
hey @albertteoh, I wonder have you got a chance to check this?

**Comment by albertteoh** [comment]
At a high-level, this makes sense to me. Please go ahead and create the PR when you get the chance.

**Comment by gbbr** [comment]
I've kind of lost track of what happened here. The support for Resource Attributes that was added in [this PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6717) seems to have been removed without any reference. Is the conclusion that adding resource attributes required aggregating the metrics into different groups as specified in comment https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/403#issuecomment-1017021263 ?

I am here because of a similar reason - I was looking for the instrumentation scope which is lost. Is there any chance we can add that as a dimension via configuration?

**Comment by kovrus** [comment]
@hstan the `spanmetrics` connector addresses this issue already.
