### ISSUE TITLE
[exporter/datadog] add compression

### ISSUE THREAD

**Issue by fabiovianadotcom** [open-telemetry/opentelemetry-collector-contrib#6944]
Data sent from OpenTelemetry collector is not compressed and enabling gzip compression would improve bandwidth usage.

**Describe the solution you'd like**
Similar to what was done in this PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1747

**Comment by mx-psi** [comment]
Thanks for opening the issue! This is in our internal issue tracker too

**Comment by lchayoun** [comment]
@mx-psi Do you have any estimate for this feature?

**Comment by mx-psi** [comment]
@lchayoun apologies for the delay, I was on vacation :) 

For most of the payloads we send, adding compression depends on us updating the internal library used for interacting with the backend. Both the internal library update and adding compression are in our roadmap, and I have written down that we have customers interested on this so that we can prioritize accordingly.

**Comment by take-five** [comment]
Hi, has there been any progress on this?

**Comment by take-five** [comment]
Thank you @mx-psi , appreciate that

**Comment by mx-psi** [comment]
Not stale and not done yet
