### ISSUE TITLE
[tailsamplingprocessor] Processor removes Instrumentation library

### ISSUE THREAD

**Issue by mottibec** [open-telemetry/opentelemetry-collector-contrib#7050]
**Describe the bug**
all traces ingested by the tail-sampling-processor have no Instrumentation library

**Steps to reproduce**
run a collector with the tail-sampling-processor

**What version did you use?**
Version: v0.40

**Additional context**
Looks like the code [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/514a904e0732a740002a28f5cf267cb6db563090/processor/tailsamplingprocessor/processor.go#L433) is doing it.

**Comment by jpkrohling** [comment]
I'll take a look, but I believe this happens because we might receive spans coming from different services, which would likely have different instrumentation libraries.

**Comment by jpkrohling** [comment]
Sorry for taking so long to come back to this. This is basically happening because we group spans based on their trace IDs, here:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b18f924eaaf29a0f9923ad7d4a9eb08017ba17ea/processor/tailsamplingprocessor/processor.go#L299-L312

In short: we get only the spans from the resource spans/instrumentation library spans, get them on a map, and join them together at the place you mentioned within an empty instrumentation library span.

Doing it properly, by keeping the original resource span, would mean that we'd have a bigger memory footprint. I'll play around with this, but I'm not sure most users would find this worth having.

**Comment by pkositsyn** [comment]
> Doing it properly, by keeping the original resource span, would mean that we'd have a bigger memory footprint. I'll play around with this, but I'm not sure most users would find this worth having.

To my mind, it's not about what's worth having and not - it's just a bug, because exported traces simply lack information about instrumentation library after this processor. Yes, memory consumption will be higher, but much more important that everything is correct. Still, any solution in the linked issue about compacting traces should be enough to fix any memory issues

**Comment by jpkrohling** [comment]
Agree. One other aspect to consider is that it would inherently be worse in terms of CPU performance. This might be acceptable, I just need to make sure to run some benchmarks. Or perhaps engage someone who'd be open to run such benchmarks ;-)

**Comment by jpkrohling** [comment]
This seems to be fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25117
