### ISSUE TITLE
Azure Monitor Exporter Questions

### ISSUE THREAD

**Issue by perljusback** [open-telemetry/opentelemetry-collector-contrib#717]
Hey, I got some questions surronding the Azure Monitor Exporter and some inconsistency that i've noticed.

First of all it works great we've mapped OpenTelemetry from node, web and go into the collector and it all gets sent to application insights.

Now when using the OpenTelemetry SDKs we set the resources:
service.name
service.namespace
service.instance.id
that gives:
**namespace.name**

Now when a zipkin span gets sent in it takes service.name and service.namespace and append to service.name giving:
**name.namespace**

The question is what's the correct interpetation? should we do what the zipkin receiver seems to do and merge or is it that the exporter should export in **name.namespace** format?

My next question is around handling sessions and users in application insights, there's fields for it in AI:
**ai.session.id**, should this map to  application.session?
**ai.user.id** my guess is mapped to enduser.id?

Then there's the different types if using opentelemetry-js in the browser:
**ai.device.id: browser
ai.device.type: Browser**

We tried to set these in different ways but with todays logic the HTTP takes precedence unless we do some really fishy abbrevations with rpc or database as drivers for the spans.

We'd be more then happy to assist in implementing some of this logic when it becomes clear on how it should be implemented.

Thank you for the hard work so far tho helped us alot.

**Comment by bogdandrutu** [comment]
@reyang can you answer?

**Comment by reyang** [comment]
Related to #684. Check https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/433#issuecomment-655200895.
@bogdandrutu given the Azure Monitor Exporter for OpenTelemetry Collector is not officially sponsored by Microsoft, I think we can close these issues.

@pcwiese

**Comment by reyang** [comment]
@bogdandrutu it seems I don't have permission to close the issue, need your help here. Thanks.

**Comment by LouisStAmour** [comment]
@perljusback If the community were to suggest a PR with changes, what exactly would you suggest changing with respect to the way the current Application Insights exporter works?

I'm not affiliated in any way with Microsoft but I'm looking at making a PR to add additional support for span events, metrics and logs, now that Application Insights can work with Log Workspaces. 

But I haven't played enough with the existing collector to know where it may have made assumptions about how tracing is currently reported. Please let me know if you've any specific suggestions for changes in reporting behaviour?

**Comment by perljusback** [comment]
@LouisStAmour for us the main question is around the "special" fields that Application Insights have that can be used to correlate a span as i mentioned the ai.* style span information, and what to map between OpenTelemetry <> AI Envelope since even if we add any of these ai.* to a span it will be added as custom metrics.

I would say that the fields that would make the most difference to us is:
ai.session.id
ai.user.id
because that would give us the ability to trace the full flow of a user in application insights.

I also seen there's a javascript exporter for application insigts created by microsoft so if there's changes to be proposed maybe it's an idea to try and align it towards that one?

https://github.com/microsoft/opentelemetry-azure-monitor-js

**Comment by jmealo** [comment]
@perljusback: The opentelemetry-azure-monitor-js just removed the ability to change outgoing telemetry. (The release that does this is on the master branch, it's not published, the version published on NPM has critical issues that crash the process under observation). There are a ton of fields in AI that I was unable to populate no matter how I sent them. (Device information and user location seem to only be derived fields, you cannot set them manually). I would reconsider using AI as the backend for traces until Microsoft ponies up and supports the exporter in collector if at all possible. I would not recommend running the Application Insights module in Node.js due to stability, and performance issues as well as incompatibility with community modules.

**If anyone from the monitor team can coordinate mapping properties from Open Telemetry to their two different schemas (one for AI and one for Log Analytics I believe) that'd be fantastic.** 

I think part of the issue is legacy AI customers may have a different schema/storage backend and now Microsoft has to support both or make some changes to their ingestion API to do all sorts of mapping.
