### ISSUE TITLE
PrometheusReceiver - if no metadata supplied, metric is dropped

### ISSUE THREAD

**Issue by dustin-bingham** [open-telemetry/opentelemetry-collector-contrib#8110]
If no type hint is supplied for an MTS, then the metric gets dropped (instead of defaulting to gauge as per the doc).

**Steps to reproduce**
The quickest way to reproduce is to use the go tests under prometheusreceiver.  Supply a metric series without any metadata.  For example, under metrics_receiver test, make a target page with just a couple of bare gauges and call TestEndToEnd.  

**What version did you use?**
Version: 0.36.0

**Additional context**
It appears that the metadata cache from prometheus returns an empty object if no metadata supplied (which makes sense).  (See newMetricFamily() in metricFamily.go- mc.Metadata(familyName, line 56). However, the type is an empty string (instead of unknown, as one might expect).  Under metricsbuilder.go, convToOCMetricType() doesn't handle an empty string.  It probably should under the case textparse.MetricTypeUnknown, setting it to gauge.

**Comment by Aneurysm9** [comment]
> **What version did you use?**
> Version: 0.36.0

Can you please verify with v0.45?  Significant changes to the metrics conversion pipeline have happened since v0.36.

I am unable to reproduce this with the suggested steps to reproduce on the `main` branch.  Removing the comments from the gauge at https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/metrics_receiver_test.go#L34-L36 results in no failure and removing them from the counter at https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/metrics_receiver_test.go#L38-L39 results in a failure with the metric being a gauge rather than a sum.
