### ISSUE TITLE
Add Logging to Google Cloud Exporter Component

### ISSUE THREAD

**Issue by StefanKurek** [open-telemetry/opentelemetry-collector-contrib#8249]
**Is your feature request related to a problem? Please describe.**
Google Cloud has built in capability to store/view/receive logs, so we should make use of this in the googlecloudexporter (rather than only have it work with traces/metrics)

**Describe the solution you'd like**
Add in the functionality for the existing googlecloudexporter component to handle logs. It should reuse as much of the existing configuration options as possible. It should accept a number of OTEL logs, and create logs that can be viewed in the Google Cloud Logs Explorer for a particular Google Cloud project.

**Describe alternatives you've considered**
None

**Additional context**
I would like to be assigned this as I already have a PR ready for review

**Comment by jpkrohling** [comment]
cc @aabmass @dashpole @jsuereth @punya @tbarker25

**Comment by dashpole** [comment]
cc @[damemi](https://github.com/damemi)

**Comment by dashpole** [comment]
Hey @StefanKurek, just a heads up that your PR will need to change after https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7177.  We are keeping the conversion code from Pdata -> GCP in https://github.com/GoogleCloudPlatform/opentelemetry-operations-go so that we can run integration tests against GCP's apis.

Do you have your PR ready somewhere?

I believe there was also interest in re-using some of the [stanza googlecloud](https://github.com/observIQ/stanza/tree/master/operator/builtin/output/googlecloud) exporter code.  I'm not sure if that is your plan or not.  cc @djaglowski

**Comment by StefanKurek** [comment]
@dashpole Hello. I see now how there would be an entirely new set of configs. The new library that you're using for OTEL to Google formats, does that include logs? Or is that only for metrics/traces? I do have a PR ready to go, but it was not expecting the config changes (and is using the old set of configs). I do have a PR ready right now which is based off of the stanza googlecloud exporter code (but I haven't created it yet)

**Comment by dashpole** [comment]
It doesn't include logs.  We are planning to add logs to that new library, and then include them here.

The config is still ~mostly intact (some fields moved around).  It just lives in the other repo as well now.

**Comment by dashpole** [comment]
This description might help a bit: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/279#issue-1100796832.  For logs, we would want to add `NewGoogleCloudLogsExporter()`, which returns a LogsExporter.  LogsExporter has the following public methods: `LogsExporter.PushLogs()`, and `LogsExporter.Shutdown()`.

**Comment by damemi** [comment]
Would this be easier to discuss directly in the PR review? I would like to see the changes you have @StefanKurek and I'm happy to help review if I can

**Comment by StefanKurek** [comment]
Alright, I can throw up the PR if you want to get a preview of it. Ultimately I'll wait until 7177 is merged in so that I can make the necessary modifications (and not only work in legacy mode).

**Comment by CatalinAdlerDF** [comment]
Hello,

I've been playing around with this one, but i don't like that it seems to treat logs as simple text, not mapping to the gcp even log entry type. 
I am pushing logs to the collector from an ASP.NET Core app, though the built-in exporter, the logs are quite rich, but they are exported to GCP as text, on the `textPayload` field, instead of the `jsonPayload` structured field.

Is there some configuration i am missing ?

Thanks!

**Comment by CatalinAdlerDF** [comment]
Well, i was expecting everythign to work ootb since i am using otel e2e, just connecting components.
The logs form .net code are structured, the log message is structured, has a message, a text template and replacement tokens, has nested scopes, etc....This granular structure is natively issues by the gcp operations libraries and helps tremendously in consumption.

OTEL entry in stackdriver example has only this on text payload field
`textPayload: "Checking {Count} in-progress item and re-scheduling the ones which have been in-progress for more than 21 seconds."`

the equivalent logged by the gcp libraries is in the `jsonPayload` member
``` 
{
format_parameters: {
Count: "0",
{OriginalFormat}: "Checking {Count} in-progress item and re-scheduling the ones which have been in-progress for more than 21 seconds."
},
log_name: "namespace.namespace.class",
message: "Checking 0 in-progress item and re-scheduling the ones which have been in-progress for more than 21 seconds.",
scope: "Listening to... some custom app text",
serviceContext: {
   service: "nnnn",
   version: "vvvvv"
}}
```

As far as I know when u send simple text to gcp, it is treated as `testPayload`, just like picking unstructured lines of text from stdout; when you send gcp even logs to gcp, for eg, by formatting the stdout lines as json text in gcp structure, then you get the richness.

**Comment by dashpole** [comment]
The overall issue is fixed.  The `googlecloud` exporter can be used for logs.
