### ISSUE TITLE
[processor/attributes] Metric tests are broken

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opentelemetry-collector-contrib#8393]
**Describe the bug**
[generateMetricData](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/attributesprocessor/attributes_metric_test.go#L52) function does not generate actual data points. When it is fixed to generate some data points, the tests fail

**What version did you use?**
The bug was introduced in [#8111](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8111)

**Additional context**
Thanks to @hughsimpson for spotting this while working on [#7930](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7930)

**Comment by mattsains** [comment]
I added the following lines to the `generateMetricData` function and caused [TestAttributes_FilterMetrics](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/1b4d33f6eb5b3d774a946866405cc4e11025b5cd/processor/attributesprocessor/attributes_metric_test.go#L188) to fail:

```
g := m.SetEmptyGauge()
dp := g.DataPoints().AppendEmpty()
dp.SetTimestamp(pcommon.NewTimestampFromTime(time.UnixMicro(0)))
dp.SetIntValue(7)
```

The reason the tests pass without this change is that the `attrs` parameter to `generateMetricData` is only used when `m` is not empty (has a type). Otherwise, the attributes are never set on any `Metrics` object and all the tests pass trivially.

I think the bug being surfaced by fixing this problem is here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/coreinternal/processor/filtermetric/filtermetric.go#L33-L36 where there is a case for an expression matcher, a name matcher, but there is no usage of the `ResourceAttributes` field on `MatchProperties`. 

Therefore, no matching happens based on this filter:

```
Resources: []filterconfig.Attribute{{Key: "name", Value: "^[^i].*"}}
```

I'm not very familiar with the code base, so I was hoping someone (@pmm-sumo ?) could verify my hypothesis. It seems like the function I linked above would need to be modified to add functionality to return a `resource_metric` when `config.ResourceAttributes` is not `nil`. Does this make sense?

**Comment by mattsains** [comment]
Btw it looks like all the tests that don't specify a `Resources` filter pass just fine when adding data points to the metrics object

**Comment by mattsains** [comment]
Updated link to suspected bug location (I think this is where it moved to): https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ddaa6841ed8fc908d296179ec67ebb4356b864d6/internal/filter/filtermetric/filtermetric.go#L51-L60

**Comment by mattsains** [comment]
It's not just resources, the metric data point attributes filter is also non-functional

**Comment by mattsains** [comment]
I've created a draft PR that implements both resources and data point attribute filtering: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17017

Let me know what you think!

**Comment by mattsains** [comment]
@boostchicken I think you might be an owner for this processor? If so, could you provide some feedback on what I have so far? Also, I was not sure what to do with the `services` filter field, which the documentation implies should work for metrics, but I'm not sure what field within the metric structure that is referring to specifically.

**Comment by mattsains** [comment]
Also, please assign me to this issue
