### ISSUE TITLE
Produce performance report on every build

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#9121]
As discussed in [this issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9107#issuecomment-1091972066), it would be beneficial to publish the results from the load tests for the collector.

This issue tracks the work to accomplish the first part of what's proposed in that discussion, producing a report and publishing it to a github page for the repository, similar to the python repository.

**Comment by jpkrohling** [comment]
@serkan-ozal, do you think it's possible to historical data for a specific workflow and cause the CI to fail in case it shows a significant performance degradation?

**Comment by serkan-ozal** [comment]
Hi @jpkrohling,

Thanks for bringing this requirement into our attention. That was indeed one of the features we discussed before and put our roadmap already. So it is good to see that this is also related to a real use case by OTEL.

That is definitely possible. We are also about to release an improvement for our PR comment feature which will post results about such workflow or test oriented performance comparisons between current and target branch by checking historical data. So you will be aware of such performance regression by comment.

However it is just a PR comment right now but I think we can also publish such performance insights as check result so that check results will fail if there is a performance regression. Then Github will not allow PR to be merged as there is a failing check results (but of course repo admins can still merge).

Does it make sense?

**Comment by jpkrohling** [comment]
It does make sense. I'll keep this open to keep track of this idea, please keep us posted on Foresight's progress related to this.

**Comment by codeboten** [comment]
I believe this can be closed now, the load test results are produced on every push to main and available here: https://open-telemetry.github.io/opentelemetry-collector-contrib/benchmarks/loadtests/

There will be additional issues around ensuring the stability of the tests.
