### ISSUE TITLE
[exporter/datadog] Possibly incorrect json identifier for host aliases

### ISSUE THREAD

**Issue by ljmsc** [open-telemetry/opentelemetry-collector-contrib#9122]
**Describe the bug**
The json name for host aliases is called `host-aliases` in the datadog exporter but its called `host_aliases` in the datadog agent. Could it be that the name is wrong? I also have issues getting host aliases into datadog via the otel collector.

**Steps to reproduce**
try to export host infos with host aliases

**What did you expect to see?**
host aliases in datadog

**What did you see instead?**
an empty list

**What version did you use?**
0.48.0

**Additional context**
this issue is related to the datadog exporter

**Comment by ljmsc** [comment]
@mx-psi fyi

**Comment by mx-psi** [comment]
I will take a look next week, thanks for the report!

**Comment by mx-psi** [comment]
Hi again! You are right that the Datadog exporter is using an incorrect identifier for this field ([Agent code](https://github.com/DataDog/datadog-agent/blob/5a2ce199bc5811ff7b7adefe3b495b934a70fe03/pkg/metadata/host/payload.go#L27) vs [Exporter code](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/8f6dd0c3a2ccdbe097c865d5f0071dd423c8a7e8/exporter/datadogexporter/internal/metadata/metadata.go#L90)). 

We have discussed this internally and unfortunately I think we have to wait a bit to fix this. There are some edge cases where the current logic for deciding the host metadata hostname is flawed and can lead to hard to debug errors; we are going to be making some changes to improve hostname resolution and host metadata more generally and we want to wait to fix host aliases until these changes are finalized.

If this is causing a lot of pain to you (or anyone else reading this) and you would like to have a short-term fix for this please reach out so that we can figure out a way to address any problems

**Comment by ljmsc** [comment]
Hi, thanks for checking.

Indead we have issues caused by this bug. The cloud metrics (shipped via datadog cloud integration) are not „merged“ with the trace and metric data shipped with the collector.
Can we discuss a quick fix or temporary solution for this? Should we reach out to our internal datadog contact or can we discuss with you?

**Comment by mx-psi** [comment]
Please reach out to your internal contact, yes :) A possible solution is to provide this temporarily via a feature flag, but I want to make sure this is the best way to fix this.

**Comment by ljmsc** [comment]
Will do. Thanks man.
