### ISSUE TITLE
Sqlserverreceiver detailed sample configuration link doesn't work in README.md

### ISSUE THREAD

**Issue by vipuljain24** [open-telemetry/opentelemetry-collector-contrib#9798]
**Describe the bug**
In directory "opentelemetry-collector-contrib/receiver/sqlserverreceiver/", in README.md file, there is a link to detailed sample configurations. On clicking it, it throws 404 error. 

**Steps to reproduce**
Navigate to "opentelemetry-collector-contrib/receiver/sqlserverreceiver/README.md", and click on the link mentioned in configuration section for detailed sample configurations.

**What did you expect to see?**
We expect to see how the sql server receiver can be configured to monitor sql server in windows.

**What did you see instead?**
A 404 error on clicking the link.

**What version did you use?**
On main branch

**What config did you use?**
NA

**Environment**
NA

**Additional context**
None

**Comment by atoulme** [comment]
I can look into this, please assign to me.

**Comment by fatsheep9146** [comment]
> I can look into this, please assign to me.

It's yours. @atoulme

**Comment by crobert-1** [comment]
This dead link was introduced with the receiver itself in #9252. The link in question was to a non-existent (at the time) config file. As we can see in the PR, there's a reference to a config file under `./testdata/config.yaml`, but the PR didn't include this file.

I believe this issue was resolved by #20265 as it added a sample config file that is now referenced by the README. There are no dead links in the README anymore. I believe we can mark this issue as resolved.

**Comment by crobert-1** [comment]
@atoulme or @vipuljain24: If you agree with my last comment, this issue can be closed.

**Comment by atoulme** [comment]
Thanks for looking into it. I believe you, let's close this issue and it can be reopened if there is more work required. Thanks again!
